# arandr
# Autogenerated from man page /usr/share/man/man1/arandr.1.gz
complete -c arandr -l version -d 'show program\\(aqs version number and exit'
complete -c arandr -s h -l help -d 'show this help message and exit'
complete -c arandr -l randr-display -d 'Use D as display for xrandr (but still show the GUI on the display from the e…'
complete -c arandr -l force-version -d 'Even run with untested XRandR versions'

