# arch-chroot
# Autogenerated from man page /usr/share/man/man8/arch-chroot.8.gz
complete -c arch-chroot -s u -d 'Specify non-root user and optional group to use'
complete -c arch-chroot -s h -d 'Output syntax and command line options'

