# asciinema
# Autogenerated from man page /usr/share/man/man1/asciinema.1.gz
complete -c asciinema -s c -d 'is what you want in most cases'
complete -c asciinema -l stdin -d 'Enable stdin (keyboard) recording (see below)'
complete -c asciinema -l append -d 'Append to existing recording'
complete -c asciinema -l raw -d 'Save raw STDOUT output, without timing information or other metadata'
complete -c asciinema -l overwrite -d 'Overwrite the recording if it already exists'
complete -c asciinema -l command -d 'Specify command to record, defaults to $SHELL'
complete -c asciinema -s e -l env -d 'List of environment variables to capture, defaults to SHELL,TERM'
complete -c asciinema -s t -l title -d 'Specify the title of the asciicast'
complete -c asciinema -s i -l idle-time-limit -d 'Limit recorded terminal inactivity to max <sec> seconds'
complete -c asciinema -s y -l yes -d 'Answer [lq]yes[rq] to all prompts (e. g.  upload confirmation)'
complete -c asciinema -s q -l quiet -d 'Be quiet, suppress all notices/warnings (implies -y) Stdin recording allows f…'
complete -c asciinema -s s -l speed -d 'Playback speed (can be fractional) cat <filename>'

