# autorandr
# Autogenerated from man page /usr/share/man/man1/autorandr.1.gz
complete -c autorandr -s h -l help -d 'Display help text and exit'
complete -c autorandr -s c -l change -d 'Automatically load the first detected profile'
complete -c autorandr -s d -l default -d 'Make profile PROFILE the default profile'
complete -c autorandr -s l -l load -d 'Load profile PROFILE'
complete -c autorandr -s s -l save -d 'Save the current setup to profile PROFILE'
complete -c autorandr -s r -l remove -d 'Remove profile PROFILE'
complete -c autorandr -l batch -d 'Run autorandr for all users with active X11 sessions'
complete -c autorandr -l current -d 'List only the current (active) configuration(s)'
complete -c autorandr -l config -d 'Dump the variable values of your current xrandr setup'
complete -c autorandr -l debug -d 'Enable verbose output'
complete -c autorandr -l detected -d 'List only the detected (i. e.  available) configuration(s)'
complete -c autorandr -l dry-run -d 'Don\'t change anything, only print the xrandr commands'
complete -c autorandr -l fingerprint -d 'Fingerprint the current hardware setup'
complete -c autorandr -l force -d 'Force loading or reloading of a profile'
complete -c autorandr -l skip-options -d 'Set a comma-separated list of xrandr arguments to skip both in change detecti…'
complete -c autorandr -l version -d 'Show version information and exit AUTHOR Phillip Berndt <phillip'

