# blkmapd
# Autogenerated from man page /usr/share/man/man8/blkmapd.8.gz
complete -c blkmapd -s h -d 'Display usage message'
complete -c blkmapd -s d -d 'Performs device discovery only then exits'
complete -c blkmapd -s f -d 'Runs blkmapd in the foreground and sends output to stderr (as opposed to sysl…'

