# cifs
# Autogenerated from man page /usr/share/man/man8/cifs.upcall.8.gz
complete -c cifs -s c -d 'This option is deprecated and is currently ignored'
complete -c cifs -l no-env-probe -s E -d 'Normally, cifs'
complete -c cifs -l krb5conf -s k -d 'This option allows administrators to set an alternate location for the krb5'
complete -c cifs -l keytab -s K -d 'This option allows administrators to specify a keytab file to be used'
complete -c cifs -l trust-dns -d 'With krb5 upcalls, the name used as the host portion of the service principal…'
complete -c cifs -l legacy-uid -s l -d 'Traditionally, the kernel has sent only a single uid= parameter to the upcall…'
complete -c cifs -l expire -s e -d 'Override default timeout value (600 seconds) for dns_resolver key'

