# cvtsudoers
# Autogenerated from man page /usr/share/man/man1/cvtsudoers.1.gz
complete -c cvtsudoers -s b -d 'The base DN (distinguished name) that will be used when performing LDAP queri…'
complete -c cvtsudoers -s c -d 'Specify the path to the configuration file.  Defaults to /etc/cvtsudoers'
complete -c cvtsudoers -s d -d 'Only convert Defaults entries of the specified types'
complete -c cvtsudoers -s e -d 'Expand aliases in input_file'
complete -c cvtsudoers -s f -d 'Specify the output format (case-insensitive)'
complete -c cvtsudoers -s h -d 'Display a short help message to the standard output and exit'
complete -c cvtsudoers -s i -d 'Specify the input format'
complete -c cvtsudoers -s I -d 'When generating LDIF output, increment each sudoOrder attribute by the specif…'
complete -c cvtsudoers -s m -d 'Only output rules that match the specified filter'
complete -c cvtsudoers -s M -d 'When the m option is also specified, use password and group database informat…'
complete -c cvtsudoers -s o -d 'Write the converted output to output_file'
complete -c cvtsudoers -s O -d 'When generating LDIF output, use the number specified by start_point in the s…'
complete -c cvtsudoers -s p -d 'When the m option is also specified, cvtsudoers will prune out non-matching u…'
complete -c cvtsudoers -s P -d 'When generating LDIF output, construct the initial sudoOrder value by concate…'
complete -c cvtsudoers -s s -d 'Suppress the output of specific sections of the security policy'
complete -c cvtsudoers -s V -d 'Print the cvtsudoers and sudoers grammar versions and exit'

