# dcadec
# Autogenerated from man page /usr/share/man/man1/dcadec.1.gz
complete -c dcadec -s h -d 'display help and available audio modes'
complete -c dcadec -s s -d 'use program stream demultiplexer, track 0-7 or 0x80-0x87'
complete -c dcadec -s t -d 'use transport stream demultiplexer, pid 0x10-0x1ffe'
complete -c dcadec -s c -d 'use c implementation, disables all accelerations'
complete -c dcadec -s r -d 'disable dynamic range compression'
complete -c dcadec -s o -d 'use audio output driver `mode\''

