# dnssec-coverage
# Autogenerated from man page /usr/share/man/man8/dnssec-coverage.8.gz
complete -c dnssec-coverage -s K -d 'Sets the directory in which keys can be found'
complete -c dnssec-coverage -s f -d 'If a file is specified, then the zone is read from that file; the largest TTL…'
complete -c dnssec-coverage -s l -d 'The length of time to check for DNSSEC coverage'
complete -c dnssec-coverage -s m -d 'Sets the value to be used as the maximum TTL for the zone or zones being anal…'
complete -c dnssec-coverage -s d -d 'Sets the value to be used as the DNSKEY TTL for the zone or zones being analy…'
complete -c dnssec-coverage -s r -d 'Sets the value to be used as the resign interval for the zone or zones being …'
complete -c dnssec-coverage -s k -d 'Only check KSK coverage; ignore ZSK events.  Cannot be used with'
complete -c dnssec-coverage -s z
complete -c dnssec-coverage -s c -d 'Specifies a path to a named-compilezone binary.  Used for testing.  SEE ALSO'

