# dnssec-verify
# Autogenerated from man page /usr/share/man/man8/dnssec-verify.8.gz
complete -c dnssec-verify -s c -d 'This option specifies the DNS class of the zone'
complete -c dnssec-verify -s E -d 'This option specifies the cryptographic hardware to use, when applicable'
complete -c dnssec-verify -s I -d 'This option sets the format of the input zone file'
complete -c dnssec-verify -s o -d 'This option indicates the zone origin'
complete -c dnssec-verify -s v -d 'This option sets the debugging level'
complete -c dnssec-verify -s V -d 'This option prints version information'
complete -c dnssec-verify -s q -d 'This option sets quiet mode, which suppresses output'
complete -c dnssec-verify -s x -d 'This option verifies only that the DNSKEY RRset is signed with key-signing ke…'
complete -c dnssec-verify -s z -d 'This option indicates that the KSK flag on the keys should be ignored when de…'
complete -c dnssec-verify -l with-pkcs11

