# dnssort
# Autogenerated from man page /usr/share/man/man1/dnssort.1.gz
complete -c dnssort -l help -d 'Display some help and exit'
complete -c dnssort -s r -d 'Reverse the sorting comparisons'
complete -c dnssort -l version -d 'Display program version and license and exit'

