# dnssec-revoke
# Autogenerated from man page /usr/share/man/man8/dnssec-revoke.8.gz
complete -c dnssec-revoke -s h -d 'This option emits a usage message and exits'
complete -c dnssec-revoke -s K -d 'This option sets the directory in which the key files are to reside'
complete -c dnssec-revoke -s r -d 'This option indicates to remove the original keyset files after writing the n…'
complete -c dnssec-revoke -s v -d 'This option sets the debugging level'
complete -c dnssec-revoke -s V -d 'This option prints version information'
complete -c dnssec-revoke -s E -d 'This option specifies the cryptographic hardware to use, when applicable'
complete -c dnssec-revoke -s f -d 'This option indicates a forced overwrite and causes dnssec-revoke to write th…'
complete -c dnssec-revoke -s R -d 'This option prints the key tag of the key with the REVOKE bit set, but does n…'
complete -c dnssec-revoke -l with-pkcs11

