# ecryptfs-migrate-home
# Autogenerated from man page /usr/share/man/man8/ecryptfs-migrate-home.8.gz
complete -c ecryptfs-migrate-home -s u -l user -d 'Migrate USER\'s home directory to an encrypted home directory'

