# erofsfuse
# Autogenerated from man page /usr/share/man/man1/erofsfuse.1.gz
complete -c erofsfuse -s o -d 'mount options'
complete -c erofsfuse -s h -l help -d 'display help and exit . SS "erofsfuse options:"'
complete -c erofsfuse -l dbglevel -d 'Specify the level of debugging messages'
complete -c erofsfuse -s d -d 'enable debug output (implies -f)'
complete -c erofsfuse -s f -d 'foreground operation'
complete -c erofsfuse -s s -d 'disable multi-threaded operation'

