# escputil
# Autogenerated from man page /usr/share/man/man1/escputil.1.gz
complete -c escputil -s P -l printer-name -d 'Specify the name of the printer to operate on'
complete -c escputil -s r -l raw-device -d 'Specify the name of the device to write to directly rather than going through…'
complete -c escputil -s m -l model -d 'Specify the precise printer model for head alignment'
complete -c escputil -s u -l new -d 'The printer is a new printer (Stylus Color 740 or newer)'
complete -c escputil -s c -l clean-head -d 'Clean the print head'
complete -c escputil -s n -l nozzle-check -d 'Print a nozzle test pattern'
complete -c escputil -s a -l align-head -d 'Align the print head'
complete -c escputil -s i -l ink-level -d 'Obtain the ink level from the printer'
complete -c escputil -s d -l identify -d 'Query the printer for make and model information'
complete -c escputil -s o -l align-color -d 'Align the color print head (used by Stylus Color 480 and 580 only)'
complete -c escputil -s s -l status -d 'Retrieve printer status'
complete -c escputil -s l -l license -d 'Display the license/warranty terms of this program'
complete -c escputil -s M -l list-models -d 'List the supported printer models'
complete -c escputil -s h -l help -d 'Display a list of all command line options'
complete -c escputil -s q -l quiet -d 'Suppress the banner'

