# eu-elfclassify
# Autogenerated from man page /usr/share/man/man1/eu-elfclassify.1.gz
complete -c eu-elfclassify -l core -d 'PD File is an ELF core dump file'
complete -c eu-elfclassify -l elf -d 'PD File looks like an ELF object or archive/static library (default)'
complete -c eu-elfclassify -l elf-archive -d 'PD File is an ELF archive or static library'
complete -c eu-elfclassify -l elf-file -d 'PD File is an regular ELF object (not an archive/static library)'
complete -c eu-elfclassify -l executable -d 'PD File is (primarily) an ELF program executable (not primarily a DS. O)'
complete -c eu-elfclassify -l library -d 'PD File is an ELF shared object (DSO) (might also be an executable)'
complete -c eu-elfclassify -l linux-kernel-module -d 'PD File is a linux kernel module'
complete -c eu-elfclassify -l loadable -d 'PD File is a loadable ELF object (program or shared object)'
complete -c eu-elfclassify -l program -d 'PD File is an ELF program executable (might also be a DSO)'
complete -c eu-elfclassify -l shared -d 'PD File is (primarily) an ELF shared object (DSO) (not primarily an executabl…'
complete -c eu-elfclassify -l unstripped -d 'PD File is an ELF file with symbol table or '
complete -c eu-elfclassify -l not- -d 'Classification Options'
complete -c eu-elfclassify -s f
complete -c eu-elfclassify -l file -d 'Only classify regular (not symlink nor special device) files'
complete -c eu-elfclassify -l no-stdin -d 'Do not read files from standard input (default)'
complete -c eu-elfclassify -l stdin -d 'Also read file names to process from standard input, separated by newlines'
complete -c eu-elfclassify -l stdin0 -d 'Also read file names to process from standard input, separated by ASCII NUL b…'
complete -c eu-elfclassify -s z
complete -c eu-elfclassify -l compressed -d 'Try to open compressed files or embedded (kernel) ELF images.  Output flags'
complete -c eu-elfclassify -l matching -d 'If printing file names, print matching files (default)'
complete -c eu-elfclassify -l no-print -d 'Do not output file names'
complete -c eu-elfclassify -l not-matching -d 'If printing file names, print files that do not match'
complete -c eu-elfclassify -l print -d 'Output names of files, separated by newline'
complete -c eu-elfclassify -l print0 -d 'Output names of files, separated by ASCII NUL.   Additional flags'
complete -c eu-elfclassify -s q
complete -c eu-elfclassify -l quiet -d 'Suppress some error output (counterpart to --verbose)'
complete -c eu-elfclassify -s v
complete -c eu-elfclassify -l verbose -d 'Output additional information (can be specified multiple times)'
complete -c eu-elfclassify -s '?'
complete -c eu-elfclassify -l help -d 'Give this help list'
complete -c eu-elfclassify -l usage -d 'Give a short usage message'
complete -c eu-elfclassify -s V
complete -c eu-elfclassify -l version -d 'Print program version'

