# extlinux
# Autogenerated from man page /usr/share/man/man1/extlinux.1.gz
complete -c extlinux -s H -l heads -d 'Force the number of heads'
complete -c extlinux -s i -l install -d 'Install over the current bootsector'
complete -c extlinux -s O -l clear-once -d 'Clear the boot-once command'
complete -c extlinux -s o -l once -d 'Execute a command once upon boot'
complete -c extlinux -s M -l menu-save -d 'Set the label to select as default on the next boot'
complete -c extlinux -s r -l raid -d 'Fall back to the next device on boot failure'
complete -c extlinux -l reset-adv -d 'Reset auxiliary data'
complete -c extlinux -s S -l sectors -d 'Force the number of sectors per track'
complete -c extlinux -s U -l update -d 'Updates a previous EXTLINUX installation'
complete -c extlinux -s z -l zip -d 'Force zipdrive geometry (-H 64 -S 32)'
complete -c extlinux -l device -d 'Override the automatic detection of device names'

