# extract_mpeg2
# Autogenerated from man page /usr/share/man/man1/extract_mpeg2.1.gz
complete -c extract_mpeg2 -s h -d 'display help'
complete -c extract_mpeg2 -s s -d 'set track number (0-0xf or 0xe0-0xef)'
complete -c extract_mpeg2 -s t -d 'use transport stream demultiplexer, pid 0x10-0x1ffe AUTHORS Michel Lespinasse…'

