# extract_dts
# Autogenerated from man page /usr/share/man/man1/extract_dts.1.gz
complete -c extract_dts -s h -d 'display help'
complete -c extract_dts -s s -d 'set track number (0-7 or 0x80-0x87)'
complete -c extract_dts -s t -d 'use transport stream demultiplexer, pid 0x10-0x1ffe AUTHORS Michel Lespinasse…'

