# faad
# Autogenerated from man page /usr/share/man/man1/faad.1.gz
complete -c faad -s a -l adtsout -d 'Sets the processing to output to the specified file in MPEG\\(hy4 AAC ADTS for…'
complete -c faad -s b -l bits -d 'Set the output (individual) sample format'
complete -c faad -s d -l downmix -d 'Set the processing to downsample from 5'
complete -c faad -s f -l format -d 'Set the output file format.  The number takes one of the following values: '
complete -c faad -s g -d 'Set the processing to not perform gapless decoding'
complete -c faad -s h -l help -d 'Shows a usage summary'
complete -c faad -s i -l info -d 'Shows information about the about the input file'
complete -c faad -s l -l objecttype -d 'Sets the MPEG\\hy(4 profile and object type for the processing to use'
complete -c faad -s o -l outfile -d 'Sets the filename for processing output'
complete -c faad -s q -l quiet -d 'Quiet - Suppresses status messages during processing'
complete -c faad -s t -l oldformat -d 'Sets the processing to use the old MPEG\\(hy4 AAC ADTS format when outputting …'

