# fido2-token
# Autogenerated from man page /usr/share/man/man1/fido2-token.1.gz
complete -c fido2-token -s C -d 'Changes the PIN of device'
complete -c fido2-token -s D -d 'Deletes the resident credential specified by id from device, where id is the …'
complete -c fido2-token -s G -d 'Gets a FIDO 2'
complete -c fido2-token -s I -d 'Retrieves information on device'
complete -c fido2-token -s L -d 'Produces a list of authenticators found by the operating system'
complete -c fido2-token -s R -d 'Performs a reset on device.  fido2-token will NOT prompt for confirmation'
complete -c fido2-token -s S -d 'Sets the PIN of device.  The user will be prompted for the PIN'
complete -c fido2-token -s V -d 'Prints version information'
complete -c fido2-token -s d -d 'Causes fido2-token to emit debugging output on stderr'

