# fido2-assert
# Autogenerated from man page /usr/share/man/man1/fido2-assert.1.gz
complete -c fido2-assert -s G -d 'Tells fido2-assert to obtain a new assertion from device'
complete -c fido2-assert -s V -d 'Tells fido2-assert to verify an assertion using the PEM-encoded public key in…'
complete -c fido2-assert -s b -d 'Request the credential\'s largeBlobKey, a 32-byte symmetric key associated wit…'
complete -c fido2-assert -s h -d 'If obtaining an assertion, enable the FIDO2 hmac-secret extension'
complete -c fido2-assert -s d -d 'Causes fido2-assert to emit debugging output on stderr'
complete -c fido2-assert -s i -d 'Tells fido2-assert to read the parameters of the assertion from input_file in…'
complete -c fido2-assert -s o -d 'Tells fido2-assert to write output on output_file instead of stdout'
complete -c fido2-assert -s p -d 'If obtaining an assertion, request user presence'
complete -c fido2-assert -s r -d 'Obtain an assertion using a resident credential'
complete -c fido2-assert -s t -d 'Toggles a key/value option, where option is a string of the form key=value'
complete -c fido2-assert -s u -d 'Obtain an assertion using U2F'
complete -c fido2-assert -s v -d 'If obtaining an assertion, prompt the user for a PIN and request user verific…'

