# gssd
# Autogenerated from man page /usr/share/man/man8/gssd.8.gz
complete -c gssd -s D -d 'The server name passed to GSSAPI for authentication is normally the name exac…'
complete -c gssd -s f -d 'Runs  rpc'
complete -c gssd -s n -d 'When specified, UID 0 is forced to obtain user credentials which are used ins…'
complete -c gssd -s k -d 'Tells  rpc'
complete -c gssd -s l -d 'When specified, restricts  rpc'
complete -c gssd -s p -d 'Tells  rpc. gssd where to look for the rpc_pipefs filesystem'
complete -c gssd -s d -d 'This option specifies a colon separated list of directories that  rpc'
complete -c gssd -s M -d 'By default, machine credentials are stored in files in the first directory in…'
complete -c gssd -s v -d 'Increases the verbosity of the output (can be specified multiple times)'
complete -c gssd -s r -d 'If the RPCSEC_GSS library supports setting debug level, increases the verbosi…'
complete -c gssd -s R -d 'Kerberos tickets from this  realm will be preferred when scanning available c…'
complete -c gssd -s t -d 'Timeout, in seconds, for kernel GSS contexts'
complete -c gssd -s T -d 'Timeout, in seconds, to create an RPC connection with a server while establis…'
complete -c gssd -s U -d 'Timeout, in seconds, for upcall threads'
complete -c gssd -s C -d 'In addition to logging an error message for threads that have timed out, the …'
complete -c gssd -s H -d 'Avoids setting $HOME to "/".  This allows rpc'

