# i3-config-wizard
# Autogenerated from man page /usr/share/man/man1/i3-config-wizard.1.gz
complete -c i3-config-wizard -s s -l socket -d 'Overwrites the path to the i3 IPC socket'
complete -c i3-config-wizard -s m -l modifier -d 'Generates the configuration file headlessly.  Accepts win or alt'
complete -c i3-config-wizard -s v -l version -d 'Display version number and exit'
complete -c i3-config-wizard -s h -l help -d 'Display a short help message and exit'

