# i3-nagbar
# Autogenerated from man page /usr/share/man/man1/i3-nagbar.1.gz
complete -c i3-nagbar -s v -l version -d 'Display version number and exit'
complete -c i3-nagbar -s h -l help -d 'Display a short help-message and exit'
complete -c i3-nagbar -s t -l type -d 'Display either a warning or error message'
complete -c i3-nagbar -s m -l message -d 'Display message as text on the left of the i3-nagbar'
complete -c i3-nagbar -s f -l font -d 'Select font that is being used'
complete -c i3-nagbar -s b -l button -d 'Create a button with text button'
complete -c i3-nagbar -s B -l button-no-terminal -d 'Same as above, but will execute the shell commands directly, without launchin…'

