# i3bar
# Autogenerated from man page /usr/share/man/man1/i3bar.1.gz
complete -c i3bar -s s -l socket -d 'Overwrites the path to the i3 IPC socket'
complete -c i3bar -s b -l bar_id -d 'Specifies the bar ID for which to get the configuration from i3'
complete -c i3bar -s v -l version -d 'Display version number and exit'
complete -c i3bar -s h -l help -d 'Display a short help-message and exit'

