# idmapd
# Autogenerated from man page /usr/share/man/man8/idmapd.8.gz
complete -c idmapd -s h -d 'Display usage message'
complete -c idmapd -s v -d 'Increases the verbosity level (can be specified multiple times)'
complete -c idmapd -s f -d 'Runs idmapd in the foreground and prints all output to the terminal'
complete -c idmapd -s p -d 'Specifies the location of the RPC pipefs to be path'
complete -c idmapd -s c -d 'Use configuration file path.  This option is deprecated'
complete -c idmapd -s C -d 'Client-only: perform no idmapping for any NFS server, even if one is detected'
complete -c idmapd -s S -d 'Server-only: perform no idmapping for any NFS client, even if one is detected'

