# isohybrid
# Autogenerated from man page /usr/share/man/man1/isohybrid.1.gz
complete -c isohybrid -s h -d 'br Number of geometry heads (default 64)'
complete -c isohybrid -s s -d 'br Number of geometry sectors (default 32)'
complete -c isohybrid -s e -l entry -d 'Specify parititon entry number (1-4)'
complete -c isohybrid -s o -l offset -d 'br Specify partition offset (default 0)'
complete -c isohybrid -s t -l type -d 'br Specify partition type (default 0x17)'
complete -c isohybrid -s i -l id -d 'br Specify MBR ID (default random)'
complete -c isohybrid -s u -l uefi -d 'Build EFI bootable image'
complete -c isohybrid -s m -l mac -d 'Add Apple File Protocol partition table support'
complete -c isohybrid -l forcehd0 -d 'Assume we are laoded as disk ID 0'
complete -c isohybrid -l ctrlhd0 -d 'Assume disk ID 0 if the Ctrl key is pressed'
complete -c isohybrid -l partok -d 'Allow booting from within a partition'
complete -c isohybrid -s '?' -l help -d 'Display help'
complete -c isohybrid -s v -l verbose -d 'Display verbose output'

