# jack_wait
# Autogenerated from man page /usr/share/man/man1/jack_wait.1.gz
complete -c jack_wait -s w -l wait -d 'br Wait for jackd to be available'
complete -c jack_wait -s q -l quit -d 'br Wait for jackd quit'
complete -c jack_wait -s c -l check -d 'br Only check for existence of jackd, and exit'
complete -c jack_wait -s s -l server -d 'br Connect to the jack server named servername'
complete -c jack_wait -s t -l timeout -d 'br Only wait timeout_seconds'
complete -c jack_wait -s h -l help -d 'br Display help/usage message'
complete -c jack_wait -s v -l version

