# jack_metro
# Autogenerated from man page /usr/share/man/man1/jack_metro.1.gz
complete -c jack_metro -s n -l name -d 'br Specify a name for this instance of the metronome'
complete -c jack_metro -s f -l frequency -d 'br Define the frequency of the "tick" in Hz'
complete -c jack_metro -s D -l duration -d 'br Define the duration of the "tick" in milliseconds'
complete -c jack_metro -s a -l attack -d 'br Define the duration of the attack phase of the "tick" as a percentage of t…'
complete -c jack_metro -s d -l decay -d 'br Define the duration of the decay phase of the "tick" as a percentage of th…'
complete -c jack_metro -l b -l bpm

