# jack_lsp
# Autogenerated from man page /usr/share/man/man1/jack_lsp.1.gz
complete -c jack_lsp -s s -l server -d 'br Connect to the jack server named servername'
complete -c jack_lsp -s A -l aliases -d 'br List aliases for each port'
complete -c jack_lsp -s c -l connections -d 'br List connections to/from each port'
complete -c jack_lsp -s l -l latency -d 'br Display per-port latency in frames at each port'
complete -c jack_lsp -s L -d 'br Display total latency in frames at each port'
complete -c jack_lsp -s p -l properties -d 'br Display port properties'
complete -c jack_lsp -s t -l type -d 'br Display port type'
complete -c jack_lsp -s h -l help -d 'br Display help/usage message'
complete -c jack_lsp -s v -l version

