# jack_property
# Autogenerated from man page /usr/share/man/man1/jack_property.1.gz
complete -c jack_property -s l -d 'list all metadata currently defined'
complete -c jack_property -s d -d 'deletes all metadata for identifier'
complete -c jack_property -s D -d 'delete all currently defined metadata'
complete -c jack_property -s s -d 'sets the metadata associated with key to value for identifer, with its type s…'
complete -c jack_property -s c -d 'interpret a given identifier as a client name rather than a UUID'
complete -c jack_property -s p -d 'interpret a given identifier as a port name rather than a UUID'

