# jfs_fscklog
# Autogenerated from man page /usr/share/man/man8/jfs_fscklog.8.gz
complete -c jfs_fscklog -s d -d 'Format and display a previously extracted JFS fsck service log'
complete -c jfs_fscklog -s e -d 'Extract the JFS fsck service log from  device and store it in a file'
complete -c jfs_fscklog -s f -d 'Specify the file name, overriding the default file name'
complete -c jfs_fscklog -s p -d 'Extract the prior log (as opposed to the most recent log)'
complete -c jfs_fscklog -s V -d 'Print version information and exit (regardless of any other chosen options)'
complete -c jfs_fscklog -s v -d 'option on the JFS device'

