# jfs_tune
# Autogenerated from man page /usr/share/man/man8/jfs_tune.8.gz
complete -c jfs_tune -s J -d 'Attach the JFS external journal located on  external-journal to the JFS file …'
complete -c jfs_tune -s l -d 'List the contents of the JFS file system or external journal superblock that …'
complete -c jfs_tune -s L -d 'Set the volume label of the JFS file system or external journal'
complete -c jfs_tune -s U -d 'Set the universally unique identifier (UUID) of the file system or external j…'
complete -c jfs_tune -s V -d 'Print version information and exit (regardless of any other chosen options)'

