# jpeg2yuv
# Autogenerated from man page /usr/share/man/man1/jpeg2yuv.1.gz
complete -c jpeg2yuv -s b -d 'Frame offset:  skip output of the first \'num\' frames.   (default: 0)'
complete -c jpeg2yuv -s f -d 'Set the frame rate of stream accepts the same numbers'
complete -c jpeg2yuv -s A -d 'Sample aspect ratio.   Default is square pixels (1:1)'
complete -c jpeg2yuv -s I -d 'interlacing mode: p = none / progressive . br t = top field first '
complete -c jpeg2yuv -s L -d '0 = non-interlaced (two successive fields per JPEG file) '
complete -c jpeg2yuv -s l -d 'Specifies the number of loops (default: 0 loops ) '
complete -c jpeg2yuv -s n -d 'Specifies the number of frames to process.  (default: all = -1)'
complete -c jpeg2yuv -s j -d 'Read JPEG frames with the name components as follows:  {1} JPEG filename pref…'
complete -c jpeg2yuv -s R -d 'rescale YUV color values from 0-255 to 16-235 (default: 1)'

