# lav2yuv
# Autogenerated from man page /usr/share/man/man1/lav2yuv.1.gz
complete -c lav2yuv -s m -d 'Force mono-chrome'
complete -c lav2yuv -s c -d 'Conceal frames containing corrupt MJPEG data by repeating the preceeding good…'
complete -c lav2yuv -s S -d 'Output a scene list with scene detection'
complete -c lav2yuv -s T -d 'Set scene detection threshold to num (default: 4)'
complete -c lav2yuv -s D -d 'Width decimation to use for scene detection (default: 2)'
complete -c lav2yuv -s o -d 'Frame offset - skip num frames at the beginning'
complete -c lav2yuv -s f -d 'Only num frames are written to stdout.  0 means that all frames are processed'
complete -c lav2yuv -s A -d 'Set/override the sample aspect ratio (SAR) emitted in the output stream header'
complete -c lav2yuv -s P -d 'Set the intended/approximate display aspect ratio (DAR) for the stream'
complete -c lav2yuv -s C -d 'Set output chroma (default: \'420jpeg\')'

