# lav2mpeg
# Autogenerated from man page /usr/share/man/man1/lav2mpeg.1.gz
complete -c lav2mpeg -o s/S -d 'Turn stereo off/on                   (default auto)'
complete -c lav2mpeg -o k/K -d 'Turn keeping of raw files off/on      (default off)'
complete -c lav2mpeg -o f/F -d 'Turn use of fifos off/on              (default off)'
complete -c lav2mpeg -o l/L -d 'Turn logging of entire process off/on (default off)'
complete -c lav2mpeg -o n/N -d 'Turn "noisy logging" off/on           (default off)'
complete -c lav2mpeg -o y/Y -d 'Turn use of yuvdenoise off/on         (default off)'
complete -c lav2mpeg -s m -d 'one of MODES (see below)              (default vcd)'
complete -c lav2mpeg -s e -d 'encoding quality : 0, 1, or 2         (default 2)'
complete -c lav2mpeg -s o -d 'output file  ( defaults to firstInputFileName. mpg )'
complete -c lav2mpeg -s b -d 'video bitrate in kbps  ( only used when -o is "mpeg1" or "mpeg2" )'
complete -c lav2mpeg -s a -d 'audio bitrate in kpbs  ( only used when -o is not "vcd*" )'
complete -c lav2mpeg -s q -d 'quality for mpeg2enc   ( only used when -o is "mpeg1" or "mpeg2" )'
complete -c lav2mpeg -s d -d 'dimensions XxY         ( only used when -o is "mpeg1" or "mpeg2" ) defaults t…'

