# lav2wav
# Autogenerated from man page /usr/share/man/man1/lav2wav.1.gz
complete -c lav2wav -s s -d 'Start extracting at video frame (num)'
complete -c lav2wav -s c -d 'Extract (num) frames of audio'
complete -c lav2wav -s v -d 'Verbosity level (0, 1 or 2)'
complete -c lav2wav -s I -d 'Ignore unsupported bitrates/bits per sample'
complete -c lav2wav -s R -d 'If the file does not contain any sound'

