# lavpipe
# Autogenerated from man page /usr/share/man/man1/lavpipe.1.gz
complete -c lavpipe -s o -d 'This is the frame offset of the output video'
complete -c lavpipe -s n -d 'This is the frame count'

