# ldbdel
# Autogenerated from man page /usr/share/man/man1/ldbdel.1.gz
complete -c ldbdel -s h -d 'Show list of available options'
complete -c ldbdel -s H -d 'LDB URL to connect to.  See ldb(3) for details'

