# ldbsearch
# Autogenerated from man page /usr/share/man/man1/ldbsearch.1.gz
complete -c ldbsearch -s h -d 'Show list of available options'
complete -c ldbsearch -s H -d 'LDB URL to connect to.  See ldb(3) for details'
complete -c ldbsearch -s s -d 'Search scope to use.  One-level, subtree or base'
complete -c ldbsearch -s i -d 'Read search expressions from stdin'
complete -c ldbsearch -s b -d 'Specify Base DN to use'

