# lecs
# Autogenerated from man page /usr/share/man/man8/lecs.8.gz
complete -c lecs -s d -d 'Reads the configuration file, dumps its contents and exits'
complete -c lecs -o llisten_address -d 'Use the listen_address to where wait connections'
complete -c lecs -s l -d 'Use the listen_address to where wait connections'
complete -c lecs -s f -d 'Use the specified configuration file instead of . lecs_conf.  FILES '

