# les
# Autogenerated from man page /usr/share/man/man8/les.8.gz
complete -c les -o dmodule -d 'Set debugging messages on for a module'
complete -c les -o mmodule -d 'Set memory debugging messages on for a module'
complete -c les -s d -d 'Set debugging messages on for a module'
complete -c les -s m -d 'Set memory debugging messages on for a module'
complete -c les -s f -d 'Use the specified configuration file instead of . lanevars.  FILES '

