# lou_trace
# Autogenerated from man page /usr/share/man/man1/lou_trace.1.gz
complete -c lou_trace -s h -l help -d 'display this help and exit'
complete -c lou_trace -s v -l version -d 'display version information and exit'
complete -c lou_trace -s f -l forward -d 'forward translation using the given table'
complete -c lou_trace -s b -l backward -d 'backward translation using the given table'
complete -c lou_trace -l noContractions -d 'Use no contractions'
complete -c lou_trace -l dotsIO -d 'Display dot patterns'
complete -c lou_trace -l ucBrl -d 'Use Unicode Braille patterns'
complete -c lou_trace -l noUndefined -d 'Disable output of undefined dot numbers during back-translation'
complete -c lou_trace -l partialTrans -d 'Use partial back-translation If neither -f nor -b are specified forward trans…'

