# lou_checktable
# Autogenerated from man page /usr/share/man/man1/lou_checktable.1.gz
complete -c lou_checktable -s h -l help -d 'display this help and exit'
complete -c lou_checktable -s v -l version -d 'display version information and exit'
complete -c lou_checktable -s q -l quiet -d 'do not write to standard error if there are no errors'

