# lrzip
# Autogenerated from man page /usr/share/man/man1/lrzip.1.gz
complete -c lrzip -s c -d 'This option enables integrity checking of the file written to disk on decompr…'
complete -c lrzip -s d -d Decompress
complete -c lrzip -s e
complete -c lrzip -l encrypt -d Encrypt
complete -c lrzip -s h -s '?' -d 'Print an options summary page'
complete -c lrzip -s H -d 'This shows the md5 hash value calculated on compressing or decompressing an l…'
complete -c lrzip -s i -d 'This shows information about a compressed file'
complete -c lrzip -s q -d 'If this option is specified then lrzip will not show the percentage progress …'
complete -c lrzip -s r -d 'If this option is specified, lrzip will recursively enter the directories spe…'
complete -c lrzip -s t -d 'This tests the compressed file integrity'
complete -c lrzip -s v -d 'Increases verbosity.  -vv will print more messages than -v'
complete -c lrzip -s V -d 'Print the lrzip version number'
complete -c lrzip -s D -d 'If this option is specified then lrzip will delete the source file after succ…'
complete -c lrzip -s f -d 'If this option is not specified (Default) then lrzip will not overwrite any e…'
complete -c lrzip -s k -d 'This option will keep broken or damaged files instead of deleting them'
complete -c lrzip -s o -d 'Set the output file name'
complete -c lrzip -s O -d 'Set the output directory for the default filename'
complete -c lrzip -s S -d 'Set the compression suffix.  The default is \'. lrz\''
complete -c lrzip -s b -d 'Bzip2 compression'
complete -c lrzip -s g -d 'Gzip compression.  Uses gzip compression for the 2nd stage'
complete -c lrzip -s l -d 'LZO Compression'
complete -c lrzip -s n -d 'No 2nd stage compression'
complete -c lrzip -s z -d 'ZPAQ compression'
complete -c lrzip -s L -d 'Set the compression level from 1 to 9'
complete -c lrzip -s N -d 'The default nice value is 19'
complete -c lrzip -s p -d 'Set the number of processor count to determine the number of threads to run'
complete -c lrzip -s T -d 'Disables the LZ4 compressibility threshold testing when a slower compression …'
complete -c lrzip -s U -d 'Unlimited window size'
complete -c lrzip -s w -d 'Set the maximum allowable compression window size to n in hundreds of megabyt…'

