# lscp
# Autogenerated from man page /usr/share/man/man1/lscp.1.gz
complete -c lscp -s a -l all -d 'Do not hide minor checkpoints'
complete -c lscp -s b -l show-block-count -d 'Show number of used blocks instead of appended blocks'
complete -c lscp -s g -l show-increment -d 'Show number of appended blocks instead of used blocks'
complete -c lscp -s r -l reverse -d 'Reverse order'
complete -c lscp -s s -l snapshot -d 'List only snapshots'
complete -c lscp -s i -l index -d 'Skip index checkpoints (or snapshots) at start of input'
complete -c lscp -s n -l lines -d 'List only lines input checkpoints (or snapshots)'
complete -c lscp -s h -l help -d 'Display help message and exit'
complete -c lscp -s V -l version -d 'Display version and exit'

