# mcview
# Autogenerated from man page /usr/share/man/man1/mcview.1.gz
complete -c mcview -s b -d 'Force black and white display'
complete -c mcview -s c -d 'Force color mode on terminals where  mcview defaults to black and white'
complete -c mcview -s C -d 'Specify a different color set'
complete -c mcview -s d -d 'Disable mouse support'
complete -c mcview -s f -d 'Display the compiled-in search paths for Midnight Commander files'
complete -c mcview -s t -d 'Used only if the code was compiled with S-Lang and terminfo: it makes Midnigh…'
complete -c mcview -s V -d 'Displays the version of the program'
complete -c mcview -s x -d 'Forces xterm mode'

