# mdb_dump
# Autogenerated from man page /usr/share/man/man1/mdb_dump.1.gz
complete -c mdb_dump -s V -d 'Write the library version number to the standard output, and exit'
complete -c mdb_dump -s f -d 'Write to the specified file instead of to the standard output'
complete -c mdb_dump -s l -d 'List the databases stored in the environment'
complete -c mdb_dump -s n -d 'Dump an LMDB database which does not use subdirectories'
complete -c mdb_dump -s p -d 'If characters in either the key or data items are printing characters (as def…'
complete -c mdb_dump -s a -d 'Dump all of the subdatabases in the environment'
complete -c mdb_dump -s s -d 'Dump a specific subdatabase'

