# mdb_load
# Autogenerated from man page /usr/share/man/man1/mdb_load.1.gz
complete -c mdb_load -s V -d 'Write the library version number to the standard output, and exit'
complete -c mdb_load -s a -d 'Append all records in the order they appear in the input'
complete -c mdb_load -s f -d 'Read from the specified file instead of from the standard input'
complete -c mdb_load -s n -d 'Load an LMDB database which does not use subdirectories'
complete -c mdb_load -s s -d 'Load a specific subdatabase'
complete -c mdb_load -s N -d 'Don\'t overwrite existing records when loading into an already existing databa…'
complete -c mdb_load -s T -d 'option below.  OPTIONS'

