# mdb_copy
# Autogenerated from man page /usr/share/man/man1/mdb_copy.1.gz
complete -c mdb_copy -s V -d 'Write the library version number to the standard output, and exit'
complete -c mdb_copy -s c -d 'Compact while copying'
complete -c mdb_copy -s n -d 'Open LDMB environment(s) which do not use subdirectories'

