# mountstats
# Autogenerated from man page /usr/share/man/man8/mountstats.8.gz
complete -c mountstats -s h -l help -d 'show the help message and exit'
complete -c mountstats -s v -l version -d 'show program\'s version number and exit'
complete -c mountstats -s f -l file -d 'Read stats from  infile instead of  R /proc/self/mountstats "'
complete -c mountstats -s S -l since -d 'Show difference between current stats and those in R sincefile "'
complete -c mountstats -s r -l rpc -d 'Display only the RPC statistics'
complete -c mountstats -s R -l raw -d 'Display only the raw statistics'
complete -c mountstats -s x -l xprt -d 'Display only the transport statistics '
complete -c mountstats -s 3 -d 'Show only NFS version 3 statistics'
complete -c mountstats -s n -l nfs -d 'Display only the NFS statistics'
complete -c mountstats -s 4 -d 'Show only NFS version 4 statistics'

