# mpcd
# Autogenerated from man page /usr/share/man/man8/mpcd.8.gz
complete -c mpcd -s s -d 'Local ATM address this MPC uses for MPOA control connections'
complete -c mpcd -s l -d 'Local ATM address from and to which MPOA shortcuts are established'
complete -c mpcd -s c -d 'ATM address of MPS.  Only needed if MPS can not advertise it by itself'
complete -c mpcd -s i -d 'The interface number of LEC this MPC serves.  E. g.  2 for "lec2"'
complete -c mpcd -s m -d 'MAC address of default router where MPS recides'
complete -c mpcd -s L -d 'Listen address of the . SM LANE client zeppelin'
complete -c mpcd -s n -d 'Name of the . SM ELAN for which mpcd asks for parameters when it connects to '
complete -c mpcd -s C -d 'ATM address of'

