# nbd-server
# Autogenerated from man page /usr/share/man/man1/nbd-server.1.gz
complete -c nbd-server -s r -d 'Export the file read-only'
complete -c nbd-server -s m -d 'Work with multiple files'
complete -c nbd-server -s c -d 'Copy on write'
complete -c nbd-server -s C -d 'Specify configuration file'
complete -c nbd-server -s M -d 'Specify the maximum number of opened connections'
complete -c nbd-server -s V -d 'Output the version of nbd-server, and exit'
complete -c nbd-server -s d -d 'Do not fork.  Useful for debugging'

