# nfs-ls
# Autogenerated from man page /usr/share/man/man1/nfs-ls.1.gz
complete -c nfs-ls -s s -l summary -d 'Print a summary line at the end of output'
complete -c nfs-ls -s R -l recursive -d 'Recursive listing of the specified URL'
complete -c nfs-ls -s D -l 'discovery;' -d 'This option is used to discover local NFS servers and to list the exports for…'
complete -c nfs-ls -s '?' -l help -d 'Display basic help text'
complete -c nfs-ls -l usage -d 'Display basic usage text'
complete -c nfs-ls -o rwxrwxr-x
complete -c nfs-ls -o rwxr-xr-x
complete -c nfs-ls -o rwxrwxrwx -d '       OPTIONS'

