# nfsd
# Autogenerated from man page /usr/share/man/man8/nfsd.8.gz
complete -c nfsd -s d -l debug -d 'enable logging of debugging messages'
complete -c nfsd -s H -l host -d 'specify a particular hostname (or address) that NFS requests will be accepted…'
complete -c nfsd -s p -l port -d 'specify a different port to listen on for NFS requests.  By default,  rpc'
complete -c nfsd -s r -l rdma -d 'specify that NFS requests on the standard RDMA port ("nfsrdma", port 20049) s…'
complete -c nfsd -s N -l no-nfs-version -d 'This option can be used to request that   rpc'
complete -c nfsd -s s -l syslog -d 'By default,  rpc'
complete -c nfsd -s t -l tcp -d 'Instruct the kernel nfs server to open and listen on a TCP socket'
complete -c nfsd -s T -l no-tcp -d 'Instruct the kernel nfs server not to open and listen on a TCP socket'
complete -c nfsd -s u -l udp -d 'Instruct the kernel nfs server to open and listen on a UDP socket'
complete -c nfsd -s U -l no-udp -d 'Instruct the kernel nfs server not to open and listen on a UDP socket'
complete -c nfsd -s V -l nfs-version -d 'This option can be used to request that   rpc'
complete -c nfsd -s L -l lease-time -d 'Set the lease-time used for NFSv4'
complete -c nfsd -s G -l grace-time -d 'Set the grace-time used for NFSv4 and NLM (for NFSv2 and NFSv3)'

