# nfsdcld
# Autogenerated from man page /usr/share/man/man8/nfsdcld.8.gz
complete -c nfsdcld -s d -l debug -d 'Enable debug level logging'
complete -c nfsdcld -s F -l foreground -d 'Runs the daemon in the foreground and prints all output to stderr'
complete -c nfsdcld -s p -l pipefsdir -d 'Location of the rpc_pipefs filesystem'

