# nfsiostat
# Autogenerated from man page /usr/share/man/man8/nfsiostat.8.gz
complete -c nfsiostat -s a -l attr -d 'displays statistics related to the attribute cache'
complete -c nfsiostat -s d -l dir -d 'displays statistics related to directory operations'
complete -c nfsiostat -s h -l help -d 'shows help message and exit'
complete -c nfsiostat -s l -l list -d 'only print stats for first LIST mount points'
complete -c nfsiostat -s p -l page -d 'displays statistics related to the page cache'
complete -c nfsiostat -s s -l sort -d 'Sort NFS mount points by ops/second'
complete -c nfsiostat -l version -d 'show program\'s version number and exit FILES'

