# nfsstat
# Autogenerated from man page /usr/share/man/man8/nfsstat.8.gz
complete -c nfsstat -s s -l server -d 'Print only server-side statistics'
complete -c nfsstat -s c -l client -d 'Print only client-side statistics'
complete -c nfsstat -s n -l nfs -d 'Print only NFS statistics'
complete -c nfsstat -s 2 -d 'Print only NFS v2 statistics'
complete -c nfsstat -s 3 -d 'Print only NFS v3 statistics'
complete -c nfsstat -s 4 -d 'Print only NFS v4 statistics'
complete -c nfsstat -s m -l mounts -d 'Print information about each of the mounted NFS file systems'
complete -c nfsstat -s r -l rpc -d 'Print only RPC statistics'
complete -c nfsstat -s o -d 'Display statistics for the specified facility, which must be one of: . RS'
complete -c nfsstat -s v -l verbose -d 'This is equivalent to -o all'
complete -c nfsstat -s l -l list -d 'Print information in list form'
complete -c nfsstat -s S -l since -d 'Instead of printing current statistics,   nfsstat imports statistics from  fi…'
complete -c nfsstat -s Z -l sleep -d 'Instead of printing current statistics and immediately exiting, nfsstat takes…'

