# nfsv4
# Autogenerated from man page /usr/share/man/man8/nfsv4.exportd.8.gz
complete -c nfsv4 -s d -l debug -d 'Turn on debugging.  Valid kinds are: all, auth, call, general and parse'
complete -c nfsv4 -s l -l log-auth -d 'Enable logging of responses to authentication and access requests from nfsd'
complete -c nfsv4 -s i -l cache-use-ipaddr -d 'Normally each client IP address is matched against each host identifier (name…'
complete -c nfsv4 -s T -l ttl -d 'Provide a time-to-live (TTL) for cached information given to the kernel'
complete -c nfsv4 -s F -l foreground -d 'Run in foreground (do not daemonize)'
complete -c nfsv4 -s h -l help -d 'Display usage message'
complete -c nfsv4 -s t -l num-threads -l num-threads -d 'This option specifies the number of worker threads that   nfsv4'
complete -c nfsv4 -s g -l manage-gids -d 'Accept requests from the kernel to map user id numbers into lists of group id…'

