# nilfs-tune
# Autogenerated from man page /usr/share/man/man8/nilfs-tune.8.gz
complete -c nilfs-tune -s f -d 'Force to modify even the specified file system is mounted'
complete -c nilfs-tune -s i -d 'Set the commit interval of segment'
complete -c nilfs-tune -s m -d 'Set the threshold of the data amount of the segment construction'
complete -c nilfs-tune -s l -d 'List the contents of the file system superblock, including the current values…'
complete -c nilfs-tune -s L -d 'Set the volume label of the file system'
complete -c nilfs-tune -s O -d 'Set or clear the indicated filesystem features (options) in the filesystem'
complete -c nilfs-tune -s U -d 'Set the universally unique identifier (UUID) of the file system to UUID'
complete -c nilfs-tune -s h -d 'Display help message and exit.  AUTHOR Jiro SEKIBA <jir@unicus'

