# ntpd
# Autogenerated from man page /usr/share/man/man1/ntpd.1.gz
complete -c ntpd -s q -d and
complete -c ntpd -s x -d 'options.  See the tinker configuration file directive for other options'
complete -c ntpd -s u -d option
complete -c ntpd -l enable-clockctl
complete -c ntpd -l enable-linuxcaps -l enable-solarisprivs -d 'Listen on an interface name or address'
complete -c ntpd -s g -d and

