# nvme-primary-ctrl-caps
# Autogenerated from man page /usr/share/man/man1/nvme-primary-ctrl-caps.1.gz
complete -c nvme-primary-ctrl-caps -s o -l output-format -d 'Set the reporting format to normal, json, or binary'
complete -c nvme-primary-ctrl-caps -s H -l human-readable -d 'This option will parse and format many of the bit fields into human-readable …'

