# nvme-zns-id-ns
# Autogenerated from man page /usr/share/man/man1/nvme-zns-id-ns.1.gz
complete -c nvme-zns-id-ns -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-zns-id-ns -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-zns-id-ns -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

