# nvme-zns-report-zones
# Autogenerated from man page /usr/share/man/man1/nvme-zns-report-zones.1.gz
complete -c nvme-zns-report-zones -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-zns-report-zones -s s -l start-lba -d 'The starting LBA of the zone to begin the report'
complete -c nvme-zns-report-zones -s d -l descs -d 'The number of descriptors to request in the report'
complete -c nvme-zns-report-zones -s S -l state -d 'The state of zones to request in the report.  Known values include: '
complete -c nvme-zns-report-zones -s e -l extended -d 'Request to use the Extended Report Zones option'
complete -c nvme-zns-report-zones -s p -l partial -d 'If set, the device will return the number of zones that match the state rathe…'
complete -c nvme-zns-report-zones -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-zns-report-zones -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

