# nvme-self-test-log
# Autogenerated from man page /usr/share/man/man1/nvme-self-test-log.1.gz
complete -c nvme-self-test-log -s e -l log-entries
complete -c nvme-self-test-log -s o -l output-format

