# nvme-id-nvmset
# Autogenerated from man page /usr/share/man/man1/nvme-id-nvmset.1.gz
complete -c nvme-id-nvmset -s i -l nvmset_id -d 'This field specifies the identifier of the NVM Set'
complete -c nvme-id-nvmset -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

