# nvme-copy
# Autogenerated from man page /usr/share/man/man1/nvme-copy.1.gz
complete -c nvme-copy -l sdlba -s d -d '64-bit addr of first destination logical block'
complete -c nvme-copy -l blocks -s b -d 'Comma separated list of the number of blocks in each range'
complete -c nvme-copy -l slbs -s s -d 'Comma separated list of the starting blocks in each range'
complete -c nvme-copy -l limited-retry -s l -d 'Sets the limited retry flag'
complete -c nvme-copy -l force-unit-access -s f -d 'Set the force-unit access flag'
complete -c nvme-copy -l prinfow -s p -d 'Protection Information field write definition'
complete -c nvme-copy -l prinfor -s P -d 'Protection Information field read definition'
complete -c nvme-copy -l ref-tag -s r -d 'initial lba reference tag'
complete -c nvme-copy -l expected-ref-tags -s R -d 'expected lba reference tags (comma-separated list)'
complete -c nvme-copy -l app-tag -s a -d 'lba app tag'
complete -c nvme-copy -l expected-app-tags -s A -d 'expected lba app tags (comma-separated list)'
complete -c nvme-copy -l app-mask -s m -d 'lba tag mask'
complete -c nvme-copy -l expected-app-masks -s M -d 'expected lba tag masks (comma-separated list)'
complete -c nvme-copy -l dir-type -s T -d 'Optional directive type'
complete -c nvme-copy -l dir-spec -s S -d 'Optional field for directive specifics'
complete -c nvme-copy -l format -s F -d 'source range entry format'

