# nvme-lnvm-create
# Autogenerated from man page /usr/share/man/man1/nvme-lnvm-create.1.gz
complete -c nvme-lnvm-create -l device-name -s d -d 'Device name to initialize'
complete -c nvme-lnvm-create -l target-name -s n -d 'Target name of the device to initialize.  For example: target0'
complete -c nvme-lnvm-create -l target-type -s t -d 'Target type of the device to use.  For example: pblk'
complete -c nvme-lnvm-create -l lun-begin -s b -d 'Begin LUN id offset to use for target'
complete -c nvme-lnvm-create -l lun-end -s e -d 'End LUN id offset to use for target'

