# nvme-capacity-mgmt
# Autogenerated from man page /usr/share/man/man1/nvme-capacity-mgmt.1.gz
complete -c nvme-capacity-mgmt -s o -l operation -d 'Operation to be performed by the controller'
complete -c nvme-capacity-mgmt -s i -l element-id -d 'Value specific to the value of the Operation field'
complete -c nvme-capacity-mgmt -s l -l cap-lower -d 'Least significant 32 bits of the capacity in bytes of the Endurance Group or …'
complete -c nvme-capacity-mgmt -s u -l cap-upper -d 'Most significant 32 bits of the capacity in bytes of the Endurance Group or N…'

