# nvme-lnvm-init
# Autogenerated from man page /usr/share/man/man1/nvme-lnvm-init.1.gz
complete -c nvme-lnvm-init -l device-name -s d -d 'Device name to initialize'
complete -c nvme-lnvm-init -l mediamgr-name -s m -d 'Media Manager name to use for initialization'

