# nvme-wdc-namespace-resize
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-namespace-resize.1.gz
complete -c nvme-wdc-namespace-resize -s n -l namespace-id -d 'Namespace ID; ID of the namespace to resize'
complete -c nvme-wdc-namespace-resize -s o -l op-option -d 'Overprovisioning Option; defaults to 0xF . sp . if n \\{\\'

