# nvme-id-iocs
# Autogenerated from man page /usr/share/man/man1/nvme-id-iocs.1.gz
complete -c nvme-id-iocs -s c -l controller-id -d 'Retrieve the identify I/O Command set data structure for the given cntid'
complete -c nvme-id-iocs -s H -l human-readable -d 'This option will parse and format many of the bit fields into human-readable …'
complete -c nvme-id-iocs -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

