# nvme-lnvm-remove
# Autogenerated from man page /usr/share/man/man1/nvme-lnvm-remove.1.gz
complete -c nvme-lnvm-remove -l target-name -s n -d 'Target name of the device to initialize.  For example: target0'

