# nvme-verify
# Autogenerated from man page /usr/share/man/man1/nvme-verify.1.gz
complete -c nvme-verify -l namespace-id -s n -d 'Namespace ID use in the command'
complete -c nvme-verify -l start-block -s s -d 'Start block address'
complete -c nvme-verify -l block-count -s c -d 'Number of logical blocks to Verify'
complete -c nvme-verify -l limited-retry -s l -d 'Sets the limited retry flag'
complete -c nvme-verify -l force-unit-access -s f -d 'Set the force-unit access flag'
complete -c nvme-verify -l prinfo -s p -d 'Protection Information field definition'
complete -c nvme-verify -l ref-tag -s r -d 'Optional reftag when used with protection information'
complete -c nvme-verify -l app-tag-mask -s m -d 'Optional application tag mask when used with protection information'
complete -c nvme-verify -l app-tag -s a -d 'Optional application tag when used with protection information'
complete -c nvme-verify -l storage-tag -s S -d 'Variable Sized Expected Logical Block Storage Tag(ELBST) and Expected Logical…'
complete -c nvme-verify -l storage-tag-check -s C -d 'This bit specifies the Storage Tag field shall be checked as part of Verify o…'

