# nvme-zns-set-zone-desc
# Autogenerated from man page /usr/share/man/man1/nvme-zns-set-zone-desc.1.gz
complete -c nvme-zns-set-zone-desc -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-zns-set-zone-desc -s s -l start-lba -d 'The starting LBA of the zone to manage send'
complete -c nvme-zns-set-zone-desc -s d -o data -d 'Optional file for data (default stdin)'
complete -c nvme-zns-set-zone-desc -s t -l timeout -d 'Override default timeout value.  In milliseconds'

