# nvme-nvm-id-ctrl
# Autogenerated from man page /usr/share/man/man1/nvme-nvm-id-ctrl.1.gz
complete -c nvme-nvm-id-ctrl -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

