# nvme-predictable-lat-log
# Autogenerated from man page /usr/share/man/man1/nvme-predictable-lat-log.1.gz
complete -c nvme-predictable-lat-log -s i -l nvmset-id -d 'Retrieve the Predectible latency per NVM set log for the given nvmset id'
complete -c nvme-predictable-lat-log -s b -l raw-binary -d 'Print the raw Predectible latency per NVM set log buffer to stdout'
complete -c nvme-predictable-lat-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

