# nvme-smart-log
# Autogenerated from man page /usr/share/man/man1/nvme-smart-log.1.gz
complete -c nvme-smart-log -s n -l namespace-id -d 'Retrieve the SMART log for the given nsid'
complete -c nvme-smart-log -s b -l raw-binary -d 'Print the raw SMART log buffer to stdout'
complete -c nvme-smart-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

