# nvme-create-ns
# Autogenerated from man page /usr/share/man/man1/nvme-create-ns.1.gz
complete -c nvme-create-ns -s s -l nsze
complete -c nvme-create-ns -s c -l ncap
complete -c nvme-create-ns -s f -l flbas
complete -c nvme-create-ns -s d -l dps
complete -c nvme-create-ns -s m -l nmic
complete -c nvme-create-ns -s a -l anagrp-id
complete -c nvme-create-ns -s i -l nvmset-id
complete -c nvme-create-ns -s y -l csi
complete -c nvme-create-ns -s b -l block-size

