# nvme-micron-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-micron-internal-log.1.gz
complete -c nvme-micron-internal-log -s l -l package -d 'name of the file (with . zip extension) to save the device logs'

