# nvme-toshiba-vs-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-toshiba-vs-internal-log.1.gz
complete -c nvme-toshiba-vs-internal-log -s o -l output-file -d 'Output binary file.  Defaults to text-formatted dump to stdout'
complete -c nvme-toshiba-vs-internal-log -s p -l prev-log -d 'Use previous log contents.  Defaults to the current log contents'

