# nvme-list-ns
# Autogenerated from man page /usr/share/man/man1/nvme-list-ns.1.gz
complete -c nvme-list-ns -s n -l namespace-id -d 'Retrieve the identify list structure starting with the given nsid'
complete -c nvme-list-ns -s y -l csi -d 'If this value is given, retrieve the identify list structure associated with …'
complete -c nvme-list-ns -s a -l all -d 'Retrieve the identify list structure for all namespaces in the subsystem, whe…'
complete -c nvme-list-ns -s o -l output-format -d 'Set the reporting format to normal, or json'

