# nvme-lnvm-id-ns
# Autogenerated from man page /usr/share/man/man1/nvme-lnvm-id-ns.1.gz
complete -c nvme-lnvm-id-ns -l namespace-id -s n -d 'Retrieve the geometry from the selected namespace'
complete -c nvme-lnvm-id-ns -l force -s f -d 'Try to read the data and assume it is a LightNVM device'
complete -c nvme-lnvm-id-ns -l raw-binary -s b -d 'Output the raw output'
complete -c nvme-lnvm-id-ns -l human-readable -s H -d 'Output the status in human readable format'

