# nvme-security-recv
# Autogenerated from man page /usr/share/man/man1/nvme-security-recv.1.gz
complete -c nvme-security-recv -s n -l namespace-id -d 'Target a specific namespace for this security command'
complete -c nvme-security-recv -s N -l nssf -d 'NVMe Security Specific field'
complete -c nvme-security-recv -s x -l size -d 'Size of buffer to allocate.  One success it will be printed to STDOUT'
complete -c nvme-security-recv -s p -l secp -d 'Security Protocol: This field specifies the security protocol as defined in S…'
complete -c nvme-security-recv -s s -l spsp -d 'SP Specific: The value of this field is specific to the Security Protocol as …'
complete -c nvme-security-recv -s t -l al -d 'Allocation Length: The value of this field is specific to the Security Protoc…'
complete -c nvme-security-recv -s b -l raw-binary -d 'Print the raw buffer to stdout.  Defaults to print in hex'

