# nvme-virtium-save-smart-to-vtview-log
# Autogenerated from man page /usr/share/man/man1/nvme-virtium-save-smart-to-vtview-log.1.gz
complete -c nvme-virtium-save-smart-to-vtview-log -s r -l run-tim -d '(optional) Number of hours to log data (default = 20 hours)'
complete -c nvme-virtium-save-smart-to-vtview-log -s f -l freq -d '(optional) How often you want to log SMART data (0. 25 = 15\\*(Aq , 0'
complete -c nvme-virtium-save-smart-to-vtview-log -s o -l output-file -d '(optional) Name of the log file (give it a name that easy for you to remember…'
complete -c nvme-virtium-save-smart-to-vtview-log -s n -l test-name -d '(optional) Name of the test you are doing'

