# nvme-resv-notif-log
# Autogenerated from man page /usr/share/man/man1/nvme-resv-notif-log.1.gz
complete -c nvme-resv-notif-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

