# nvme-wdc-enc-get-log
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-enc-get-log.1.gz
complete -c nvme-wdc-enc-get-log -s o -l output-file -d 'Output file pathname'
complete -c nvme-wdc-enc-get-log -s s -l transfer-size -d 'Data retrieval transfer size, maximum transfer size should be 0x2000 (decimal…'

