# nvme-zns-close-zone
# Autogenerated from man page /usr/share/man/man1/nvme-zns-close-zone.1.gz
complete -c nvme-zns-close-zone -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-zns-close-zone -s s -l start-lba -d 'The starting LBA of the zone to close'
complete -c nvme-zns-close-zone -s a -l select-all -d 'Select all zones for this action'
complete -c nvme-zns-close-zone -s t -l timeout -d 'Override default timeout value.  In milliseconds'

