# pacstrap
# Autogenerated from man page /usr/share/man/man8/pacstrap.8.gz
complete -c pacstrap -s C -d 'Use an alternate config file for pacman'
complete -c pacstrap -s c -d 'Use the package cache on the host, rather than the target'
complete -c pacstrap -s G -d 'Avoid copying the host\'s pacman keyring to the target'
complete -c pacstrap -s i -d 'Prompt for package confirmation when needed (run interactively)'
complete -c pacstrap -s M -d 'Avoid copying the host\'s mirrorlist to the target'
complete -c pacstrap -s U -d 'Use pacman -U to install packages'
complete -c pacstrap -s h -d 'Output syntax and command line options'

