# pktsetup
# Autogenerated from man page /usr/share/man/man8/pktsetup.8.gz
complete -c pktsetup -s d -d 'Delete the association between the specified packet-device and its block devi…'
complete -c pktsetup -s s -d 'Show the current device mapping, one device per line, in the format  name : p…'

