# png2yuv
# Autogenerated from man page /usr/share/man/man1/png2yuv.1.gz
complete -c png2yuv -s b -d 'Frame offset:  skip output of the first \'num\' frames.   (default: 0)'
complete -c png2yuv -s f -d 'Set the frame rate of stream accepts the same numbers'
complete -c png2yuv -s I -d 'interlacing mode: p = none / progressive . br t = top field first '
complete -c png2yuv -s L -d '0 = non-interleaved (two successive fields per PNG file) '
complete -c png2yuv -s S -d 'chroma subsampling mode, only for professionals, for more info see ppmtoy4m a…'
complete -c png2yuv -s n -d 'Specifies the nummber of frames to process.  (default: all = -1)'
complete -c png2yuv -s j -d 'Read PNG frames with the name components as follows:  {1} PNG filename prefix…'

