# ppmtoy4m
# Autogenerated from man page /usr/share/man/man1/ppmtoy4m.1.gz
complete -c ppmtoy4m -s o -d 'Frame offset:  skip output of the first \'num\' frames.   (default: 0)'
complete -c ppmtoy4m -s n -d 'Output a total of \'num\' output frames.   Use \'0\' to specify all frames'
complete -c ppmtoy4m -s F -d 'Set framerate encoded in output stream, as an exact integer ratio'
complete -c ppmtoy4m -s A -d 'Set pixel aspect ratio encoded in output stream, as an exact integer ratio'
complete -c ppmtoy4m -s B -d 'Interpret data as being BGR rather than RGB'
complete -c ppmtoy4m -s I -d 'Set interlacing mode, used to interpret the PPM image(s), and also encoded in…'
complete -c ppmtoy4m -s L -d 'For interlaced streams, treat each PPM image as two interleaved fields'
complete -c ppmtoy4m -s r -d 'Repeat last input frame until output is complete'
complete -c ppmtoy4m -s S -d 'Set chroma subsampling mode'

