# pppoe-sniff
# Autogenerated from man page /usr/share/man/man8/pppoe-sniff.8.gz
complete -c pppoe-sniff -s I -d 'The -I option specifies the Ethernet interface to use'
complete -c pppoe-sniff -s V -d 'The -V option causes pppoe-sniff to print its version number and exit'

