# pppoe-relay
# Autogenerated from man page /usr/share/man/man8/pppoe-relay.8.gz
complete -c pppoe-relay -s S -d 'Adds the Ethernet interface interface to the list of interfaces managed by pp…'
complete -c pppoe-relay -s C -d 'Adds the Ethernet interface interface to the list of interfaces managed by pp…'
complete -c pppoe-relay -s B -d 'Adds the Ethernet interface interface to the list of interfaces managed by pp…'
complete -c pppoe-relay -s n -d 'Allows at most num concurrent PPPoE sessions'
complete -c pppoe-relay -s i -d 'Specifies the session idle timeout'
complete -c pppoe-relay -s F -d 'The -F option causes pppoe-relay not to fork into the background; instead, it…'
complete -c pppoe-relay -s h -d 'The -h option prints a brief usage message and exits'

