# pw-mon
# Autogenerated from man page /usr/share/man/man1/pw-mon.1.gz
complete -c pw-mon -s r -l remote -d 'The name the remote instance to monitor'
complete -c pw-mon -s h -l help -d 'Show help'
complete -c pw-mon -l version -d 'Show version information.  AUTHORS The PipeWire Developers <https://gitlab'

