# rdisc6
# Autogenerated from man page /usr/share/man/man8/rdisc6.8.gz
complete -c rdisc6 -s 1 -l single -d 'Exit as soon as the first advertisement is received'
complete -c rdisc6 -s h -l help -d 'Display some help and exit'
complete -c rdisc6 -s m -l multiple -d 'Wait for possible multiple advertisements and print all of them (default)'
complete -c rdisc6 -s n -l numeric -d 'If the optional parameter is not a valid IPv6 address, do not try to resolve …'
complete -c rdisc6 -s q -l quiet -d 'Only display advertised IPv6 prefixes.  Display nothing in case of failure'
complete -c rdisc6 -s r -l retry -d 'Send ICMPv6 Router Discovery that many times until a reply is received, or ab…'
complete -c rdisc6 -s s -l source -d 'Specify the IPv6 address to be used as the source for the router solicitation…'
complete -c rdisc6 -s V -l version -d 'Display program version and license and exit'
complete -c rdisc6 -s v -l verbose -d 'Display verbose information.  That is the default'
complete -c rdisc6 -s w -l wait -d 'Wait  wait_ms  milliseconds for a response before retrying'

