# resize
# Autogenerated from man page /usr/share/man/man8/resize.f2fs.8.gz
complete -c resize -s t -d 'Specify the size in sectors'
complete -c resize -s d -d 'Specify the level of debugging options'

