# rg
# Autogenerated from man page /usr/share/man/man1/rg.1.gz
complete -c rg -l no-column -d exist
complete -c rg -s A -l after-context
complete -c rg -l auto-hybrid-regex
complete -c rg -s B -l before-context
complete -c rg -l binary
complete -c rg -o a/--text
complete -c rg -l block-buffered
complete -c rg -s b -l byte-offset
complete -c rg -s s -l case-sensitive
complete -c rg -l color
complete -c rg -l colors
complete -c rg -l column
complete -c rg -s C -l context
complete -c rg -l context-separator
complete -c rg -l no-context-separator
complete -c rg -s c -l count
complete -c rg -l count-matches
complete -c rg -l only-matching
complete -c rg -l crlf
complete -c rg -l debug
complete -c rg -l dfa-size-limit
complete -c rg -l max-filesize
complete -c rg -s E -l encoding
complete -c rg -l engine
complete -c rg -o e/--regexp -o f/--file
complete -c rg -l field-context-separator
complete -c rg -l field-match-separator
complete -c rg -s f -l file
complete -c rg -l files
complete -c rg -s l -l files-with-matches
complete -c rg -l files-without-match
complete -c rg -s F -l fixed-strings
complete -c rg -s L -l follow
complete -c rg -s g -l glob
complete -c rg -l glob-case-insensitive
complete -c rg -l heading
complete -c rg -l hidden
complete -c rg -l iglob
complete -c rg -s i -l ignore-case
complete -c rg -l ignore-file
complete -c rg -l ignore-file-case-insensitive
complete -c rg -l include-zero
complete -c rg -s v -l invert-match
complete -c rg -l json
complete -c rg -l replace -l max-columns -d 'when --json is set'
complete -c rg -l line-buffered
complete -c rg -s n -l line-number
complete -c rg -s x -l line-regexp
complete -c rg -s M
complete -c rg -l max-columns-preview
complete -c rg -s m -l max-count
complete -c rg -l max-depth
complete -c rg -l mmap
complete -c rg -s U -l multiline
complete -c rg -l multiline-dotall
complete -c rg -l no-config
complete -c rg -s I -l no-filename
complete -c rg -l no-heading
complete -c rg -l no-ignore
complete -c rg -l no-ignore-dot -l no-ignore-exclude -l no-ignore-global
complete -c rg -l no-ignore-vcs
complete -c rg -l no-ignore-files
complete -c rg -l no-ignore-messages
complete -c rg -l no-ignore-parent
complete -c rg -s N -l no-line-number
complete -c rg -l no-messages
complete -c rg -l no-mmap
complete -c rg -l no-pcre2-unicode
complete -c rg -l no-require-git
complete -c rg -l no-unicode
complete -c rg -l pcre2-unicode
complete -c rg -l unicode
complete -c rg -s 0 -l null
complete -c rg -l null-data
complete -c rg -l one-file-system
complete -c rg -s o
complete -c rg -l passthru
complete -c rg -l path-separator
complete -c rg -s P -l pcre2
complete -c rg -o U/--multiline -d 'instead of reporting an error immediately (like it does with the default rege…'
complete -c rg -l pcre2-version
complete -c rg -l pre
complete -c rg -l pre-glob
complete -c rg -s p -l pretty
complete -c rg -s q -l quiet
complete -c rg -l regex-size-limit
complete -c rg -s e -l regexp
complete -c rg -s r
complete -c rg -s z -l search-zip
complete -c rg -s S -l smart-case
complete -c rg -l sort
complete -c rg -l sortr
complete -c rg -l stats
complete -c rg -s a -l text
complete -c rg -s j -l threads
complete -c rg -l trim
complete -c rg -s t -l type
complete -c rg -l type-list
complete -c rg -l type-add
complete -c rg -l type-clear
complete -c rg -s T -l type-not
complete -c rg -s u -l unrestricted
complete -c rg -l vimgrep
complete -c rg -s H -l with-filename
complete -c rg -s w -l word-regexp
complete -c rg -o './--hidden' -d oc
complete -c rg -o L/--follow -d 'As a special short hand, the -u flag can be specified up to three times'
complete -c rg -o uu -d oc
complete -c rg -o uuu -d 'In particular, rg -uuu should search the same exact content as grep -r'

