# rndc
# Autogenerated from man page /usr/share/man/man8/rndc.8.gz
complete -c rndc -s 4 -d 'This option indicates use of IPv4 only'
complete -c rndc -s 6 -d 'This option indicates use of IPv6 only'
complete -c rndc -s b -d 'This option indicates source-address as the source address for the connection…'
complete -c rndc -s c -d 'This option indicates config-file as the configuration file instead of the de…'
complete -c rndc -s k -d 'This option indicates key-file as the key file instead of the default, /etc/r…'
complete -c rndc -s s -d 'server is the name or address of the server which matches a server statement …'
complete -c rndc -s p -d 'This option instructs BIND 9 to send commands to TCP port port instead of its…'
complete -c rndc -s q -d 'This option sets quiet mode, where message text returned by the server is not…'
complete -c rndc -s r -d 'This option instructs rndc to print the result code returned by named after e…'
complete -c rndc -s V -d 'This option enables verbose logging'
complete -c rndc -s y -d 'This option indicates use of the key key_id from the configuration file'
complete -c rndc -s d -s f
complete -c rndc -o redirect -d 'would specify a zone called "-redirect". ) LIMITATIONS'

