# rpcbind
# Autogenerated from man page /usr/share/man/man8/rpcbind.8.gz
complete -c rpcbind -s a -d 'When debugging d, do an abort on errors'
complete -c rpcbind -s d -d 'Run in debug mode'
complete -c rpcbind -s f -d 'Do not fork and become a background process'
complete -c rpcbind -s h -d 'Specify specific IP addresses to bind to for UDP requests'
complete -c rpcbind -s i -d 'Insecure mode.  Allow calls to SET and UNSET from any host'
complete -c rpcbind -s l -d 'Turn on libwrap connection logging'
complete -c rpcbind -s s -d 'Cause rpcbind to change to the user daemon as soon as possible'
complete -c rpcbind -s w -d 'Cause rpcbind to do a "warm start" by read a state file when rpcbind starts up'

