# rpcdebug
# Autogenerated from man page /usr/share/man/man8/rpcdebug.8.gz
complete -c rpcdebug -s c -d 'Clear the given debug flags'
complete -c rpcdebug -s h -d 'Print a help message and exit'
complete -c rpcdebug -s m -d 'Specify which module\'s flags to set or clear.   Available modules are: . RS'
complete -c rpcdebug -s s -d 'Set the given debug flags'
complete -c rpcdebug -s v -d 'Increase the verbosity of rpcdebug\'s output'

