# scsi_start
# Autogenerated from man page /usr/share/man/man8/scsi_start.8.gz
complete -c scsi_start -s h -l help -d 'print out the usage message then exit'
complete -c scsi_start -s v -l verbose -d 'increase level or verbosity'
complete -c scsi_start -s w -l wait -d 'wait for the spin up (start) on each given DEVICE to complete'

