# scsi_ch_swp
# Autogenerated from man page /usr/share/man/man8/scsi_ch_swp.8.gz
complete -c scsi_ch_swp -s h -l help -d 'print out the usage message then exit'
complete -c scsi_ch_swp -s s -l set -d 'when 0 is given then the SWP bit in the Control mode page is cleared (i. e'
complete -c scsi_ch_swp -s v -l verbose -d 'increase level or verbosity'
complete -c scsi_ch_swp -s w -l wr -d 'when the BLK_DEVICE is in read-only mode, Linux will not typically allow BLK_…'

