# sddm-greeter
# Autogenerated from man page /usr/share/man/man1/sddm-greeter.1.gz
complete -c sddm-greeter -l theme -d 'Specify theme full path'
complete -c sddm-greeter -l socket -d 'Specify the socket used to communicate with sddm daemon'
complete -c sddm-greeter -l test-mode -d 'Start greeter in test mode'
complete -c sddm-greeter -l help -s h -d 'Show help message and exit'

