# setcifsacl
# Autogenerated from man page /usr/share/man/man1/setcifsacl.1.gz
complete -c setcifsacl -s h -d 'Print usage message and exit'
complete -c setcifsacl -s v -d 'Print version number and exit'
complete -c setcifsacl -s U -d 'Apply ACE editing actions (-a, -D, -M, -S) to SACL (aUdit ACL)'
complete -c setcifsacl -s a -d 'Add one or more ACEs to an ACL of a security descriptor'
complete -c setcifsacl -s D -d 'Delete one or more ACEs from an ACL of a security descriptor'
complete -c setcifsacl -s M -d 'Modify one or more ACEs from an ACL of a security descriptor'
complete -c setcifsacl -s S -d 'Set an ACL of security descriptor with the list of ACEs Existing ACL is repla…'
complete -c setcifsacl -s o -d 'Set owner SID to one specified as a command line argument'
complete -c setcifsacl -s g -d 'Set group SID to one specified as a command line argument'

