# sg_dd
# Autogenerated from man page /usr/share/man/man8/sg_dd.8.gz
complete -c sg_dd -s d -l dry-run -d 'does all the command line parsing and preparation but bypasses the actual cop…'
complete -c sg_dd -s h -l help -d 'outputs usage message and exits'
complete -c sg_dd -s p -l progress -d 'this option causes a progress report to be output every two minutes until the…'
complete -c sg_dd -s v -l verbose -d 'when used once, this is equivalent to verbose=1.  When used twice (e. g'
complete -c sg_dd -s x -l verify -d 'do a verify operation (like Unix command cmp(1)) rather than a copy'
complete -c sg_dd -s V -l version -d 'outputs version number information and exits'

