# sg_emc_trespass
# Autogenerated from man page /usr/share/man/man8/sg_emc_trespass.8.gz
complete -c sg_emc_trespass -s d -d 'outputs some extra debug information associated with executing this command'
complete -c sg_emc_trespass -o hr -d 'Sets the \'Honor Reservation\' bit in the command'
complete -c sg_emc_trespass -s s -d 'Send the short version of the trespass command instead of the long version'
complete -c sg_emc_trespass -s V -d 'print out version string then exit'

