# sg_read_block_limits
# Autogenerated from man page /usr/share/man/man8/sg_read_block_limits.8.gz
complete -c sg_read_block_limits -s h -l help -d 'output the usage message then exit'
complete -c sg_read_block_limits -s H -l hex -d 'output response in hex (rather than decode it)'
complete -c sg_read_block_limits -s r -l raw -d 'output response in binary to stdout'
complete -c sg_read_block_limits -s R -l readonly -d 'open DEVICE in read-only mode.  The default is to open it in read-write mode'
complete -c sg_read_block_limits -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_read_block_limits -s V -l version -d 'print the version string and then exit'

