# sg_rtpg
# Autogenerated from man page /usr/share/man/man8/sg_rtpg.8.gz
complete -c sg_rtpg -s d -l decode -d 'decodes the status code and asymmetric access state from each target port gro…'
complete -c sg_rtpg -s e -l extended -d 'use extended header format for parameter data'
complete -c sg_rtpg -s h -l help -d 'output the usage message then exit'
complete -c sg_rtpg -s H -l hex -d 'output response in hex (rather than partially or fully decode it)'
complete -c sg_rtpg -s r -l raw -d 'output response in binary to stdout'
complete -c sg_rtpg -s R -l readonly -d 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag)'
complete -c sg_rtpg -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_rtpg -s V -l version -d 'print the version string and then exit'

