# sg_reassign
# Autogenerated from man page /usr/share/man/man8/sg_reassign.8.gz
complete -c sg_reassign -s a -l address -d 'where A,A.  is a string of comma separated numbers'
complete -c sg_reassign -s d -l dummy -d 'prepare for but do not execute the SCSI REASSIGN BLOCKS command'
complete -c sg_reassign -s e -l eight -d 'when value is 1 then it sets the \'LONGLBA\' flag in the command indicating tha…'
complete -c sg_reassign -s g -l grown -d 'use the SCSI READ DEFECT DATA (10) command to determine the number of element…'
complete -c sg_reassign -s h -l help -d 'output the usage message then exit'
complete -c sg_reassign -s H -l hex -d 'print response in hex (for -g, --grown, -p or --primary)'
complete -c sg_reassign -s l -l longlist -d 'sets the REASSIGN BLOCKS cdb field of the same name to the given value'
complete -c sg_reassign -s p -l primary -d 'use the SCSI READ DEFECT DATA (10) command to determine the number of element…'
complete -c sg_reassign -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_reassign -s V -l version -d 'print the version string and then exit'

