# sg_reset_wp
# Autogenerated from man page /usr/share/man/man8/sg_reset_wp.8.gz
complete -c sg_reset_wp -s a -l all -d 'sets the ALL field in the cdb'
complete -c sg_reset_wp -s C -l count -d 'ZC is placed in the Zone Count field in the cdb of the RESET WRITE POINTER co…'
complete -c sg_reset_wp -s h -l help -d 'output the usage message then exit'
complete -c sg_reset_wp -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_reset_wp -s V -l version -d 'print the version string and then exit'
complete -c sg_reset_wp -l zone
complete -c sg_reset_wp -s z -d 'where ID is placed in the cdb\'s ZONE ID field'

