# sg_rep_pip
# Autogenerated from man page /usr/share/man/man8/sg_rep_pip.8.gz
complete -c sg_rep_pip -s h -l help -d 'output the usage message then exit'
complete -c sg_rep_pip -s H -l hex -d 'output the response in hexadecimal to stdout'
complete -c sg_rep_pip -s m -l maxlen -d 'where LEN is the (maximum) response length in bytes'
complete -c sg_rep_pip -s r -l raw -d 'output the SCSI response (i. e.  the data-out buffer) in binary (to stdout)'
complete -c sg_rep_pip -s R -l readonly -d 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag)'
complete -c sg_rep_pip -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_rep_pip -s V -l version -d 'print the version string and then exit'

