# sg_rbuf
# Autogenerated from man page /usr/share/man/man8/sg_rbuf.8.gz
complete -c sg_rbuf -s b -l buffer -d 'where EACH is the number of bytes to be transferred by each READ BUFFER comma…'
complete -c sg_rbuf -s d -l dio -d 'use direct IO if available'
complete -c sg_rbuf -s h -l help -d 'print usage message then exit'
complete -c sg_rbuf -s m -l mmap -d 'use memory mapped IO if available'
complete -c sg_rbuf -s O -l old -d 'Switch to older style options.  Please use as first option'
complete -c sg_rbuf -s q -l quick -d 'only transfer the data into kernel buffers (typically by DMA from the SCSI ad…'
complete -c sg_rbuf -s s -l size -d 'where OVERALL is the size of total transfer in bytes'
complete -c sg_rbuf -s t -l time -d 'times the bulk data transfer component of this command'
complete -c sg_rbuf -s v -l verbose -d 'increase level of verbosity.  Can be used multiple times'
complete -c sg_rbuf -s V -l version -d 'print out version string then exit'
complete -c sg_rbuf -s N -l new -d 'Switch to the newer style options'

