# sg_sat_set_features
# Autogenerated from man page /usr/share/man/man8/sg_sat_set_features.8.gz
complete -c sg_sat_set_features -s c -l count -d 'the number CO is placed in the "count" field in the ATA SET FEATURES command'
complete -c sg_sat_set_features -s C -l ck_cond -d 'sets the CK_COND bit in the ATA PASS-THROUGH SCSI cdb'
complete -c sg_sat_set_features -s e -l extended -d 'allow for extended LBA numbers (i. e.  larger than 32 bits)'
complete -c sg_sat_set_features -s f -l feature -d 'the value FEA is placed in the "feature" field in the ATA SET FEATURES command'
complete -c sg_sat_set_features -s h -l help -d 'outputs the usage message summarizing command line options then exits'
complete -c sg_sat_set_features -s L -l lba -d 'the number LBA is placed in the "lba" field of the ATA SET FEATURES command'
complete -c sg_sat_set_features -s l -l len -d 'this is the length of the SCSI cdb used for the ATA PASS-THROUGH commands'
complete -c sg_sat_set_features -s r -l readonly -d 'causes the DEVICE to be opened with the read-only flag (O_RDONLY in Unix)'
complete -c sg_sat_set_features -s v -l verbose -d 'increases the level or verbosity'
complete -c sg_sat_set_features -s V -l version -d 'print out version string NOTES In the 2'

