# sg_safte
# Autogenerated from man page /usr/share/man/man8/sg_safte.8.gz
complete -c sg_safte -s c -l config -d 'will issues a  Read Enclosure Configuration '
complete -c sg_safte -s d -l devstatus -d 'will issue a  Read Device Slot Status '
complete -c sg_safte -s s -l encstatus -d 'will issue a  Read Enclosure Status '
complete -c sg_safte -s f -l flags -d 'will issue a  Read Global Flags '
complete -c sg_safte -s h -l help -d 'output the usage message then exit'
complete -c sg_safte -s H -l hex -d 'output the response to a READ BUFFER command in ASCII hex to stdout'
complete -c sg_safte -s i -l insertions -d 'will issue a  Read Device Insertions '
complete -c sg_safte -s r -l raw -d 'output the response to a READ BUFFER command in binary to stdout'
complete -c sg_safte -s u -l usage -d 'will issue a  Read Usage Statistics '
complete -c sg_safte -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_safte -s V -l version -d 'print the version string and then exit'

