# sg_stpg
# Autogenerated from man page /usr/share/man/man8/sg_stpg.8.gz
complete -c sg_stpg -s a -l active -d 'set active/non-optimized state'
complete -c sg_stpg -s h -l help -d 'output the usage message then exit'
complete -c sg_stpg -s H -l hex -d 'output response to the REPORT TARGET PORT GROUPS command in hex then exit'
complete -c sg_stpg -s O -s l -l offline -d 'set offline state'
complete -c sg_stpg -s o -l optimized -d 'set active/optimized state'
complete -c sg_stpg -s r -l raw -d 'output response to the REPORT TARGET PORT GROUPS command in binary to stdout …'
complete -c sg_stpg -s s -l standby -d 'set standby state'
complete -c sg_stpg -s S -l state -d 'specifies a comma separated list (one element of more) of states'
complete -c sg_stpg -s t -l tp -d 'specifies a comma separated list (one element of more)'
complete -c sg_stpg -s u -l unavailable -d 'set unavailable state'
complete -c sg_stpg -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_stpg -s V -l version -d 'print the version string and then exit'

