# sg_sat_identify
# Autogenerated from man page /usr/share/man/man8/sg_sat_identify.8.gz
complete -c sg_sat_identify -s c -l ck_cond -d 'sets the CK_COND bit in the ATA PASS-THROUGH SCSI cdb'
complete -c sg_sat_identify -s e -l extend -d 'sets the EXTEND bit in the ATA PASS-THROUGH SCSI cdb'
complete -c sg_sat_identify -s h -l help -d 'outputs the usage message summarizing command line options then exits'
complete -c sg_sat_identify -s H -l hex -d 'outputs the ATA IDENTIFY (PACKET) DEVICE response in hex'
complete -c sg_sat_identify -s i -l ident -d 'outputs the World Wide Name (WWN) of the device'
complete -c sg_sat_identify -s l -l len -d 'CLEN this is the length of the SCSI cdb used for the ATA PASS-THROUGH command'
complete -c sg_sat_identify -s p -l packet -d 'send an ATA IDENTIFY PACKET DEVICE command (via the SATL)'
complete -c sg_sat_identify -s r -l raw -d 'output the ATA IDENTIFY (PACKET) DEVICE response in binary'
complete -c sg_sat_identify -s R -l readonly -d 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag)'
complete -c sg_sat_identify -s v -l verbose -d 'increases the level or verbosity'
complete -c sg_sat_identify -s V -l version -d 'print out version string NOTES Since the response to the IDENTIFY (PACKET) DE…'

