# sg_timestamp
# Autogenerated from man page /usr/share/man/man8/sg_timestamp.8.gz
complete -c sg_timestamp -s e -l elapsed -d 'assume the timestamp in the REPORT TIMESTAMP is an elapsed time from an event…'
complete -c sg_timestamp -s h -l help -d 'output the usage message then exit'
complete -c sg_timestamp -s H -l hex -d 'output the response to REPORT TIMESTAMP in ASCII hexadecimal on stderr'
complete -c sg_timestamp -s m -l milliseconds -d 'where MS is the number of milliseconds since 1970-01-01 00:00:00 UTC to set i…'
complete -c sg_timestamp -s N -l no-timestamp -d 'when REPORT TIMESTAMP is called this option suppress the output of the timest…'
complete -c sg_timestamp -s o -l origin -d 'the REPORT TIMESTAMP returned parameter data contains a "timestamp origin" fi…'
complete -c sg_timestamp -s r -l raw -d 'output the SCSI REPORT TIMESTAMP response (i. e'
complete -c sg_timestamp -s R -l readonly -d 'open the DEVICE read-only'
complete -c sg_timestamp -s s -l seconds -d 'where SECS is the number of seconds since 1970-01-01 00:00:00 UTC to set in t…'
complete -c sg_timestamp -s S -l srep -d 'report the number of seconds since 1970-01-01 00:00:00 UTC'
complete -c sg_timestamp -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_timestamp -s V -l version -d 'print the version string and then exit'

