# sg_unmap
# Autogenerated from man page /usr/share/man/man8/sg_unmap.8.gz
complete -c sg_unmap -s A -l all -d 'where ST is the starting LBA, RN is the repeat number which is the maximum nu…'
complete -c sg_unmap -s a -l anchor -d 'sets the \'Anchor\' bit in the command (introduced in sbc3r22)'
complete -c sg_unmap -s d -l dry-run -d 'perform all the preparation, including opening DEVICE plus sending a \'standar…'
complete -c sg_unmap -s f -l force -d 'bypass the 15 second warning period that occurs before any UNMAP commands are…'
complete -c sg_unmap -s g -l grpnum -d 'sets the \'Group number\' field to GN.  Defaults to a value of zero'
complete -c sg_unmap -s h -l help -d 'output the usage message then exit'
complete -c sg_unmap -s I -l in -d 'where FILE is a file name containing pairs of values'
complete -c sg_unmap -s l -l lba -d 'where LBA,LBA'
complete -c sg_unmap -s n -l num -d 'where NUM,NUM'
complete -c sg_unmap -s t -l timeout -d 'where TO is a timeout value (in seconds) for the UNMAP command'
complete -c sg_unmap -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_unmap -s V -l version -d 'print the version string and then exit'

