# sg_write_verify
# Autogenerated from man page /usr/share/man/man8/sg_write_verify.8.gz
complete -c sg_write_verify -s S -l 16 -d 'Send a WRITE AND VERIFY(16) command'
complete -c sg_write_verify -s b -l bytchk -d 'where BC is the value to place in the command\'s BYTCHK field'
complete -c sg_write_verify -s d -l dpo -d 'Set the DPO (disable page out) bit in the command'
complete -c sg_write_verify -s g -l group -d 'where GN is the value to place in the command\'s GROUP NUMBER field'
complete -c sg_write_verify -s h -l help -d 'output the usage message then exit'
complete -c sg_write_verify -s I -l ilen -d 'where ILEN is the number of bytes that will be placed in the data-out buffer'
complete -c sg_write_verify -s i -l in -d 'read data (binary) from file named IF.  If IF is "-" then stdin is used'
complete -c sg_write_verify -s l -l lba -d 'where LBA is the logical block address to start the write to medium'
complete -c sg_write_verify -s n -l num -d 'where NUM is the number of blocks, starting at LBA, to write to the medium'
complete -c sg_write_verify -s R -l repeat -d 'this option will continue to do WRITE AND VERIFY commands until the IF file i…'
complete -c sg_write_verify -s t -l timeout -d 'where TO is the command timeout value in seconds'
complete -c sg_write_verify -s v -l verbose -d 'increase the degree of verbosity (debug messages)'
complete -c sg_write_verify -s V -l version -d 'output version string then exit'
complete -c sg_write_verify -s w -l wrprotect -d 'set the WRPROTECT field in the cdb to WP'

