# sg_zone
# Autogenerated from man page /usr/share/man/man8/sg_zone.8.gz
complete -c sg_zone -s a -l all -d 'sets the ALL field in the cdb'
complete -c sg_zone -s c -l close -d 'causes the CLOSE ZONE command to be sent to the DEVICE'
complete -c sg_zone -s C -l count -d 'ZC is placed in the Zone Count field in the cdb of all four commands supporte…'
complete -c sg_zone -s e -l element -d 'where EID is an element identifier which is a 32 bit unsigned integer startin…'
complete -c sg_zone -s f -l finish -d 'causes the FINISH ZONE command to be sent to the DEVICE'
complete -c sg_zone -s h -l help -d 'output the usage message then exit'
complete -c sg_zone -s o -l open -d 'causes the OPEN ZONE command to be sent to the DEVICE'
complete -c sg_zone -s r -l remove -d 'causes the REMOVE ELEMENT AND MODIFY ZONES command to be sent to the DEVICE'
complete -c sg_zone -s S -l sequentialize -d 'causes the SEQUENTIALIZE ZONE command to be sent to the DEVICE'
complete -c sg_zone -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_zone -s V -l version -d 'print the version string and then exit'
complete -c sg_zone -s z -l zone -d 'where ID is placed in the cdb\'s ZONE ID field'

