# smbinfo
# Autogenerated from man page /usr/share/man/man1/smbinfo.1.gz
complete -c smbinfo -s v -d 'Print version number and exit'
complete -c smbinfo -s V -d 'Verbose output'
complete -c smbinfo -s h -d 'Print help explaining the command line options'

