# statd
# Autogenerated from man page /usr/share/man/man8/statd.8.gz
complete -c statd -s d -l no-syslog -d 'Causes  rpc'
complete -c statd -s F -l foreground -d 'Keeps  rpc'
complete -c statd -s h -s '?' -l help -d 'Causes  rpc. statd to display usage information on  stderr and then exit'
complete -c statd -s H -l ha-callout -d 'Specifies a high availability callout program'
complete -c statd -s L -l no-notify -d 'Prevents  rpc'
complete -c statd -s n -l name -d 'This string is only used by the  sm-notify command as the source address from…'
complete -c statd -s N -d 'Causes  rpc. statd to run the  sm-notify command, and then exit'
complete -c statd -s o -l outgoing-port -d 'Specifies the source port number the  sm-notify command should use when sendi…'
complete -c statd -s p -l port -d 'Specifies the port number used for RPC listener sockets'
complete -c statd -s T -l nlm-port -d 'Specifies the port number that  lockd should listen on for  NLM requests'
complete -c statd -s U -l nlm-udp-port -d 'Specifies the UDP port number that  lockd should listen on for  NLM requests'
complete -c statd -s P -l state-directory-path -d 'Specifies the pathname of the parent directory where NSM state information re…'
complete -c statd -s v -s V -l version -d 'Causes rpc. statd to display version information on stderr and then exit'

