# tcpspray6
# Autogenerated from man page /usr/share/man/man1/tcpspray6.1.gz
complete -c tcpspray6 -s 4 -l ipv4 -d 'Force usage of TCP over IPv4'
complete -c tcpspray6 -s 6 -l ipv6 -d 'Force usage of TCP over IPv6'
complete -c tcpspray6 -s b -l bsize -d 'Send block of the specified byte size (default: 1024)'
complete -c tcpspray6 -s d -l delay -d 'Waits for the given amount of microseconds after any given was sent before at…'
complete -c tcpspray6 -s e -l echo -d 'Use the Echo protocol instead of Discard'
complete -c tcpspray6 -s f -l fill -d 'Read data from the specified file to fill sent blocks with'
complete -c tcpspray6 -s h -l help -d 'Display some help and exit'
complete -c tcpspray6 -s n -l count -d 'Send the specified amount of data blocks for the measurements (default: 100)'
complete -c tcpspray6 -s V -l version -d 'Display program version and license and exit'
complete -c tcpspray6 -s v -l verbose -d 'Display more verbose informations'

