# tcpspray
# Autogenerated from man page /usr/share/man/man1/tcpspray.1.gz
complete -c tcpspray -s 4 -l ipv4 -d 'Force usage of TCP over IPv4'
complete -c tcpspray -s 6 -l ipv6 -d 'Force usage of TCP over IPv6'
complete -c tcpspray -s b -l bsize -d 'Send block of the specified byte size (default: 1024)'
complete -c tcpspray -s d -l delay -d 'Waits for the given amount of microseconds after any given was sent before at…'
complete -c tcpspray -s e -l echo -d 'Use the Echo protocol instead of Discard'
complete -c tcpspray -s f -l fill -d 'Read data from the specified file to fill sent blocks with'
complete -c tcpspray -s h -l help -d 'Display some help and exit'
complete -c tcpspray -s n -l count -d 'Send the specified amount of data blocks for the measurements (default: 100)'
complete -c tcpspray -s V -l version -d 'Display program version and license and exit'
complete -c tcpspray -s v -l verbose -d 'Display more verbose informations'

