# termite
# Autogenerated from man page /usr/share/man/man1/termite.1.gz
complete -c termite -s h -l help -d 'Display help message'
complete -c termite -s v -l version -d 'Display version information'
complete -c termite -s e -l exec -d 'Tell termite start COMMAND instead of the shell'
complete -c termite -s r -l role -d 'The role to set the termite window to report itself with'
complete -c termite -s t -l title -d 'Set the termite window\'s title to TITLE.  This disables dynamic titles'
complete -c termite -s d -l directory -d 'Tell termite to change to DIRECTORY when launching'
complete -c termite -l 'icon\\f8' -d 'Override the window icon name'
complete -c termite -l hold -d 'Keep termite open after the child process exits'
complete -c termite -l display -d 'Launch on DISPLAY X display'
complete -c termite -s c -l config -d 'Specify a path to an alternative config file to use'
complete -c termite -l name -d 'Set the windows name part of the WM_CLASS property'
complete -c termite -l icon -d 'Override the window icon name'
complete -c termite -l help-gtk
complete -c termite -l class -d 'Set the windows class part of the WM_CLASS property'

