# tmux
# Autogenerated from man page /usr/share/man/man1/tmux.1.gz
complete -c tmux -s 2 -d 'Force tmux to assume the terminal supports 256 colours'
complete -c tmux -s C -d 'Start in control mode (see the CONTROL MODE section)'
complete -c tmux -s c -d 'Execute shell-command using the default shell'
complete -c tmux -s D -d 'Do not start the tmux server as a daemon'
complete -c tmux -s f -d 'Specify an alternative configuration file'
complete -c tmux -s L -d 'tmux stores the server socket in a directory under TMUX_TMPDIR or /tmp if it …'
complete -c tmux -s l -d 'Behave as a login shell'
complete -c tmux -s N -d 'Do not start the server even if the command would normally do so (for example…'
complete -c tmux -s S -d 'Specify a full alternative path to the server socket'
complete -c tmux -s u -d 'Write UTF-8 output to the terminal even if the first environment variable of …'
complete -c tmux -s T -d 'Set terminal features for the client'
complete -c tmux -s v -d 'Request verbose logging.  Log messages will be saved into tmux-client-PID'
complete -c tmux -s V -d 'Report the tmux version'

