# tsig-keygen
# Autogenerated from man page /usr/share/man/man8/tsig-keygen.8.gz
complete -c tsig-keygen -s a -d 'This option specifies the algorithm to use for the TSIG key'
complete -c tsig-keygen -s h -d 'This option prints a short summary of options and arguments'
complete -c tsig-keygen -s k -d 'This option specifies the key name of the DDNS authentication key'
complete -c tsig-keygen -s q -d 'This option enables quiet mode, which prints only the key, with no explanator…'
complete -c tsig-keygen -s s -d 'This option generates a configuration example to allow dynamic updates of a s…'
complete -c tsig-keygen -s z -d 'This option generates a configuration example to allow dynamic updates of a z…'

