# udfinfo
# Autogenerated from man page /usr/share/man/man1/udfinfo.1.gz
complete -c udfinfo -s h -l help -d 'Display the usage and the list of options'
complete -c udfinfo -s b -l blocksize -d 'Specify the size of blocks in bytes'
complete -c udfinfo -l startblock -d 'Specify the block location where the UDF filesystem starts'
complete -c udfinfo -l lastblock -d 'Specify the block location where the UDF filesystem ends'
complete -c udfinfo -l vatblock -d 'Specify the block location of the Virtual Allocation Table'
complete -c udfinfo -l locale -d 'Encode UDF string identifiers on output according to current locale settings …'
complete -c udfinfo -l u8 -d 'Encode UDF string identifiers on output to 8-bit OSTA Compressed Unicode form…'
complete -c udfinfo -l u16 -d 'Encode UDF string identifiers on output to 16-bit OSTA Compressed Unicode for…'
complete -c udfinfo -l utf8 -d 'Encode UDF string identifiers on output to UTF-8'

