# update-smart-drivedb
# Autogenerated from man page /usr/share/man/man8/update-smart-drivedb.8.gz
complete -c update-smart-drivedb -s s -d 'Use the  smartctl (8) executable at path SMARTCTL for drive database syntax c…'
complete -c update-smart-drivedb -s t -d 'Use TOOL for download.  TOOL is one of:  curl wget lynx . \\"# '
complete -c update-smart-drivedb -s u -d 'Use URL of LOCATION for download.  LOCATION is one of: '
complete -c update-smart-drivedb -l trunk -d 'Download from SVN trunk'
complete -c update-smart-drivedb -l branch -d '[NEW EXPERIMENTAL UPDATE-SMART-DRIVEDB FEATURE] Download from branches/RELEAS…'
complete -c update-smart-drivedb -l cacert -d 'Use CA certificates from FILE to verify the peer'
complete -c update-smart-drivedb -l capath -d 'Use CA certificate files from DIR to verify the peer'
complete -c update-smart-drivedb -l insecure -d 'Don\'t abort download if certificate verification fails'
complete -c update-smart-drivedb -l no-verify -d 'Don\'t verify signature with GnuPG'
complete -c update-smart-drivedb -l export-key -d 'Print the OpenPGP/GPG public key block'
complete -c update-smart-drivedb -l dryrun -d 'Print download commands only'

