# wvdial
# Autogenerated from man page /usr/share/man/man1/wvdial.1.gz
complete -c wvdial -s c -l chat -d 'Run wvdial as a chat replacement from within pppd, instead of the more normal…'
complete -c wvdial -s C -l config -d 'Run wvdial with CONFIGFILE as the configuration file, instead of R /etc/wvdial'
complete -c wvdial -s n -l no-syslog -d 'Don\'t output debug information to the syslog daemon (only useful together wit…'

