# xdo
# Autogenerated from man page /usr/share/man/man1/xdo.1.gz
complete -c xdo -s r -d 'Distinct ID'
complete -c xdo -s c -d 'Same class'
complete -c xdo -s C -d 'Distinct class'
complete -c xdo -s d -d 'Same desktop'
complete -c xdo -s D -d 'Distinct desktop'
complete -c xdo -s n -d 'The window has the given instance name'
complete -c xdo -s N -d 'The window has the given class name'
complete -c xdo -s a -d 'The window has the given wm name'
complete -c xdo -s t -d 'The target window for the below and above actions'
complete -c xdo -s p -d 'The window has the given pid'
complete -c xdo -s k -d 'Use the given code for the key_press, key_release, button_press and button_re…'
complete -c xdo -s x -d 'Window x coordinate (or delta) for the move and pointer_motion action'
complete -c xdo -s y -d 'Window y coordinate (or delta) for the move and pointer_motion action'
complete -c xdo -s w -d 'Window width (or delta) for the resize action'
complete -c xdo -s h -d 'Window height (or delta) for the resize action'
complete -c xdo -s m -d 'Wait for the existence of a matching window'
complete -c xdo -s s -d 'Handle symbolic desktop numbers'
complete -c xdo -s v

