# xl2tpd
# Autogenerated from man page /usr/share/man/man8/xl2tpd.8.gz
complete -c xl2tpd -s D -d 'This option prevents xl2tpd from detaching from the terminal and daemonizing'
complete -c xl2tpd -s l -d 'This option tells xl2tpd to use syslog for logging even when -D was specified'
complete -c xl2tpd -s c -d 'Set an alternate config file'
complete -c xl2tpd -s s -d 'Tells xl2tpd to use an alternate "secrets" file'
complete -c xl2tpd -s p -d 'Set an alternate pid file.  Default is /var/run/xl2tpd/xl2tpd. pid'
complete -c xl2tpd -s C -d 'Set an alternate control file.  FILES /etc/xl2tpd/xl2tpd'

