# xl2tpd-control
# Autogenerated from man page /usr/share/man/man8/xl2tpd-control.8.gz
complete -c xl2tpd-control -s c -d 'This option specifies xl2tpd control file'
complete -c xl2tpd-control -s d -d 'This option enables debugging mode'

