# y4mscaler
# Autogenerated from man page /usr/share/man/man1/y4mscaler.1.gz
complete -c y4mscaler -s v -d 'Set verbosity level.     0 = warnings and errors only'
complete -c y4mscaler -s V -d 'Show version information and exit'
complete -c y4mscaler -s h -d 'Show a help message (synopsis of options)'
complete -c y4mscaler -s I
complete -c y4mscaler -s O
complete -c y4mscaler -s S
complete -c y4mscaler -l --------------------------------------------------------------------- -d '  VCD           352x240{288}  none          10:11{59:54}   4:2:0-JPEG   CVD  …'

