# y4mtopnm
# Autogenerated from man page /usr/share/man/man1/y4mtopnm.1.gz
complete -c y4mtopnm -s P -d 'Produce PAM format output, instead of PPM and/or PGM'
complete -c y4mtopnm -s D -d 'Produce a separate output image for each field of each frame'
complete -c y4mtopnm -s f -d 'Produce a special \'flattened\' output, most useful for analyzing and debugging…'

