# y4munsharp
# Autogenerated from man page /usr/share/man/man1/y4munsharp.1.gz
complete -c y4munsharp -s v -d 'Set verbosity level (0 = quiet, 1 = normal, 2 = debug) (default: 1)'
complete -c y4munsharp -s h -d 'Print a suage summary and exit'
complete -c y4munsharp -s L -d 'Y\' (luma) unsharp parameters'

