# yuv2lav
# Autogenerated from man page /usr/share/man/man1/yuv2lav.1.gz
complete -c yuv2lav -s o -d 'This (compulsorary) option sets the name of the file that yuv2lav will write …'
complete -c yuv2lav -s f -d 'This sets the output file format, which has to be one of '
complete -c yuv2lav -s q -d 'This option specifies the JPEG encoding quality as passed through to libjpeg'
complete -c yuv2lav -s b -d 'This option specifies the size of the buffer (in kBytes) that yuv2lav allocat…'
complete -c yuv2lav -s m -d 'This is the maximum size (in MB) per file'
complete -c yuv2lav -s I -d 'Force a specific interlacing type'
complete -c yuv2lav -s w -d 'This is the WAV file containing audio data to be combined with the video stre…'
complete -c yuv2lav -s v -d 'Verbosity level'

