# yuvdenoise
# Autogenerated from man page /usr/share/man/man1/yuvdenoise.1.gz
complete -c yuvdenoise -s g -d 'This sets the thresholds for the gaussian filter'
complete -c yuvdenoise -s m -d 'This sets the thresholds for the pre-processing 3D median filter'
complete -c yuvdenoise -s r -d 'This sets the thresholds for adding random "noise" back into the video stream'
complete -c yuvdenoise -s t -d 'This sets the thresholds for the temporal noise-filter'
complete -c yuvdenoise -s M -d 'This sets the thresholds for the post-processing 3D median filter'

