# yuvinactive
# Autogenerated from man page /usr/share/man/man1/yuvinactive.1.gz
complete -c yuvinactive -s h -d 'Some help output'
complete -c yuvinactive -s i -d 'Specifies the area yuvinactive shall work with'
complete -c yuvinactive -s d -d 'How much darker the area should be compared to the original color'
complete -c yuvinactive -s s -d 'Here you specify a certain color in the yuv format'
complete -c yuvinactive -s a -d 'With this option the program uses on pixel and averages the surrounding  pixe…'

