# yuvscaler
# Autogenerated from man page /usr/share/man/man1/yuvscaler.1.gz
complete -c yuvscaler -o only -d 'downscaling- that goes much faster than bicubic'
complete -c yuvscaler -s n -d '(usually not necessary) if norm could not be determined from data flux, speci…'
complete -c yuvscaler -s v -d 'Specifies the degree of verbosity: 0=quiet, 1=normal, 2=verbose/debug'
complete -c yuvscaler -s h -d 'Prints a summary of command line syntax'
complete -c yuvscaler -s I -d 'Specifies input processing options'
complete -c yuvscaler -s M -d 'Sets the scaling mode options'
complete -c yuvscaler -s O

