# zresample
# Autogenerated from man page /usr/share/man/man1/zresample.1.gz
complete -c zresample -l help -d 'Display a short help text'
complete -c zresample -l rate -d 'Set the output sample rate'
complete -c zresample -l gain -d 'Gain in dB, default zero. SS Output file type'
complete -c zresample -l wav -d 'Produce a WAV file, or for more than 2 channels, a WAVEX file'
complete -c zresample -l amb -d 'Produce a WAVEX file with the Ambisonic GUID.  Such files should have the  '
complete -c zresample -l caf -d 'Produce a Core Audio file'
complete -c zresample -l aiff -d 'Produce an AIFF file'
complete -c zresample -l flac -d 'Produce a FLAC file. SS Output sample format'
complete -c zresample -l 16bit -d 'Output sample format is signed 16-bit'
complete -c zresample -l 24bit -d 'Output sample format is 24-bit.  This is the default'
complete -c zresample -l float -d 'Output sample format is 32-bit floating point. SS Dithering'
complete -c zresample -l rec -d 'Add white dithering noise with a rectangular distribution'
complete -c zresample -l tri -d 'Add filtered noise with a triangular distribution'
complete -c zresample -l lips -d 'This uses the optimal error feedback filter described by  Stanley Lipschitz'
complete -c zresample -l pad -d 'Insert zero valued input samples at the start and end so that the output incl…'

