# zvbid
# Autogenerated from man page /usr/share/man/man1/zvbid.1.gz
complete -c zvbid -o dev -d 'Path of a device from which to read data'
complete -c zvbid -o buffers -d 'Number of buffers to allocate for capturing VBI raw data from devices which s…'
complete -c zvbid -o nodetach -d 'Daemon process remains connected to the terminal from which it was started (e'
complete -c zvbid -o kill -d 'Terminates a proxy daemon running for the given device'
complete -c zvbid -o debug -d 'Enables debug output: 0= off(default); 1= general messages; In addition 2, 4,…'
complete -c zvbid -o syslog -d 'Enables syslog output'
complete -c zvbid -o loglevel -d 'Log file level'
complete -c zvbid -o logfile -d 'Path to the log file'
complete -c zvbid -o maxclients -d 'Max.  number of clients which are allowed to connect simultaneously'
complete -c zvbid -o help -d 'Print a short description of all command line options'

