# zvbi-chains
# Autogenerated from man page /usr/share/man/man1/zvbi-chains.1.gz
complete -c zvbi-chains -o dev -d 'Path of a VBI device from which to read data'
complete -c zvbi-chains -o debug -d 'Enables debug output: 0 = off (default); 1 = warnings, 2 = all messages'
complete -c zvbi-chains -o help -d 'Print a short description of all command line options'

