# zvbi-atsc-cc
# Autogenerated from man page /usr/share/man/man1/zvbi-atsc-cc.1.gz
complete -c zvbi-atsc-cc -s '?' -s h -l help -l usage -d 'Print a short usage message'
complete -c zvbi-atsc-cc -s q -l quiet -d 'Suppress all progress and error messages'
complete -c zvbi-atsc-cc -s v -l verbose -d 'Increase verbosity. SS "Device options"'
complete -c zvbi-atsc-cc -l adapter-num -d 'PD Select a different DVB device to capture the signal (/dev/dvb/adapterN)'
complete -c zvbi-atsc-cc -l frontend-id -d 'PD Select a different frontend on the DVB device (/dev/dvb/adapterN/frontendM)'
complete -c zvbi-atsc-cc -l demux-id -d 'PD Select a different demultiplexer on the DVB device (/dev/dvb/adapterN/demu…'
complete -c zvbi-atsc-cc -l dvr-id -d 'PD Select a different DVR interface on the DVB device (/dev/dvb/adapterN/dvrM)'
complete -c zvbi-atsc-cc -l ts -d 'PD Decode an MPEG-2 Transport Stream on standard input instead of opening a D…'
complete -c zvbi-atsc-cc -l channel-conf -d 'PD To tune in a TV station  zvbi-atsc-cc needs a channel configuration file'
complete -c zvbi-atsc-cc -s L -l list -d 'List all stations in the channel configuration file and their transponder fre…'
complete -c zvbi-atsc-cc -l station -d 'PD The station to tune in.  Usually the -n can be omitted'
complete -c zvbi-atsc-cc -s c -l cc -d 'Print any received caption on standard output'
complete -c zvbi-atsc-cc -l cc-file -d 'PD Append any received caption to the specified file'
complete -c zvbi-atsc-cc -l channel -d 'PD Print NTSC Closed Caption channel 1, 2, 3 or 4 on standard output'
complete -c zvbi-atsc-cc -l cc1-file -l cc4-file -d 'PD Filter out NTSC Closed Caption channel CC1 '
complete -c zvbi-atsc-cc -l t1-file -l t4-file -d 'PD Filter out NTSC Text service T1 '
complete -c zvbi-atsc-cc -l s1-file -l s2-file -d 'PD Filter out DTVCC service 1 or 2 and append the text to the specified file'
complete -c zvbi-atsc-cc -s b -l no-webtv -d 'Do not print WebTV links'
complete -c zvbi-atsc-cc -s m -l timestamps -d 'Prepend timestamps (YYYYMMDDHHMMSS) to caption lines'
complete -c zvbi-atsc-cc -s s -l sentences -d 'Print caption one sentence at a time'
complete -c zvbi-atsc-cc -l format -d 'PD When type is "plain"  zvbi-atsc-cc prints caption and XDS text without any…'
complete -c zvbi-atsc-cc -s p -l plain -d 'Same as -jplain . SS "XDS options"'
complete -c zvbi-atsc-cc -s x -l xds -d 'Print all received XDS data on standard output'
complete -c zvbi-atsc-cc -l xds-file -d 'PD Filter out eXtended Data Service data (station name, program name, program…'
complete -c zvbi-atsc-cc -s a
complete -c zvbi-atsc-cc -s i
complete -c zvbi-atsc-cc -s d
complete -c zvbi-atsc-cc -s r
complete -c zvbi-atsc-cc -s T
complete -c zvbi-atsc-cc -l atsc -d 'option to clarify that this is an ATSC TS and the program should expect an az…'
complete -c zvbi-atsc-cc -s e
complete -c zvbi-atsc-cc -s n
complete -c zvbi-atsc-cc -s C
complete -c zvbi-atsc-cc -s l
complete -c zvbi-atsc-cc -s 1 -s 4
complete -c zvbi-atsc-cc -s 5 -s 8
complete -c zvbi-atsc-cc -s 9 -s 0
complete -c zvbi-atsc-cc -s j
complete -c zvbi-atsc-cc -s X
complete -c zvbi-atsc-cc -s f
complete -c zvbi-atsc-cc -l filter

