# a52dec
# Autogenerated from man page /usr/share/man/man1/a52dec.1.gz
complete -c a52dec -s h -d 'display help and available audio modes'
complete -c a52dec -s s -d 'use program stream demultiplexer, track 0-7 or 0x80-0x87'
complete -c a52dec -s t -d 'use transport stream demultiplexer, pid 0x10-0x1ffe'
complete -c a52dec -s c -d 'use c implementation, disables all accelerations'
complete -c a52dec -s r -d 'disable dynamic range compression'
complete -c a52dec -s o -d 'use audio output driver `mode\''

