# addr2name
# Autogenerated from man page /usr/share/man/man1/addr2name.1.gz
complete -c addr2name -s 4 -l ipv4 -d 'Only try to perform IPv4 lookups'
complete -c addr2name -s 6 -l ipv6 -d 'Only try to perform IPv6 lookups'
complete -c addr2name -s c -l config -d 'Only lookup and print results for address families that match locally configu…'
complete -c addr2name -s h -l help -d 'Display some help and exit'
complete -c addr2name -s m -l multiple -d 'Normally, if a name yields multiple results, only the first one is printed'
complete -c addr2name -s n -l numeric -d 'Prevent forward hostname lookup'
complete -c addr2name -s r -l reverse -d 'Perform a reverse DNS lookup . RB "(enabled implicitly with " "addr2name" ")'
complete -c addr2name -l version -d 'Display program version and license and exit'

