# alacritty
# Autogenerated from man page /usr/share/man/man1/alacritty.1.gz
complete -c alacritty -l class -d 'Defines the window class hint on Linux [default: Alacritty,Alacritty]  On Way…'
complete -c alacritty -s e -l command -d 'Command and args to execute (must be last argument)'
complete -c alacritty -l config-file -d 'Specify alternative configuration file  Alacritty looks for the configuration…'
complete -c alacritty -l embed -d 'Defines the X11 window ID (as a decimal integer) to embed Alacritty within'
complete -c alacritty -s o -l option -d 'Override configuration file options [example: cursor. style=Beam]'
complete -c alacritty -s t -l title -d 'Defines the window title [default: Alacritty]'

