# alsa_in
# Autogenerated from man page /usr/share/man/man1/alsa_in.1.gz
complete -c alsa_in -s j -d 'br Set Client Name'
complete -c alsa_in -s d -d 'br Use this Soundcard'
complete -c alsa_in -s v -d 'br Verbose, prints out resample coefficient and other parameters useful for d…'
complete -c alsa_in -s i -d 'br Instrumentation'
complete -c alsa_in -s c -d 'br Set Number of channels'
complete -c alsa_in -s r -d 'br Set sample_rate.  The program resamples as necessary'
complete -c alsa_in -s p -d 'br Set the period size.  It is not related to the jackd period_size'
complete -c alsa_in -s n -d 'br Set number of periods.  See note for period_size'
complete -c alsa_in -s q -d 'br Set the quality of the resampler from 0 to 4'
complete -c alsa_in -s m -d 'br The value when a soft xrun occurs'
complete -c alsa_in -s t -d 'br The delay alsa_io should try to approach.  Same as for max_diff'
complete -c alsa_in -s s -d 'br This parameter controls the size of the array used for smoothing the delay…'
complete -c alsa_in -s C -d 'br If you have a PCI card, then the default value (15) of this parameter is t…'
complete -c alsa_in -s S

