# atmarp
# Autogenerated from man page /usr/share/man/man8/atmarp.8.gz
complete -c atmarp -s a -d 'list the current ATMARP table'
complete -c atmarp -s c -d 'create the specified IP interface'
complete -c atmarp -s q -d 'sets the QOS and the send buffer size to use as the default for all VCs gener…'
complete -c atmarp -s s -d 'set up a PVC or create an SVC entry.  The following options are recognized: '
complete -c atmarp -s d -d 'delete the specified ARP entry'
complete -c atmarp -s V -d 'print the version number of atmarp on standard output and exit'

