# atmdump
# Autogenerated from man page /usr/share/man/man8/atmdump.8.gz
complete -c atmdump -s i -d 'displays timestamps as the interval since the last cell reception'
complete -c atmdump -o ttype -d 'selects transmit mode and specifies the payload type'
complete -c atmdump -o ggfc -d 'specifies the value of the GFC field'
complete -c atmdump -s t -d 'selects transmit mode and specifies the payload type'
complete -c atmdump -s g -d 'specifies the value of the GFC field'
complete -c atmdump -s c -d 'sets the cell loss priority flag, indicating low priority'

