# atmloop
# Autogenerated from man page /usr/share/man/man8/atmloop.8.gz
complete -c atmloop -s s -d 'set loopback mode'
complete -c atmloop -o llevel -d 'enable local loopback'
complete -c atmloop -o rlevel -d 'enable remote loopback'
complete -c atmloop -o qlevel -d 'query loopback levels supported by the interface'
complete -c atmloop -s l -d 'enable local loopback'
complete -c atmloop -s r -d 'enable remote loopback'
complete -c atmloop -s q -d 'query loopback levels supported by the interface'
complete -c atmloop -s V -d 'print version number of atmloop on standard output and exit'

