# conky
# Autogenerated from man page /usr/share/man/man1/conky.1.gz
complete -c conky -l alignment -d 'Text alignment on screen, {top,bottom,middle}_{left,right,middle} or none'
complete -c conky -l config -d 'Config file to load instead of \\*(T<~/. config/conky/conky. conf\\*(T>'
complete -c conky -l font -d 'Font to use.  Only available with build flag BUILD_X11 enabled'
complete -c conky -l pause -d 'Time to pause/wait before actually starting Conky'
complete -c conky -l text -d 'Text to render, remember single quotes, like -t \' $uptime \''
complete -c conky -l interval -d 'Update interval'
complete -c conky -s V -d 'Prints version, build information and general info.  Exits after printing'
complete -c conky -l window-id -d 'Window id to draw.  Only available with build flag BUILD_X11 enabled'
complete -c conky -l display -d 'X11 display to use.  Only available with build flag BUILD_X11 enabled'
complete -c conky -s t
complete -c conky -l -------------------------------------------------------------------- -d 'USAGE: conky -t \'${sip_status}\' # print SIP status conky -t \'${sip_status 0}\'…'

