# cups-genppd
# Autogenerated from man page /usr/share/man/man8/cups-genppd.8.gz
complete -c cups-genppd -s c -d 'use localedir as the base directory for locale data'
complete -c cups-genppd -s l -d 'output PPDs translated with messages for locale'
complete -c cups-genppd -s p -d 'output PPDs in directory prefix.   Directories are not recursively created'
complete -c cups-genppd -s q -d 'Quiet mode'
complete -c cups-genppd -s v -d 'Verbose mode'
complete -c cups-genppd -s h -d 'show a help message'
complete -c cups-genppd -s L -d 'list available translations (message catalogs)'
complete -c cups-genppd -s M -d 'list available printer models'
complete -c cups-genppd -s V -d 'show version information and defaults The default behavior is to output PPDs …'

