# ddns-confgen
# Autogenerated from man page /usr/share/man/man8/ddns-confgen.8.gz
complete -c ddns-confgen -s a -d 'This option specifies the algorithm to use for the TSIG key'
complete -c ddns-confgen -s h -d 'This option prints a short summary of options and arguments'
complete -c ddns-confgen -s k -d 'This option specifies the key name of the DDNS authentication key'
complete -c ddns-confgen -s q -d 'This option enables quiet mode, which prints only the key, with no explanator…'
complete -c ddns-confgen -s s -d 'This option generates a configuration example to allow dynamic updates of a s…'
complete -c ddns-confgen -s z -d 'This option generates a configuration example to allow dynamic updates of a z…'

