# debugfs
# Autogenerated from man page /usr/share/man/man8/debugfs.reiserfs.8.gz
complete -c debugfs -s j -d 'prints the contents of the journal'
complete -c debugfs -s J -d 'prints the journal header'
complete -c debugfs -s m -d 'prints the contents of the bitmap (slightly useful)'
complete -c debugfs -s B -d 'takes the list of bad blocks stored in the internal ReiserFS tree and transla…'
complete -c debugfs -s 1 -d 'prints the specified block of the filesystem'
complete -c debugfs -s u -d 'builds the ReiserFS filesystem image with gunzip -c xxx'
complete -c debugfs -s q -d 'When '

