# defrag
# Autogenerated from man page /usr/share/man/man8/defrag.f2fs.8.gz
complete -c defrag -s s -d 'Specify the starting block address'
complete -c defrag -s l -d 'Specifiy the number of blocks to move'
complete -c defrag -s t -d 'Specify the destination block address'
complete -c defrag -s i -d 'Set the direction to left'
complete -c defrag -s d -d 'Specify the level of debugging options'

