# dex
# Autogenerated from man page /usr/share/man/man1/dex.1.gz
complete -c dex -s h -l help -d 'Show this help message and exit'
complete -c dex -s a -l autostart -d 'Autostart programs'
complete -c dex -s c -l create -d 'Create a DesktopEntry file for the program at the given path'
complete -c dex -s d -l dry-run -d 'Dry run, don\\(aqt execute any command'
complete -c dex -s e -l environment -d 'Specify the Desktop Environment an autostart should be performed for; works o…'
complete -c dex -s s -l search-paths -d 'Colon separated list of paths to search for desktop files, overriding the def…'
complete -c dex -s t -l target-directory -d 'Create files in target directory'
complete -c dex -l term -d 'The terminal emulator that will be used to run the program if Terminal=true i…'
complete -c dex -s w -l wait -d 'Block until the program exits'
complete -c dex -l test -d 'Perform a self-test'
complete -c dex -s v -l verbose -d 'Verbose output'
complete -c dex -s V -l version -d 'Display version information'

