# dmenu
# Autogenerated from man page /usr/share/man/man1/dmenu.1.gz
complete -c dmenu -s b -d 'dmenu appears at the bottom of the screen'
complete -c dmenu -s f -d 'dmenu grabs the keyboard before reading stdin if not reading from a tty'
complete -c dmenu -s i -d 'dmenu matches menu items case insensitively'
complete -c dmenu -s l -d 'dmenu lists items vertically, with the given number of lines'
complete -c dmenu -s m -d 'dmenu is displayed on the monitor number supplied'
complete -c dmenu -s p -d 'defines the prompt to be displayed to the left of the input field'
complete -c dmenu -o fn -d 'defines the font or font set used'
complete -c dmenu -o nb -d 'defines the normal background color'
complete -c dmenu -o nf -d 'defines the normal foreground color'
complete -c dmenu -o sb -d 'defines the selected background color'
complete -c dmenu -o sf -d 'defines the selected foreground color'
complete -c dmenu -s v -d 'prints version information to stdout, then exits'
complete -c dmenu -s w -d 'embed into windowid.  USAGE dmenu is completely controlled by the keyboard'

