# dnssec-dsfromkey
# Autogenerated from man page /usr/share/man/man8/dnssec-dsfromkey.8.gz
complete -c dnssec-dsfromkey -s 1 -d 'This option is an abbreviation for -a SHA1'
complete -c dnssec-dsfromkey -s 2 -d 'This option is an abbreviation for -a SHA-256'
complete -c dnssec-dsfromkey -s a -d 'This option specifies a digest algorithm to use when converting DNSKEY record…'
complete -c dnssec-dsfromkey -s A -d 'This option indicates that ZSKs are to be included when generating DS records'
complete -c dnssec-dsfromkey -s c -d 'This option specifies the DNS class; the default is IN'
complete -c dnssec-dsfromkey -s C -d 'This option generates CDS records rather than DS records'
complete -c dnssec-dsfromkey -s f -d 'This option sets zone file mode, in which the final dnsname argument of dnsse…'
complete -c dnssec-dsfromkey -s h -d 'This option prints usage information'
complete -c dnssec-dsfromkey -s K -d 'This option tells BIND 9 to look for key files or keyset- files in directory'
complete -c dnssec-dsfromkey -s s -d 'This option enables keyset mode, in which the final dnsname argument from dns…'
complete -c dnssec-dsfromkey -s T -d 'This option specifies the TTL of the DS records'
complete -c dnssec-dsfromkey -s v -d 'This option sets the debugging level'
complete -c dnssec-dsfromkey -s V -d 'This option prints version information'

