# dnssec-importkey
# Autogenerated from man page /usr/share/man/man8/dnssec-importkey.8.gz
complete -c dnssec-importkey -s f -d 'This option indicates the zone file mode'
complete -c dnssec-importkey -s K -d 'This option sets the directory in which the key files are to reside'
complete -c dnssec-importkey -s L -d 'This option sets the default TTL to use for this key when it is converted int…'
complete -c dnssec-importkey -s h -d 'This option emits a usage message and exits'
complete -c dnssec-importkey -s v -d 'This option sets the debugging level'
complete -c dnssec-importkey -s V -d 'This option prints version information'
complete -c dnssec-importkey -s P -d 'This option sets the date on which a key is to be published to the zone'
complete -c dnssec-importkey -s D -d 'This option sets the date on which the key is to be deleted'

