# dnssec-keymgr
# Autogenerated from man page /usr/share/man/man8/dnssec-keymgr.8.gz
complete -c dnssec-keymgr -s c -d 'If -c is specified, then the DNSSEC policy is read from file'
complete -c dnssec-keymgr -s f -d 'Force: allow updating of key events even if they are already in the past'
complete -c dnssec-keymgr -s g -d 'Specifies a path to a dnssec-keygen binary.  Used for testing'
complete -c dnssec-keymgr -s h -d 'Print the dnssec-keymgr help summary and exit'
complete -c dnssec-keymgr -s K -d 'Sets the directory in which keys can be found'
complete -c dnssec-keymgr -s k -d 'Only apply policies to KSK keys.  See also the -z option'
complete -c dnssec-keymgr -s q -d 'Quiet: suppress printing of dnssec-keygen and dnssec-settime'
complete -c dnssec-keymgr -s s -d 'Specifies a path to a dnssec-settime binary.  Used for testing'
complete -c dnssec-keymgr -s v -d 'Print the dnssec-keymgr version and exit'
complete -c dnssec-keymgr -s z -d 'Only apply policies to ZSK keys.  See also the -k option'

