# downgrade
# Autogenerated from man page /usr/share/man/man8/downgrade.8.gz
complete -c downgrade -l pacman -d 'Pacman command, default is pacman'
complete -c downgrade -l pacman-conf -d 'Pacman configuration file, default is /etc/pacman. conf'
complete -c downgrade -l pacman-cache -d 'Pacman cache directory, default value(s) taken from pacman configuration file…'
complete -c downgrade -l pacman-log -d 'Pacman log file, default value is extracted from pacman configuration file, o…'
complete -c downgrade -l maxdepth -d 'Maximum depth to search for cached packages, defaults to 1'
complete -c downgrade -l ala-url -d 'Location of an ALA server, default is https://archive. archlinux. org'
complete -c downgrade -l ala-only -d 'Search ALA only'
complete -c downgrade -l cached-only -d 'Search local cache only'
complete -c downgrade -l version -d 'Show downgrade version'
complete -c downgrade -s h -l help -d 'Show help script'

