# ecryptfs-verify
# Autogenerated from man page /usr/share/man/man1/ecryptfs-verify.1.gz
complete -c ecryptfs-verify -s h -l home -d 'True if HOME is correctly configured for encryption, False otherwise'
complete -c ecryptfs-verify -s p -l private -d 'True if a non-HOME directory is correctly configured for encryption, False ot…'
complete -c ecryptfs-verify -s e -l filenames-encrypted -d 'True if filenames are set for encryption, False otherwise'
complete -c ecryptfs-verify -s n -l filenames-not-encrypted -d 'True if filenames are not encrypted, False otherwise'
complete -c ecryptfs-verify -s u -l user -d 'By default, the current user\'s configuration is checked, override with this o…'
complete -c ecryptfs-verify -l help -d 'This usage information'

