# fatresize
# Autogenerated from man page /usr/share/man/man1/fatresize.1.gz
complete -c fatresize -s h -l help -d 'Show summary of options'
complete -c fatresize -s s -l size -d 'Resize volume to SIZE[k|M|G|ki|Mi|Gi] bytes or "max"'
complete -c fatresize -s i -l info -d 'Show volume information'
complete -c fatresize -s p -l progress -d 'Show progress'
complete -c fatresize -s q -l quiet -d 'Be quiet'

