# fido2-cred
# Autogenerated from man page /usr/share/man/man1/fido2-cred.1.gz
complete -c fido2-cred -s M -d 'Tells fido2-cred to make a new credential on device'
complete -c fido2-cred -s V -d 'Tells fido2-cred to verify a credential'
complete -c fido2-cred -s b -d 'Request the credential\'s largeBlobKey, a 32-byte symmetric key associated wit…'
complete -c fido2-cred -s c -d 'If making a credential, set the credential\'s protection level to cred_protect…'
complete -c fido2-cred -s d -d 'Causes fido2-cred to emit debugging output on stderr'
complete -c fido2-cred -s h -d 'If making a credential, enable the FIDO2 hmac-secret extension'
complete -c fido2-cred -s i -d 'Tells fido2-cred to read the parameters of the credential from input_file ins…'
complete -c fido2-cred -s o -d 'Tells fido2-cred to write output on output_file instead of stdout'
complete -c fido2-cred -s q -d 'Tells fido2-cred to be quiet'
complete -c fido2-cred -s r -d 'Create a resident credential'
complete -c fido2-cred -s u -d 'Create a U2F credential'
complete -c fido2-cred -s v -d 'If making a credential, request user verification'

