# genfstab
# Autogenerated from man page /usr/share/man/man8/genfstab.8.gz
complete -c genfstab -s f -d 'Restrict output to mountpoints matching the prefix filter'
complete -c genfstab -s L -d 'Use labels for source identifiers (shortcut for -t LABEL)'
complete -c genfstab -s p -d 'Exclude pseudofs mounts (default behavior)'
complete -c genfstab -s P -d 'Include pseudofs mounts'
complete -c genfstab -s t -d 'Use tag for source identifiers (should be one of: LABEL, UUID, PARTLABEL, PAR…'
complete -c genfstab -s U -d 'Use UUIDs for source identifiers (shortcut for -t UUID)'
complete -c genfstab -s h -d 'Output syntax and command line options'

