# getcifsacl
# Autogenerated from man page /usr/share/man/man1/getcifsacl.1.gz
complete -c getcifsacl -s v -d 'Print version number and exit'
complete -c getcifsacl -s r -d 'Display a security descriptor in raw mode'
complete -c getcifsacl -s R -d 'List the ACLs of all files and directories recursively'

