# gethostip
# Autogenerated from man page /usr/share/man/man1/gethostip.1.gz
complete -c gethostip -s d -d 'Output the IP address in decimal format'
complete -c gethostip -s x -d 'Output the IP address in hexadecimal format'
complete -c gethostip -s n -d 'Output the host\'s canonical name'

