# gksu
# Autogenerated from man page /usr/share/man/man1/gksu.1.gz
complete -c gksu -l debug -s d -d 'Print information on the screen that might be useful for diagnosing and/or so…'
complete -c gksu -l user -s u -d 'Call <command> as the specified user'
complete -c gksu -l disable-grab -s g -d 'Disable the "locking" of the keyboard, mouse, and focus done by the program w…'
complete -c gksu -l prompt -s P -d 'Ask the user if they want to have their keyboard and mouse grabbed before doi…'
complete -c gksu -l preserve-env -s k -d 'Preserve the current environments, does not set $HOME nor $PATH, for example'
complete -c gksu -l login -s l -d 'Make this a login shell'
complete -c gksu -l description -s D -d 'Provide a descriptive name for the command to be used in the default message,…'
complete -c gksu -l message -s m -d 'Replace the standard message shown to ask for password for the argument passe…'
complete -c gksu -l print-pass -s p -d 'Ask gksu to print the password to stdout, just like ssh-askpass'
complete -c gksu -l su-mode -s w -d 'Force gksu to use su(1) as its backend for running the programs'
complete -c gksu -l sudo-mode -s S -d 'Force gksu to use sudo(1) as its backend for running the programs'

