# gsettings-data-convert
# Autogenerated from man page /usr/share/man/man1/gsettings-data-convert.1.gz
complete -c gsettings-data-convert -s h -l help
complete -c gsettings-data-convert -l dry-run
complete -c gsettings-data-convert -l verbose

