# gsettings-schema-convert
# Autogenerated from man page /usr/share/man/man1/gsettings-schema-convert.1.gz
complete -c gsettings-schema-convert -s h -l help
complete -c gsettings-schema-convert -s o -l output
complete -c gsettings-schema-convert -s f -l force
complete -c gsettings-schema-convert -s g -l gconf
complete -c gsettings-schema-convert -s s -l simple
complete -c gsettings-schema-convert -s x -l xml
complete -c gsettings-schema-convert -s i -l schema-id
complete -c gsettings-schema-convert -s d -l gettext-domain
complete -c gsettings-schema-convert -s u -l keep-underscores

