# gssproxy
# Autogenerated from man page /usr/share/man/man8/gssproxy.8.gz
complete -c gssproxy -s D -l daemon -d 'Become a daemon after starting up'
complete -c gssproxy -s c -l config -d 'Specify a config file to use as the main config file (read before the rest of…'
complete -c gssproxy -s C -l configdir -d 'Specify a non-default config dir.  Files named of the form "##-foo'
complete -c gssproxy -s d -l debug -d 'Turn on debugging.  This option is identical to --debug-level=1'
complete -c gssproxy -l debug-level -d 'Turn on debugging at the specified level'
complete -c gssproxy -s i -l interactive -d 'Run in the foreground, don\\*(Aqt become a daemon'
complete -c gssproxy -s s -l socket -d 'Specify a custom default socket name'
complete -c gssproxy -l syslog-status -d 'Enable additional logging to syslog'
complete -c gssproxy -l version -d 'Print version number and exit'

