# hardinfo
# Autogenerated from man page /usr/share/man/man1/hardinfo.1.gz
complete -c hardinfo -s h -l help -d 'Show help options'
complete -c hardinfo -s r -l generate-report -d 'creates a report and prints to standard output'
complete -c hardinfo -s f -l report-format -d 'chooses a report format (text, html)'
complete -c hardinfo -s b -l run-benchmark -d 'run benchmark; requires benchmark. so to be loaded'
complete -c hardinfo -s l -l list-modules -d 'lists modules'
complete -c hardinfo -s m -l load-module -d 'specify module to load'
complete -c hardinfo -s a -l autoload-deps -d 'automatically load module dependencies'
complete -c hardinfo -s v -l version -d 'shows program version and quit AUTHORS/CONTRIBUTORS For current maintainers c…'

