# i3-input
# Autogenerated from man page /usr/share/man/man1/i3-input.1.gz
complete -c i3-input -s s -d 'Specify the path to the i3 IPC socket (it should not be necessary to use this…'
complete -c i3-input -s F -d 'Every occurrence of "%s" in the <format> string is replaced by the user input…'
complete -c i3-input -s l -d 'Set the maximum allowed length of the user input to <limit> characters'
complete -c i3-input -s P -d 'Display the <prompt> string in front of user input text field'
complete -c i3-input -s f -d 'Use the specified X11 core font (use xfontsel to chose a font)'
complete -c i3-input -s v -d 'Show version and exit'

