# irssi
# Autogenerated from man page /usr/share/man/man1/irssi.1.gz
complete -c irssi -l config -d 'use   FILE instead of ~/. irssi/config'
complete -c irssi -l home -d 'PATH  specifies the home directory of Irssi; default is   ~/. irssi'
complete -c irssi -s c -l connect -d 'connect to   SERVER'
complete -c irssi -s w -l password -d 'use  PASSWORD  for authentication'
complete -c irssi -s p -l port -d 'automatically connect to   PORT  on server'
complete -c irssi -l noconnect -d 'disable autoconnecting of servers'
complete -c irssi -s n -l nick -d 'specify   NICKNAME  as your nick'
complete -c irssi -s h -l hostname -d 'use  HOSTNAME for your irc session'
complete -c irssi -s v -l version -d 'display the version of Irssi'
complete -c irssi -s '?' -l help -d 'show a help message SEE ALSO Irssi has a solid amount of documentation availa…'

