# jack_load
# Autogenerated from man page /usr/share/man/man1/jack_load.1.gz
complete -c jack_load -s i -l init -d 'br initialization string passed to the in-process client'
complete -c jack_load -s s -l server -d 'br Name of JACK server to connect to'
complete -c jack_load -s w -l wait -d 'Wait for a signal (eg.  from Ctrl-c) and then unload the client'

