# katalyzer
# Autogenerated from man page /usr/share/man/man1/katalyzer.1.gz
complete -c katalyzer -s h -d 'Show command line help'
complete -c katalyzer -s V -d 'Show version information'
complete -c katalyzer -s l -d 'Select the types of information to log, from the list below'

