# kateenc
# Autogenerated from man page /usr/share/man/man1/kateenc.1.gz
complete -c kateenc -s h -d 'Show command line help'
complete -c kateenc -s V -d 'Show version information'
complete -c kateenc -s M -d 'Allow simple HTML-like markup in SRT files'
complete -c kateenc -s o -d 'Write the output Kate stream to the given file name (writes to stdout if not …'
complete -c kateenc -s l -d 'Sets the language for the stream (default is the language specified in the in…'
complete -c kateenc -s c -d 'Sets the category for the stream (default is the category specified in the in…'
complete -c kateenc -s s -d 'Sets the serial number for the output Kate stream (does not apply to raw stre…'
complete -c kateenc -s C -d 'Adds a comment to encode into the output Kate stream'
complete -c kateenc -s t -d 'Specifies the type of the input (srt, lrc, kate)'
complete -c kateenc -s R -d 'Use repeat packets, with the given threshold (in seconds)'
complete -c kateenc -s K -d 'Use keepalive packets, with the given threshold (in seconds)'

