# katedec
# Autogenerated from man page /usr/share/man/man1/katedec.1.gz
complete -c katedec -s h -d 'Show command line help'
complete -c katedec -s V -d 'Show version information'
complete -c katedec -s v -d 'Increase verbosity'
complete -c katedec -s o -d 'Write the output description file to the given file name (writes to stdout if…'
complete -c katedec -s t -d 'Set the output format type:     kate: Kate description format     srt: SubRip…'

