# lavtrans
# Autogenerated from man page /usr/share/man/man1/lavtrans.1.gz
complete -c lavtrans -s f -d 'Specifies the output format that should be saved'
complete -c lavtrans -s i -d 'Convert a single frame to a JPEG file'
complete -c lavtrans -s o -d 'Specifies the name of the output file If you want as output single JPEG image…'

