# ldbedit
# Autogenerated from man page /usr/share/man/man1/ldbedit.1.gz
complete -c ldbedit -s '?' -l help -d 'Show list of available options, and a phrase describing what that option does'
complete -c ldbedit -l usage -d 'Show list of available options'
complete -c ldbedit -s H -d 'LDB URL to connect to'
complete -c ldbedit -s s -d 'Search scope to use.  One-level, subtree or base'
complete -c ldbedit -s a -o all -d 'Edit all records'
complete -c ldbedit -s e -l editor -d 'Specify the editor that should be used (overrides the VISUAL and EDITOR envir…'
complete -c ldbedit -s b -d 'Specify Base Distinguished Name to use'
complete -c ldbedit -s v -l verbose -d 'Make ldbedit more verbose about the operations that are being performed'

