# ldns-verify-zone
# Autogenerated from man page /usr/share/man/man1/ldns-verify-zone.1.gz
complete -c ldns-verify-zone -s h -d 'Show usage and exit'
complete -c ldns-verify-zone -s a -d 'Apex only, check only the zone apex'
complete -c ldns-verify-zone -s e -d 'Signatures may not expire within this period.  Default no period is used'
complete -c ldns-verify-zone -s i -d 'Signatures must have been valid at least this long'
complete -c ldns-verify-zone -s k -d 'A file that contains a trusted DNSKEY or DS rr'
complete -c ldns-verify-zone -s p -d 'Only check this percentage of the zone'
complete -c ldns-verify-zone -s S -d 'Chase signature(s) to a known key'
complete -c ldns-verify-zone -s t -o ']offset' -d 'Set the validation time either by an absolute time value or as an offset in s…'
complete -c ldns-verify-zone -s v -d 'Show the version and exit'
complete -c ldns-verify-zone -s V -d 'Set the verbosity level (default 3):'

