# lou_translate
# Autogenerated from man page /usr/share/man/man1/lou_translate.1.gz
complete -c lou_translate -s h -l help -d 'display this help and exit'
complete -c lou_translate -s v -l version -d 'display version information and exit'
complete -c lou_translate -s f -l forward -d 'forward translation using the given table'
complete -c lou_translate -s b -l backward -d 'backward translation using the given table If neither -f nor -b are specified…'

