# lou_debug
# Autogenerated from man page /usr/share/man/man1/lou_debug.1.gz
complete -c lou_debug -s h -l help -d 'display this help and exit'
complete -c lou_debug -s v -l version -d 'display version information and exit AUTHOR Written by John J.  Boyer'

