# lsb_release
# Autogenerated from man page /usr/share/man/man1/lsb_release.1.gz
complete -c lsb_release -s v -l version -d 'Display the version of the LSB specification against which the distribution i…'
complete -c lsb_release -s i -l id -d 'Display the string id of the distributor'
complete -c lsb_release -s d -l description -d 'Display the single line text description of the distribution'
complete -c lsb_release -s r -l release -d 'Display the release number of the distribution'
complete -c lsb_release -s c -l codename -d 'Display the codename according to the distribution release'
complete -c lsb_release -s a -l all -d 'Display all of the above information'
complete -c lsb_release -s s -l short -d 'Display all of the above information in short output format'
complete -c lsb_release -s h -l help -d 'Display this message.  FILES'

