# lssu
# Autogenerated from man page /usr/share/man/man1/lssu.1.gz
complete -c lssu -s a -l all -d 'Do not hide clean segments'
complete -c lssu -s h -l help -d 'Display help message and exit'
complete -c lssu -s i -l index -d 'Skip index segments at start of input'
complete -c lssu -s l -l latest-usage -d 'Print usage status of the moment'
complete -c lssu -s n -l lines -d 'List only lines input segments'
complete -c lssu -s p -l protection-period -d 'Specify protection period'
complete -c lssu -s V -l version -d 'Display version and exit'

