# lua5
# Autogenerated from man page /usr/share/man/man1/lua5.1.1.gz
complete -c lua5 -s e -d 'execute statement R stat '
complete -c lua5 -s i -d 'enter interactive mode after  script is executed'
complete -c lua5 -s l -d 'call  require(\' name \') before executing R script '
complete -c lua5 -s v -d 'is assumed when the standard input is a terminal; otherwise,'

