# mcedit
# Autogenerated from man page /usr/share/man/man1/mcedit.1.gz
complete -c mcedit -s b -d 'Force black and white display'
complete -c mcedit -s c -d 'Force ANSI color mode on terminals that don\'t seem to have color support'
complete -c mcedit -s C -d 'Specify a different color set'
complete -c mcedit -s d -d 'Disable mouse support'
complete -c mcedit -s f -d 'Display the compiled-in search path for GNU Midnight Commander data files'
complete -c mcedit -s t -d 'Force using termcap database instead of terminfo'
complete -c mcedit -s V -d 'Display the version of the program'
complete -c mcedit -s x -d 'Force xterm mode'

