# mdb_stat
# Autogenerated from man page /usr/share/man/man1/mdb_stat.1.gz
complete -c mdb_stat -s V -d 'Write the library version number to the standard output, and exit'
complete -c mdb_stat -s e -d 'Display information about the database environment'
complete -c mdb_stat -s f -d 'Display information about the environment freelist'
complete -c mdb_stat -s n -d 'Display the status of an LMDB database which does not use subdirectories'
complete -c mdb_stat -s r -d 'Display information about the environment reader table'
complete -c mdb_stat -s a -d 'Display the status of all of the subdatabases in the environment'
complete -c mdb_stat -s s -d 'Display the status of a specific subdatabase'

