# mkcp
# Autogenerated from man page /usr/share/man/man8/mkcp.8.gz
complete -c mkcp -s s -l snapshot -d 'Create a snapshot'
complete -c mkcp -s p -l print -d 'Print the checkpoint number when successfully created'
complete -c mkcp -s h -l help -d 'Display help message and exit'
complete -c mkcp -s V -l version -d 'Display version and exit'

