# mpeg2enc
# Autogenerated from man page /usr/share/man/man1/mpeg2enc.1.gz
complete -c mpeg2enc -s f -l format -d '        -       Generic MPEG1'
complete -c mpeg2enc -s T -d 'stills (352 wide) and 120KB for high resolution stills (704 wide)'
complete -c mpeg2enc -s v -l verbose
complete -c mpeg2enc -s K -l custom-quant-matrices -d ' default | hi-res | file=inputfile | help'
complete -c mpeg2enc -s E -l unit-coeff-elim -o '40..40'
complete -c mpeg2enc -s R -l b-per-refframe
complete -c mpeg2enc -s '?' -l help
complete -c mpeg2enc -s b -l video-bitrate
complete -c mpeg2enc -s q -d 'maximum bitrate of the stream'
complete -c mpeg2enc -s A -l ratecontroller
complete -c mpeg2enc -s V -l video-buffer
complete -c mpeg2enc -l target-still-size
complete -c mpeg2enc -s s -l sequence-header-every-gop
complete -c mpeg2enc -s d -l no-dummy-svcd-SOF
complete -c mpeg2enc -l correct-svcd-hds
complete -c mpeg2enc -l no-constraints
complete -c mpeg2enc -s l -l level
complete -c mpeg2enc -l no-altscan-mpeg2
complete -c mpeg2enc -l dualprime-mpeg2
complete -c mpeg2enc -s z -l playback-field-order
complete -c mpeg2enc -s n -l video-norm
complete -c mpeg2enc -s F -l frame-rate
complete -c mpeg2enc -s a -l aspect
complete -c mpeg2enc -s x -l display-hsize
complete -c mpeg2enc -s y -l display-vsize
complete -c mpeg2enc -s p -l 3-2-pulldown
complete -c mpeg2enc -s M -l multi-thread
complete -c mpeg2enc -l quantisation
complete -c mpeg2enc -s I -l interlace-mode
complete -c mpeg2enc -s g -l min-gop-size
complete -c mpeg2enc -s G -l max-gop-size
complete -c mpeg2enc -s c -l closed-GOPs
complete -c mpeg2enc -s P -l force-b-b-p
complete -c mpeg2enc -s Q -l quantisation-reduction -o '4.0..5.0'
complete -c mpeg2enc -s X -l quant-reduction-max-var
complete -c mpeg2enc -s r -l motion-search-radius
complete -c mpeg2enc -s 4 -l reduction-4x4
complete -c mpeg2enc -s 2 -l reduction-2x2
complete -c mpeg2enc -s N -l reduce-hf
complete -c mpeg2enc -s H -l keep-hf
complete -c mpeg2enc -s D -l intra_dc_prec
complete -c mpeg2enc -s S -l sequence-length
complete -c mpeg2enc -s B -l nonvideo-bitrate
complete -c mpeg2enc -s u -l cbr
complete -c mpeg2enc -l chapters

