# mpicc
# Autogenerated from man page /usr/share/man/man1/mpicc.1.gz
complete -c mpicc -l showme -d 'This option comes in several different variants (see below)'
complete -c mpicc -l showme:compile -d 'Output the compiler flags that would have been supplied to the C compiler'
complete -c mpicc -l showme:link -d 'Output the linker flags that would have been supplied to the C compiler'
complete -c mpicc -l showme:command -d 'Outputs the underlying C compiler command (which may be one or more tokens)'
complete -c mpicc -l showme:incdirs -d 'Outputs a space-delimited (but otherwise undecorated) list of directories tha…'
complete -c mpicc -l showme:libdirs -d 'Outputs a space-delimited (but otherwise undecorated) list of directories tha…'
complete -c mpicc -l showme:libs -d 'Outputs a space-delimited (but otherwise undecorated) list of library names t…'
complete -c mpicc -l showme:version -d 'Outputs the version number of Open MPI'
complete -c mpicc -l showme:help -d 'Output a brief usage help message'
complete -c mpicc -o qfixed -d 'may be necessary to compile fixed-format Fortran source files'
complete -c mpicc -o m64 -d 'build, but can be activated (for example, in a binary package providing both …'

