# mpifort
# Autogenerated from man page /usr/share/man/man1/mpifort.1.gz
complete -c mpifort -l showme -d 'This option comes in several different variants (see below)'
complete -c mpifort -l showme:compile -d 'Output the compiler flags that would have been supplied to the Fortran compil…'
complete -c mpifort -l showme:link -d 'Output the linker flags that would have been supplied to the Fortran compiler'
complete -c mpifort -l showme:command -d 'Outputs the underlying Fortran compiler command (which may be one or more tok…'
complete -c mpifort -l showme:incdirs -d 'Outputs a space-delimited (but otherwise undecorated) list of directories tha…'
complete -c mpifort -l showme:libdirs -d 'Outputs a space-delimited (but otherwise undecorated) list of directories tha…'
complete -c mpifort -l showme:libs -d 'Outputs a space-delimited (but otherwise undecorated) list of library names t…'
complete -c mpifort -l showme:version -d 'Outputs the version number of Open MPI'
complete -c mpifort -l showme:help -d 'Output a brief usage help message'
complete -c mpifort -o qfixed -d 'may be necessary to compile fixed-format Fortran source files'
complete -c mpifort -o m64 -d 'build, but can be activated (for example, in a binary package providing both …'

