# named-rrchecker
# Autogenerated from man page /usr/share/man/man1/named-rrchecker.1.gz
complete -c named-rrchecker -s h -d 'This option prints out the help menu'
complete -c named-rrchecker -s o -d 'This option specifies the origin to be used when interpreting the record'
complete -c named-rrchecker -s p -d 'This option prints out the resulting record in canonical form'
complete -c named-rrchecker -s u -d 'This option prints out the resulting record in unknown record form'
complete -c named-rrchecker -s C -s T -s P -d 'These options print out the known class, standard type, and private type mnem…'

