# natspec
# Autogenerated from man page /usr/share/man/man1/natspec.1.gz
complete -c natspec -s c -l codepage -d 'Print DOS codepage for current locale'
complete -c natspec -s f -l fsenc -d 'Print filename encoding for current locale'
complete -c natspec -l utf8 -d 'Return 0 if current locale uses UTF-8'
complete -c natspec -l country-id -d 'Print country ID for DOS'
complete -c natspec -l system-locale -d 'Print system locale'
complete -c natspec -s i -l info -d 'Print summary information about current locale'
complete -c natspec -s a -l transl -d 'Transliterate ARGS from encoding to the current encoding and print the result'
complete -c natspec -s v -l verbose -d 'Be verbose'
complete -c natspec -s s -l charset -d 'Print charset for the operating system'
complete -c natspec -s h -l help -d 'Show summary of options'
complete -c natspec -s V -l version -d 'Show version of program'

