# nfsdclddb
# Autogenerated from man page /usr/share/man/man8/nfsdclddb.8.gz
complete -c nfsdclddb -s h -l help -d 'Show the help message and exit'
complete -c nfsdclddb -s p -l path -d 'Open the sqlite database located at  dbpath instead of R /var/lib/nfs/nfsdcld…'
complete -c nfsdclddb -s v -l version -d 'The schema version to downgrade to'
complete -c nfsdclddb -s s -l summary -d 'option is not given, also prints the clients in the reboot epoch tables'

