# nfsdclnts
# Autogenerated from man page /usr/share/man/man8/nfsdclnts.8.gz
complete -c nfsdclnts -s t -l type
complete -c nfsdclnts -l clientinfo
complete -c nfsdclnts -l hostname
complete -c nfsdclnts -s q -l quiet
complete -c nfsdclnts -s v -l verbose
complete -c nfsdclnts -s f -l file
complete -c nfsdclnts -s h -l help

