# nilfs-clean
# Autogenerated from man page /usr/share/man/man8/nilfs-clean.8.gz
complete -c nilfs-clean -s b -l break -l stop -d 'Stop garbage collection'
complete -c nilfs-clean -s c -l reload -d 'Request reloading config file to cleaner process'
complete -c nilfs-clean -s l -l status -d 'Display cleaner status'
complete -c nilfs-clean -s h -l help -d 'Display help message and exit'
complete -c nilfs-clean -s m -l min-reclaimable-blocks -d 'Specify the minimum number of reclaimable blocks in a segment before it can b…'
complete -c nilfs-clean -s p -l protection-period -d 'Set protection period for a cleaner run'
complete -c nilfs-clean -s q -l quit -d 'Shutdown cleaner daemon'
complete -c nilfs-clean -s r -l resume -d 'Resume garbage collection'
complete -c nilfs-clean -s s -l suspend -d 'Suspend garbage collection'
complete -c nilfs-clean -s S -l speed -d 'Set garbage collection speed for a cleaner run'
complete -c nilfs-clean -s v -l verbose -d 'Verbose mode'
complete -c nilfs-clean -s V -l version -d 'Display version and exit.  AUTHOR Ryusuke Konishi <konishi. ryusuke@gmail'

