# nilfs_cleanerd
# Autogenerated from man page /usr/share/man/man8/nilfs_cleanerd.8.gz
complete -c nilfs_cleanerd -s V -l version -d 'Display version and exit'
complete -c nilfs_cleanerd -s h -l help -d 'Display help message and exit'
complete -c nilfs_cleanerd -s c -l conf -d 'Specify configuration file'
complete -c nilfs_cleanerd -s p -l protection-period -d 'Override protection period with the specified number of seconds'

