# nilfs-resize
# Autogenerated from man page /usr/share/man/man8/nilfs-resize.8.gz
complete -c nilfs-resize -s y -l yes -l assume-yes -d 'Assume Yes to all queries and do not prompt'
complete -c nilfs-resize -s h -l help -d 'Display help message and exit'
complete -c nilfs-resize -s v -l verbose -d 'Verbose mode'
complete -c nilfs-resize -s V -l version -d 'Display version and exit.  AUTHOR Ryusuke Konishi <konishi. ryusuke@gmail'

