# nitrogen
# Autogenerated from man page /usr/share/man/man1/nitrogen.1.gz
complete -c nitrogen -l restore -d 'Restores previously saved pictures to the root displays'
complete -c nitrogen -l no-recurse -d 'Do not recurse into subdirectories of DIRECTORY'
complete -c nitrogen -l sort -d 'Sorts the background list by the given option'
complete -c nitrogen -l set-auto -d 'Set the background specified by DIRECTORY using the automatic size setting'
complete -c nitrogen -l set-centered -d 'Set the background specified by DIRECTORY using the centered size setting'
complete -c nitrogen -l set-scaled -d 'Set the background specified by DIRECTORY using the scaled size setting'
complete -c nitrogen -l set-tiled -d 'Set the background specified by DIRECTORY using the tiled size setting'
complete -c nitrogen -l set-zoom -d 'Set the background specified by DIRECTORY using the zoom size setting'
complete -c nitrogen -l set-zoom-fill -d 'Set the background specified by DIRECTORY using the zoom fill size setting'
complete -c nitrogen -l save -d 'Saves the background permanently in the config'
complete -c nitrogen -l set-color -d 'Sets background color in hex, #000000 by default'
complete -c nitrogen -l random -d 'Choose random background from config or given directory'
complete -c nitrogen -l head -d 'Select Xinerama/multihead display in GUI, 0'
complete -c nitrogen -l force-setter -d 'DEBUG: Forces the background setting engine to use a specific backend'
complete -c nitrogen -l help -d 'I\'m just here so I won\'t get fined.  FILES ~/. config/nitrogen/'

