# nvme-endurance-event-agg-log
# Autogenerated from man page /usr/share/man/man1/nvme-endurance-event-agg-log.1.gz
complete -c nvme-endurance-event-agg-log -s e -l log-entries -d 'Retrieve the Endurance Group Event Aggregate Log pending entries'
complete -c nvme-endurance-event-agg-log -s r -l rae -d 'Retain an Asynchronous Event'
complete -c nvme-endurance-event-agg-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

