# nvme-micron-selective-download
# Autogenerated from man page /usr/share/man/man1/nvme-micron-selective-download.1.gz
complete -c nvme-micron-selective-download -s f -l fw -d 'name of the firmware image file'
complete -c nvme-micron-selective-download -s s -l select -d 'flag that has following values'

