# nvme-lba-status-log
# Autogenerated from man page /usr/share/man/man1/nvme-lba-status-log.1.gz
complete -c nvme-lba-status-log -s r -l rae -d 'Retain an Asynchronous Event'
complete -c nvme-lba-status-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

