# nvme-id-ns
# Autogenerated from man page /usr/share/man/man1/nvme-id-ns.1.gz
complete -c nvme-id-ns -s n -l namespace-id -d 'Retrieve the identify namespace structure for the given nsid'
complete -c nvme-id-ns -s f -l force -d 'Request controller return the identify namespace structure even if the namesp…'
complete -c nvme-id-ns -s b -l raw-binary -d 'Print the raw buffer to stdout.  Structure is not parsed by program'
complete -c nvme-id-ns -s v -l vendor-specific -d 'In addition to parsing known fields, this option will dump the vendor specifi…'
complete -c nvme-id-ns -s H -l human-readable -d 'This option will parse and format many of the bit fields into human-readable …'
complete -c nvme-id-ns -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

