# nvme-lnvm-diag-set-bbtbl
# Autogenerated from man page /usr/share/man/man1/nvme-lnvm-diag-set-bbtbl.1.gz
complete -c nvme-lnvm-diag-set-bbtbl -l namespace-id -s n -d 'Namespace id to use'
complete -c nvme-lnvm-diag-set-bbtbl -l channel-id -s c -d 'Channel id'
complete -c nvme-lnvm-diag-set-bbtbl -l lun-id -s l -d 'LUN id'
complete -c nvme-lnvm-diag-set-bbtbl -l plane-id -s p -d 'Plane id'
complete -c nvme-lnvm-diag-set-bbtbl -l block-id -s b -d 'Block id'

