# nvme-zns-zone-mgmt-send
# Autogenerated from man page /usr/share/man/man1/nvme-zns-zone-mgmt-send.1.gz
complete -c nvme-zns-zone-mgmt-send -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-zns-zone-mgmt-send -s s -l start-lba -d 'The starting LBA of the zone to manage send'
complete -c nvme-zns-zone-mgmt-send -s l -l data-len -d 'Send data buffer length'
complete -c nvme-zns-zone-mgmt-send -l select-all -s a -d 'Send command to all zones'
complete -c nvme-zns-zone-mgmt-send -s z -l zsa -d 'Zone send action'
complete -c nvme-zns-zone-mgmt-send -s d -o data -d 'Optional file for data (default stdin)'
complete -c nvme-zns-zone-mgmt-send -s t -l timeout -d 'Override default timeout value.  In milliseconds'

