# nvme-id-domain
# Autogenerated from man page /usr/share/man/man1/nvme-id-domain.1.gz
complete -c nvme-id-domain -s d -l dom-id -d 'Retrieve the identify domain list data structure for the given domain id'
complete -c nvme-id-domain -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

