# nvme-zns-zone-append
# Autogenerated from man page /usr/share/man/man1/nvme-zns-zone-append.1.gz
complete -c nvme-zns-zone-append -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-zns-zone-append -s s -l zslba -s z -l data-size -d 'Size of data, in bytes'
complete -c nvme-zns-zone-append -s y -l metadata-size -d 'Size of metadata in bytes'
complete -c nvme-zns-zone-append -s d -l data -d 'Data file providing the data to write'
complete -c nvme-zns-zone-append -s M -l metadata -d 'Metadata file, if necessary'
complete -c nvme-zns-zone-append -s l -l limited-retry -d 'Sets the limited retry flag'
complete -c nvme-zns-zone-append -s f -l force-unit-access -d 'Set the force-unit access flag'
complete -c nvme-zns-zone-append -s r -l ref-tag -d 'Optional reftag when used with protection information'
complete -c nvme-zns-zone-append -s m -l app-tag-mask -d 'Optional application tag mask when used with protection information'
complete -c nvme-zns-zone-append -s a -l app-tag -d 'Optional application tag when used with protection information'
complete -c nvme-zns-zone-append -s p -l prinfo -d 'Protection Information field definition'

