# nvme-persistent-event-log
# Autogenerated from man page /usr/share/man/man1/nvme-persistent-event-log.1.gz
complete -c nvme-persistent-event-log -s a -l action -d 'While try to retrieve this log action the controller shall take during proces…'
complete -c nvme-persistent-event-log -s l -l log-len -d 'Allocates a buffer of <log-len> bytes size and requests this many bytes be re…'
complete -c nvme-persistent-event-log -s b -l raw-binary -d 'Print the raw persistent event log buffer to stdout'
complete -c nvme-persistent-event-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

