# nvme-ns-descs
# Autogenerated from man page /usr/share/man/man1/nvme-ns-descs.1.gz
complete -c nvme-ns-descs -s n -l namespace-id -d 'Retrieve the identify namespace identification descriptor structure for the g…'
complete -c nvme-ns-descs -s b -l raw-binary -d 'Print the raw buffer to stdout.  Structure is not parsed by program'
complete -c nvme-ns-descs -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

