# nvme-lnvm-diag-bbtbl
# Autogenerated from man page /usr/share/man/man1/nvme-lnvm-diag-bbtbl.1.gz
complete -c nvme-lnvm-diag-bbtbl -l namespace-id -s n -d 'Namespace id to use'
complete -c nvme-lnvm-diag-bbtbl -l channel-id -s c -d 'Channel id'
complete -c nvme-lnvm-diag-bbtbl -l lun-id -s l -d 'LUN id'
complete -c nvme-lnvm-diag-bbtbl -l raw-binary -s b -d 'Returns the bad block table in binary form without statistics'

