# nvme-get-lba-status
# Autogenerated from man page /usr/share/man/man1/nvme-get-lba-status.1.gz
complete -c nvme-get-lba-status -s n -l namespace-id -d 'Send the Get LBA Status command for the specified nsid'
complete -c nvme-get-lba-status -s s -l start-lba -d 'Starting LBA(SLBA) in 64-bit address of the first logical block addressed'
complete -c nvme-get-lba-status -s m -l max-dw -d 'Maximum Number of Dwords(MNDW) specifies maximum number of dwords to return'
complete -c nvme-get-lba-status -s a -l action -d 'Action Type(ATYPE) specifies the mechanism it uses in determining the LBA Sta…'
complete -c nvme-get-lba-status -s l -l range-len -d 'Range Length(RL) specifies the length of the range of contiguous LBAs beginni…'
complete -c nvme-get-lba-status -s t -l timeout -d 'Override default timeout value.  In milliseconds'
complete -c nvme-get-lba-status -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

