# nvme-resv-register
# Autogenerated from man page /usr/share/man/man1/nvme-resv-register.1.gz
complete -c nvme-resv-register -s n -l namespace-id -d 'Override the nsid field'
complete -c nvme-resv-register -s c -l crkey -d 'Current Reservation Key: If the Reservation Register Action is 001b (i. e'
complete -c nvme-resv-register -s k -l nrkey -d 'New Reservation Key: If the Reservation Register Action is 000b (i. e'
complete -c nvme-resv-register -s p -l cptpl -d 'Change Persist Through Power Loss State: This field allows the Persist Throug…'
complete -c nvme-resv-register -s r -l rrega -d 'Reservation Register Action: This field specifies the registration action tha…'
complete -c nvme-resv-register -s i -l iekey -d 'Ignore Existing Key: If this bit is set to a 1, then the Current Reservation …'

