# nvme-show-regs
# Autogenerated from man page /usr/share/man/man1/nvme-show-regs.1.gz
complete -c nvme-show-regs -s H -l human-readable -d 'Display registers or supported properties in human readable format'
complete -c nvme-show-regs -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

