# nvme-intel-lat-stats
# Autogenerated from man page /usr/share/man/man1/nvme-intel-lat-stats.1.gz
complete -c nvme-intel-lat-stats -s b -l raw-binary -d 'Print the raw buffer to stdout.  Structure is not parsed by program'
complete -c nvme-intel-lat-stats -s w -l write -d 'Get write statistics.  Read statistics are returned by default'

