# nvme-intel-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-intel-internal-log.1.gz
complete -c nvme-intel-internal-log -s l -l log -d 'Log type: 0, 1, or 2 for nlog, event log, and assert log, respectively'
complete -c nvme-intel-internal-log -s n -l namespace-id -d 'Namespace to use'
complete -c nvme-intel-internal-log -s o -l output-file -d 'Output file; defaults to device name provided'
complete -c nvme-intel-internal-log -s r -l region -d 'Select which core region to retrieve the log from'
complete -c nvme-intel-internal-log -s m -l nlognum -d 'When used with nlog, this specifies which nlog to read'

