# nvme-zns-zone-mgmt-recv
# Autogenerated from man page /usr/share/man/man1/nvme-zns-zone-mgmt-recv.1.gz
complete -c nvme-zns-zone-mgmt-recv -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-zns-zone-mgmt-recv -s s -l start-lba -d 'The starting LBA of the zone to manage receive'
complete -c nvme-zns-zone-mgmt-recv -s z -l zra -d 'Zone Receive Action'
complete -c nvme-zns-zone-mgmt-recv -s f -l zra-spec-feat -d 'Enable Zone Receive Action Specific features'
complete -c nvme-zns-zone-mgmt-recv -s o -l output-format -d 'Output format: normal|json|binary'
complete -c nvme-zns-zone-mgmt-recv -l data-len -s l
complete -c nvme-zns-zone-mgmt-recv -s a -l zrasf

