# nvme-fw-commit
# Autogenerated from man page /usr/share/man/man1/nvme-fw-commit.1.gz
complete -c nvme-fw-commit -s a -l action -d 'Commit Action: This field specifies the action that is taken on the image dow…'
complete -c nvme-fw-commit -s s -l slot -d 'Firmware Slot: Specifies the firmware slot that shall be used for the Commit …'
complete -c nvme-fw-commit -l bpid -s b -d 'Specifiies the Boot partition that shall be used for the Commit Action, if ap…'

