# nvme-write-zeroes
# Autogenerated from man page /usr/share/man/man1/nvme-write-zeroes.1.gz
complete -c nvme-write-zeroes -l start-block -s s -d 'Start block'
complete -c nvme-write-zeroes -l block-count -s c -d 'Number of logical blocks to write zeroes'
complete -c nvme-write-zeroes -l prinfo -s p -d 'Protection Information field definition'
complete -c nvme-write-zeroes -l ref-tag -s r -d 'Optional reftag when used with protection information'
complete -c nvme-write-zeroes -l app-tag-mask -s m -d 'Optional application tag mask when used with protection information'
complete -c nvme-write-zeroes -l app-tag -s a -d 'Optional application tag when used with protection information'
complete -c nvme-write-zeroes -l limited-retry -s l -d 'Sets the limited retry flag'
complete -c nvme-write-zeroes -l deac -s d -d 'Sets the DEAC bit, requesting controller deallocate the logical blocks'
complete -c nvme-write-zeroes -l force-unit-access -s f -d 'Set the force-unit access flag'
complete -c nvme-write-zeroes -l namespace-id -s n -d 'Namespace ID use in the command'
complete -c nvme-write-zeroes -l storage-tag -d 'Variable Sized Expected Logical Block Storage Tag(ELBST) and Expected Logical…'
complete -c nvme-write-zeroes -l storage-tag-check -s C -d 'This bit specifies the Storage Tag field shall be checked as part of end-to-e…'

