# nvme-lnvm-factory
# Autogenerated from man page /usr/share/man/man1/nvme-lnvm-factory.1.gz
complete -c nvme-lnvm-factory -l device-name -s d -d 'Device name to factory initialize'
complete -c nvme-lnvm-factory -l erase-only-marked -s e -d 'Erases only blocks that are marked in the bad block list'
complete -c nvme-lnvm-factory -l clear-host-side-blks -s s -d 'Remove host-side bad block marks.  This clear the media manager registration'
complete -c nvme-lnvm-factory -l clear-bb-blks -s b -d 'Removes the grown bad block marks.  Allowing them to be rediscovered'

