# nvme-dsm
# Autogenerated from man page /usr/share/man/man1/nvme-dsm.1.gz
complete -c nvme-dsm -s n -l namespace-id -d 'Sends the command with the requested nsid'
complete -c nvme-dsm -s a -l ctx-attrs -d 'Comma separated list of the context attributes in each range'
complete -c nvme-dsm -s b -l blocks -d 'Comma separated list of the number of blocks in each range'
complete -c nvme-dsm -s s -l slbs -d 'Comma separated list of the starting block in each range'
complete -c nvme-dsm -s d -l ad -d 'Attribute Deallocate'
complete -c nvme-dsm -s w -l idw -d 'Attribute Integral Dataset for Write'
complete -c nvme-dsm -s r -l idr -d 'Attribute Integral Dataset for Read'
complete -c nvme-dsm -s c -l cdw11 -d 'All the command command dword 11 attributes'

