# nvme-list-ctrl
# Autogenerated from man page /usr/share/man/man1/nvme-list-ctrl.1.gz
complete -c nvme-list-ctrl -s c -l cntid
complete -c nvme-list-ctrl -s n -l namespace-id
complete -c nvme-list-ctrl -s o -l output-format

