# nvme-pred-lat-event-agg-log
# Autogenerated from man page /usr/share/man/man1/nvme-pred-lat-event-agg-log.1.gz
complete -c nvme-pred-lat-event-agg-log -s e -l log-entries -d 'Retrieve the Predictable Latency Event Aggregate Log pending entries'
complete -c nvme-pred-lat-event-agg-log -s r -l rae -d 'Retain an Asynchronous Event'
complete -c nvme-pred-lat-event-agg-log -s b -l raw-binary -d 'Print the raw Predectible Latency Event Aggregate log buffer to stdout'
complete -c nvme-pred-lat-event-agg-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

