# nvme-zns-changed-zone-list
# Autogenerated from man page /usr/share/man/man1/nvme-zns-changed-zone-list.1.gz
complete -c nvme-zns-changed-zone-list -s o -l output-format -d 'Set the reporting format to normal, json, or binary'
complete -c nvme-zns-changed-zone-list -s r -l rae -d 'Retain an Asynchronous Event'

