# orte-info
# Autogenerated from man page /usr/share/man/man1/orte-info.1.gz
complete -c orte-info -s a -l all -d 'Show all configuration options and MCA parameters'
complete -c orte-info -l arch -d 'Show architecture ORTE was compiled on'
complete -c orte-info -s c -l config -d 'Show configuration options'
complete -c orte-info -o gmca -l gmca -d 'Pass global MCA parameters that are applicable to all contexts'
complete -c orte-info -s h -l help -d 'Shows help / usage message'
complete -c orte-info -l hostname -d 'Show the hostname that ORTE was configured and built on'
complete -c orte-info -l internal -d 'Show internal MCA parameters (not meant to be modified by users)'
complete -c orte-info -o mca -l mca -d 'Pass context-specific MCA parameters; they are considered global if --gmca is…'
complete -c orte-info -l param -d 'Show MCA parameters'
complete -c orte-info -l parsable -d 'When used in conjunction with other parameters, the output is displayed in a …'
complete -c orte-info -l path -d 'Show paths that ORTE was configured with'
complete -c orte-info -l pretty -d 'When used in conjunction with other parameters, the output is displayed in \'p…'
complete -c orte-info -l parseable -d 'Synonym for --parsable'
complete -c orte-info -s v -l version -d 'Show version of ORTE or a component'

