# pdfsig
# Autogenerated from man page /usr/share/man/man1/pdfsig.1.gz
complete -c pdfsig -o nssdir -d 'Specify the database directory containing the certificate and key database fi…'
complete -c pdfsig -o nocert -d 'Do not validate the certificate'
complete -c pdfsig -o dump -d 'Dump all signatures into current directory'
complete -c pdfsig -o sign -d 'Sign the document in the signature field with the given number'
complete -c pdfsig -o nick -d 'Use the certificate with the given nickname for signing'
complete -c pdfsig -o kpw -d 'Use the given password for the signing key (this might be missing if the key …'
complete -c pdfsig -o digest -d 'Use the given digest algorithm for signing (default: SHA256)'
complete -c pdfsig -o reason -d 'Set the given reason string for the signature (default: no reason set)'
complete -c pdfsig -o etsi -d 'Create a signature of type ETSI. CAdES. detached instead of adbe. pkcs7'
complete -c pdfsig -s v -d 'Print copyright and version information'
complete -c pdfsig -s h -d 'Print usage information.  ( -help and'
complete -c pdfsig -l help -d 'are equivalent'

