# pgmtoy4m
# Autogenerated from man page /usr/share/man/man1/pgmtoy4m.1.gz
complete -c pgmtoy4m -s v -d 'Set verbosity level.  (default: 0)'
complete -c pgmtoy4m -s h -d 'Print a usage summary and exit'
complete -c pgmtoy4m -s i -d 'Set the interlacing mode'
complete -c pgmtoy4m -s a -d 'Set the sample aspect ratio.    (default: 10:11)'

