# picom-trans
# Autogenerated from man page /usr/share/man/man1/picom-trans.1.gz
complete -c picom-trans -s w -d 'Specify the window id of the target window'
complete -c picom-trans -s n -d 'Specify and try to match a window name'
complete -c picom-trans -s c -d 'Specify the currently active window as target'
complete -c picom-trans -s s -d 'Select target window with mouse cursor'
complete -c picom-trans -s o -d 'Specify the new opacity value for the window'

