# pnmtoy4m
# Autogenerated from man page /usr/share/man/man1/pnmtoy4m.1.gz
complete -c pnmtoy4m -s o -d 'Frame offset:  skip output of the first \'num\' frames.   (default: 0)'
complete -c pnmtoy4m -s n -d 'Output a total of \'num\' output frames.   Use \'0\' to specify all frames'
complete -c pnmtoy4m -s B -d 'Interpret data as being  BGR rather than RGB'
complete -c pnmtoy4m -s r -d 'Repeat last input frame until output is complete'
complete -c pnmtoy4m -s D -d 'Treat each PNM image as a single (de-interleaved) field instead of a full fra…'
complete -c pnmtoy4m -s F -d 'Set framerate encoded in output stream, as an exact integer ratio'
complete -c pnmtoy4m -s A -d 'Set pixel aspect ratio encoded in output stream, as an exact integer ratio'
complete -c pnmtoy4m -s I -d 'Set the output interlacing mode, encoded in the output stream'

