# polybar
# Autogenerated from man page /usr/share/man/man1/polybar.1.gz
complete -c polybar -s h -l help -d 'Display help text and exit'
complete -c polybar -s v -l version -d 'Display build details and exit'
complete -c polybar -s l -l log -d 'nf Set the logging verbosity (default: notice) LEVEL is one of: error, warnin…'
complete -c polybar -s q -l quiet -d 'Be quiet (will override -l)'
complete -c polybar -s c -l config -d 'Specify the path to the configuration file'
complete -c polybar -s r -l reload -d 'Reload the application when the config file has been modified'
complete -c polybar -s d -l dump -d 'Print the value of the specified parameter PARAM in bar section and exit'
complete -c polybar -s m -l list-monitors -d 'Print list of available monitors and exit '
complete -c polybar -s M -l list-all-monitors -d 'Print list of available monitors and exit '
complete -c polybar -s w -l print-wmname -d 'Print the generated WM_NAME and exit'
complete -c polybar -s s -l stdout -d 'Output the data to stdout instead of drawing it to the X window'
complete -c polybar -s p -l png -d 'Save png snapshot to FILE after running for 3 seconds'

