# rdnssd
# Autogenerated from man page /usr/share/man/man8/rdnssd.8.gz
complete -c rdnssd -s f -l foreground -d 'Do not detach from the console.  Run the program in the foreground'
complete -c rdnssd -s H -l merge-hook -d 'Execute this hook whenever resolv. conf is updated'
complete -c rdnssd -s h -l help -d 'Display some help and exit'
complete -c rdnssd -s p -l pidfile -d 'Override the location of the pidfile'
complete -c rdnssd -s r -l resolv-file -d 'Set the path to the generated resolv. conf file'
complete -c rdnssd -s u -l user -d 'Override the user that the program will run as'
complete -c rdnssd -s V -l version -d 'Display program version and license and exit'

