# rmcp
# Autogenerated from man page /usr/share/man/man8/rmcp.8.gz
complete -c rmcp -s f -l force -d 'Ignore snapshots or nonexistent checkpoints'
complete -c rmcp -s i -l interactive -d 'Prompt before any removal'
complete -c rmcp -s h -l help -d 'Display help message and exit'
complete -c rmcp -s V -l version -d 'Display version and exit.  AUTHOR Koji Sato, Ryusuke Konishi <konishi'

