# sas_disk_blink
# Autogenerated from man page /usr/share/man/man8/sas_disk_blink.8.gz
complete -c sas_disk_blink -s h -l help -d 'print out the usage message then exit'
complete -c sas_disk_blink -s s -l set -d 'when NUM is 0 then the RLM field is cleared'
complete -c sas_disk_blink -s v -l verbose -d 'increase level or verbosity'

