# scsi_temperature
# Autogenerated from man page /usr/share/man/man8/scsi_temperature.8.gz
complete -c scsi_temperature -s h -l help -d 'print out the usage message then exit'
complete -c scsi_temperature -s v -l verbose -d 'increase level or verbosity'

