# scsi_stop
# Autogenerated from man page /usr/share/man/man8/scsi_stop.8.gz
complete -c scsi_stop -s h -l help -d 'print out the usage message then exit'
complete -c scsi_stop -s v -l verbose -d 'increase level or verbosity'
complete -c scsi_stop -s w -l wait -d 'wait for the spin down (stop) on each given DEVICE to complete'

