# scsi_readcap
# Autogenerated from man page /usr/share/man/man8/scsi_readcap.8.gz
complete -c scsi_readcap -s b -l brief -d 'shortens the output to two hexadecimal numbers, both prefixed by \'0x\''
complete -c scsi_readcap -s h -l help -d 'print out the usage message then exit'
complete -c scsi_readcap -s l -l long -d 'the default is to send the READ CAPACITY(10) command (i. e'
complete -c scsi_readcap -s v -l verbose -d 'increase level or verbosity'

