# sddm
# Autogenerated from man page /usr/share/man/man1/sddm.1.gz
complete -c sddm -l test-mode -d 'Start daemon in test mode'
complete -c sddm -l example-config -d 'Print the complete current configuration to stdout'
complete -c sddm -l help -s h -d 'Show help message and exit'

