# sg3_utils
# Autogenerated from man page /usr/share/man/man8/sg3_utils.8.gz
complete -c sg3_utils -s d -l dry-run -d 'utilities that can cause lots of user data to be lost or overwritten sometime…'
complete -c sg3_utils -s e -l enumerate -d 'some utilities (e. g'
complete -c sg3_utils -s h -s '?' -l help -d 'output the usage message then exit'
complete -c sg3_utils -s H -l hex -d 'for SCSI commands that yield a non-trivial response, print out that response …'
complete -c sg3_utils -s i -l in -d 'many SCSI commands fetch a significant amount of data (returned in the data-i…'
complete -c sg3_utils -l raw -d 'while --raw produces its output in "raw" binary'
complete -c sg3_utils -l inhex -d 'This option has the same or similar functionality as --in=FN'
complete -c sg3_utils -s m -l maxlen -d 'several important SCSI commands (e. g'
complete -c sg3_utils -s r -d 'for SCSI commands that yield a non-trivial response, output that response in …'
complete -c sg3_utils -s t -l timeout -d 'utilities that issue potentially long-running SCSI commands often have a'
complete -c sg3_utils -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg3_utils -s V -l version -d 'print the version string and then exit'

