# sg_get_elem_status
# Autogenerated from man page /usr/share/man/man8/sg_get_elem_status.8.gz
complete -c sg_get_elem_status -s b -l brief -d tbd
complete -c sg_get_elem_status -s f -l filter -d 'where FLT is placed in a two bit field called FILTER in the GET PHYSICAL ELEM…'
complete -c sg_get_elem_status -s h -l help -d 'output the usage message then exit'
complete -c sg_get_elem_status -s H -l hex -d 'output response to this command in ASCII hex'
complete -c sg_get_elem_status -s i -l inhex -d 'where FN is a function name whose contents are assumed to be ASCII hexadecimal'
complete -c sg_get_elem_status -s m -l maxlen -d 'where LEN is the (maximum) response length in bytes'
complete -c sg_get_elem_status -s r -l raw -d 'output response in binary (to stdout) unless the --inhex=FN option is also gi…'
complete -c sg_get_elem_status -s R -l readonly -d 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag)'
complete -c sg_get_elem_status -s t -l report-type -d 'where RT will be placed in the REPORT TYPE field of the GET PHYSICAL ELEMENT …'
complete -c sg_get_elem_status -s s -l starting -d 'where ELEM is the placed in the STARTING ELEMENT field of the GET PHYSICAL EL…'
complete -c sg_get_elem_status -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_get_elem_status -s V -l version -d 'print the version string and then exit'

