# sg_map26
# Autogenerated from man page /usr/share/man/man8/sg_map26.8.gz
complete -c sg_map26 -s d -l dev_dir -d 'where DIR is the directory to search for resultant device special files in (o…'
complete -c sg_map26 -s g -l given_is -d 'specifies the DEVICE is either a device special file (when the argument is 0)…'
complete -c sg_map26 -s h -l help -d 'output the usage message then exit'
complete -c sg_map26 -s r -l result -d 'specifies what variety of file (or files) that this utility tries to find'
complete -c sg_map26 -s s -l symlink -d 'when a device special file is being sought (i. e'
complete -c sg_map26 -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_map26 -s V -l version -d 'print the version string and then exit'

