# sg_map
# Autogenerated from man page /usr/share/man/man8/sg_map.8.gz
complete -c sg_map -s a -d 'assume the sg devices have alphabetical device names and loop through /dev/sg…'
complete -c sg_map -s h -d 'print usage message then exit'
complete -c sg_map -s i -d 'in addition do a standard INQUIRY and output vendor, product and revision str…'
complete -c sg_map -s n -d 'assume the sg devices have numeric device names and loop through /dev/sg0, /d…'
complete -c sg_map -o scd -d 'display mappings to SCSI cdrom device names of the form /dev/scd0, /dev/scd1 …'
complete -c sg_map -o sd -d 'display mappings to SCSI disk device names'
complete -c sg_map -o sr -d 'display mappings to SCSI cdrom device names of the form /dev/sr0, /dev/sr1 etc'
complete -c sg_map -o st -d 'display mappings to SCSI tape device names'
complete -c sg_map -s V -d 'print out version string then exit (without further ado)'
complete -c sg_map -s x -d 'after each active sg device name is displayed there are five digits: <host_nu…'

