# sg_prevent
# Autogenerated from man page /usr/share/man/man8/sg_prevent.8.gz
complete -c sg_prevent -s a -l allow -d 'allow medium removal.  This is equivalent to setting to \'--prevent=2\''
complete -c sg_prevent -s h -l help -d 'output the usage message then exit'
complete -c sg_prevent -s p -l prevent -d 'where PC is a prevent code value'
complete -c sg_prevent -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_prevent -s V -l version -d 'print the version string and then exit'

