# sg_rdac
# Autogenerated from man page /usr/share/man/man8/sg_rdac.8.gz
complete -c sg_rdac -s 6 -d 'Use the 6 byte cdb variants of the SCSI MODE SENSE and MODE SELECT commands'
complete -c sg_rdac -s a -d 'Transfer all (visible) devices'
complete -c sg_rdac -s f -d 'Transfer the device identified by LUN'
complete -c sg_rdac -s v -d 'be verbose'
complete -c sg_rdac -s V -d 'print version string then exit EXIT STATUS The exit status of sg_rdac is 0 wh…'

