# sg_rmsn
# Autogenerated from man page /usr/share/man/man8/sg_rmsn.8.gz
complete -c sg_rmsn -s h -l help -d 'output the usage message then exit'
complete -c sg_rmsn -s r -l raw -d 'sends the serial number (if found) to stdout'
complete -c sg_rmsn -s R -l readonly -d 'opens the DEVICE read-only rather than read-write which is the default'
complete -c sg_rmsn -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_rmsn -s V -l version -d 'print the version string and then exit'

