# sg_requests
# Autogenerated from man page /usr/share/man/man8/sg_requests.8.gz
complete -c sg_requests -s d -l desc -d 'sets the DESC bit in the REQUEST SENSE SCSI cdb'
complete -c sg_requests -s e -l error -d 'when used once it changes the REQUEST SENSE opcode from 0x3 to 0xff which sho…'
complete -c sg_requests -s h -l help -d 'output the usage message then exit'
complete -c sg_requests -s H -l hex -d 'output response in ASCII hexadecimal'
complete -c sg_requests -s m -l maxlen -d 'where LEN is the (maximum) response length in bytes'
complete -c sg_requests -s n -l num -d 'perform NUM SCSI REQUEST SENSE commands, stopping when either NUM is reached …'
complete -c sg_requests -l number -d 'same action as --num=NUM.  Added for compatibility with sg_turs'
complete -c sg_requests -s p -l progress -d 'show progress indication (a percentage) if available'
complete -c sg_requests -s r -l raw -d 'output response in binary (to stdout)'
complete -c sg_requests -s s -l status -d 'if the REQUEST SENSE command finished without error (as indicated by its SCSI…'
complete -c sg_requests -s t -l time -d 'time the SCSI REQUEST SENSE command(s) and calculate the average number of op…'
complete -c sg_requests -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_requests -s V -l version -d 'print the version string and then exit'

