# sg_seek
# Autogenerated from man page /usr/share/man/man8/sg_seek.8.gz
complete -c sg_seek -s T -l 10 -d 'use a 10 byte cdb command, either SEEK(10) or PRE-FETCH(10) command'
complete -c sg_seek -s c -l count -d 'NC is the number of commands (one of SEEK(10), PRE-FETCH(10) or PRE-FETCH(16)…'
complete -c sg_seek -s g -l grpnum -d 'GN is the group number, a value between 0 and 63 (in hex: 0x3f)'
complete -c sg_seek -s h -l help -d 'output the usage message then exit'
complete -c sg_seek -s i -l immed -d 'this option only applies to PRE-FETCH(10) and PRE-FETCH(16), setting the IMME…'
complete -c sg_seek -s l -l lba -d 'LBA is the starting logical block address that is placed in the command descr…'
complete -c sg_seek -s n -l num-blocks -d 'NUM is the number of blocks, starting at and including LBA, to place in the D…'
complete -c sg_seek -s p -l pre-fetch -d 'this option selects either PRE-FETCH(10) or PRE-FETCH(16) commands'
complete -c sg_seek -s r -l readonly -d 'this option sets a \'read-only\' flag when the underlying operating system open…'
complete -c sg_seek -s s -l skip -d 'SB is the number of logical block addresses to skip, between repeated command…'
complete -c sg_seek -s t -l time -d 'if given the elapsed time to execute NC commands is recorded'
complete -c sg_seek -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_seek -s V -l version -d 'print the version string and then exit'
complete -c sg_seek -s w -l wrap-offset -d 'WO is the number of blocks, relative to LBA, that when exceeded, set the next…'

