# sg_ses_microcode
# Autogenerated from man page /usr/share/man/man8/sg_ses_microcode.8.gz
complete -c sg_ses_microcode -s b -l bpw -d 'where CS is the chunk size in bytes and should be a multiple of 4'
complete -c sg_ses_microcode -s d -l dry-run -d 'the actual calls to perform SEND DIAGNOSTIC and RECEIVE DIAGNOSTIC RESULTS co…'
complete -c sg_ses_microcode -s e -l ealsd -d 'exit after last SEND DIAGNOSTIC command'
complete -c sg_ses_microcode -s h -l help -d 'output the usage message then exit'
complete -c sg_ses_microcode -s i -l id -d 'this option sets the BUFFER ID field in the Download microcode control dpage'
complete -c sg_ses_microcode -s I -l in -d 'read data from file FILE that will be sent with the SEND DIAGNOSTIC command'
complete -c sg_ses_microcode -s l -l length -d 'where LEN is the length, in bytes, of data to be written to the device'
complete -c sg_ses_microcode -s m -l mode -d 'this option sets the MODE'
complete -c sg_ses_microcode -s N -l non -d 'allow for non-standard implementations that reset their Download microcode en…'
complete -c sg_ses_microcode -s o -l offset -d 'this option sets the BUFFER OFFSET field in the Download microcode control dp…'
complete -c sg_ses_microcode -s s -l skip -d 'this option is only active when --in=FILE is given and FILE is a regular file…'
complete -c sg_ses_microcode -s S -l subenc -d 'SEID is the sub-enclosure identify'
complete -c sg_ses_microcode -s t -l tlength -d 'TLEN is the total length in bytes of the microcode to be (or being) downloaded'
complete -c sg_ses_microcode -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_ses_microcode -l raw -d 'deduced from --in=FILE or --raw is less (or no data is provided), then bytes …'
complete -c sg_ses_microcode -s V -l version -d 'print the version string and then exit'

