# sg_sat_read_gplog
# Autogenerated from man page /usr/share/man/man8/sg_sat_read_gplog.8.gz
complete -c sg_sat_read_gplog -s C -l ck_cond -d 'sets the CK_COND bit in the ATA PASS-THROUGH SCSI cdb'
complete -c sg_sat_read_gplog -s c -l count -d 'the number CO is placed in the "count" field in the ATA READ LOG EXT command'
complete -c sg_sat_read_gplog -s d -l dma -d 'use the ATA READ LOG DMA EXT command instead of ATA READ LOG EXT command'
complete -c sg_sat_read_gplog -s h -l help -d 'outputs the usage message summarizing command line options then exits'
complete -c sg_sat_read_gplog -s H -l hex -d 'when given once, the response is output in ASCII hexadecimal bytes'
complete -c sg_sat_read_gplog -s L -l log -d 'the number LA is known as the "log address" in the ATA standards and is place…'
complete -c sg_sat_read_gplog -s p -l page -d 'the number PN is the page number (within the log address) and is placed in bi…'
complete -c sg_sat_read_gplog -s l -l len -d 'this is the length of the SCSI cdb used for the ATA PASS-THROUGH commands'
complete -c sg_sat_read_gplog -s r -l readonly -d 'causes the DEVICE to be opened with the read-only flag (O_RDONLY in Unix)'
complete -c sg_sat_read_gplog -s v -l verbose -d 'increases the level or verbosity'
complete -c sg_sat_read_gplog -s V -l version -d 'print out version string NOTES Prior to Linux kernel 2. 6'

