# sg_turs
# Autogenerated from man page /usr/share/man/man8/sg_turs.8.gz
complete -c sg_turs -s d -l delay -d 'this option causes a delay of MS milliseconds to occur before each TEST UNIT …'
complete -c sg_turs -s h -l help -d 'print out the usage message then exit'
complete -c sg_turs -s l -l low -d 'when [--progress] is not being used, this utility tries to complete the SCSI …'
complete -c sg_turs -s n -l num -d 'performs TEST UNIT READY NUM times.  If not given defaults to 1'
complete -c sg_turs -l number -d 'same as --num=NUM'
complete -c sg_turs -s O -l old -d 'Switch to older style options.  Please use as first option'
complete -c sg_turs -s p -l progress -d 'show progress indication (a percentage) if available'
complete -c sg_turs -s t -l time -d 'after completing the requested number of TEST UNIT READY commands, outputs th…'
complete -c sg_turs -s v -l verbose -d 'increase level or verbosity'
complete -c sg_turs -s V -l version -d 'print version string then exit'
complete -c sg_turs -s N -l new -d 'Switch to the newer style options'

