# sg_write_buffer
# Autogenerated from man page /usr/share/man/man8/sg_write_buffer.8.gz
complete -c sg_write_buffer -s b -l bpw -d 'where CS is the chunk size in bytes'
complete -c sg_write_buffer -s d -l dry-run -d 'Do all the command line processing and sanity checks including reading the in…'
complete -c sg_write_buffer -s h -l help -d 'output the usage message then exit'
complete -c sg_write_buffer -s i -l id -d 'this option sets the buffer id field in the cdb'
complete -c sg_write_buffer -s I -l in -d 'read data from file FILE that will be sent with the WRITE BUFFER command'
complete -c sg_write_buffer -s l -l length -d 'where LEN is the length, in bytes, of data to be written to the device'
complete -c sg_write_buffer -s m -l mode -d 'this option sets the MODE field in the cdb'
complete -c sg_write_buffer -s o -l offset -d 'this option sets the BUFFER OFFSET field in the cdb'
complete -c sg_write_buffer -s r -l read-stdin -d 'read data from stdin until an EOF is detected'
complete -c sg_write_buffer -s s -l skip -d 'this option is only active when --in=FILE is given and FILE is a regular file…'
complete -c sg_write_buffer -s S -l specific -d 'MS is the MODE SPECIFIC field in the cdb'
complete -c sg_write_buffer -s t -l timeout -d 'TO is the command timeout (in seconds) for each WRITE BUFFER command issued b…'
complete -c sg_write_buffer -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_write_buffer -l raw
complete -c sg_write_buffer -s V -l version -d 'print the version string and then exit'

