# sg_wr_mode
# Autogenerated from man page /usr/share/man/man8/sg_wr_mode.8.gz
complete -c sg_wr_mode -s c -l contents -d 'where H,H'
complete -c sg_wr_mode -s d -l dbd -d 'disable block descriptors (DBD flag in cdb)'
complete -c sg_wr_mode -s f -l force -d 'force the contents string to be taken as the new mode page, or at least doesn…'
complete -c sg_wr_mode -s h -l help -d 'output the usage message then exit'
complete -c sg_wr_mode -s l -l len -d 'length of the SCSI commands (cdb) sent to DEVICE'
complete -c sg_wr_mode -s m -l mask -d 'where M,M'
complete -c sg_wr_mode -s p -l page -d 'where PG_H is the page code value to fetch and modify'
complete -c sg_wr_mode -s R -l rtd -d 'when this option is given most other actions are bypassed and a MODE SELECT(6…'
complete -c sg_wr_mode -s s -l save -d 'changes the "saved" mode page when MODE SELECT is successful.  By default (i'
complete -c sg_wr_mode -s 6 -l six -d 'this option will cause the 6 byte variants of MODE SENSE and MODE SELECT comm…'
complete -c sg_wr_mode -s v -l verbose -d 'increase the level of verbosity, (i. e.  debug output)'
complete -c sg_wr_mode -s V -l version -d 'print the version string and then exit'

