# sg_xcopy
# Autogenerated from man page /usr/share/man/man8/sg_xcopy.8.gz
complete -c sg_xcopy -s h -l help -d 'outputs usage message and exits'
complete -c sg_xcopy -l on_dst -d 'send the XCOPY command to the output file/device (i. e.  OFILE)'
complete -c sg_xcopy -l on_src -d 'send the XCOPY command to the input file/device (i. e.  IFILE)'
complete -c sg_xcopy -s v -l verbose -d 'equivalent to verbose=1.  When used twice, equivalent to verbose=2, etc'
complete -c sg_xcopy -s V -l version -d 'outputs version number information and exits'

