# sgm_dd
# Autogenerated from man page /usr/share/man/man8/sgm_dd.8.gz
complete -c sgm_dd -s d -l dry-run -d 'does all the command line parsing and preparation but bypasses the actual cop…'
complete -c sgm_dd -s h -l help -d 'outputs usage message and exits'
complete -c sgm_dd -s v -l verbose -d 'when used once, this is equivalent to verbose=1.  When used twice (e. g'
complete -c sgm_dd -s V -l version -d 'outputs version number information and exits'

