# showmount
# Autogenerated from man page /usr/share/man/man8/showmount.8.gz
complete -c showmount -s a -l all -d 'List both the client hostname or IP address and mounted directory in host:dir…'
complete -c showmount -s d -l directories -d 'List only the directories mounted by some client'
complete -c showmount -s e -l exports -d 'Show the NFS server\'s export list'
complete -c showmount -s h -l help -d 'Provide a short help summary'
complete -c showmount -s v -l version -d 'Report the current version number of the program'
complete -c showmount -l no-headers -d 'Suppress the descriptive headings from the output.  SEE ALSO rpc'

