# sload
# Autogenerated from man page /usr/share/man/man8/sload.f2fs.8.gz
complete -c sload -s f -d 'Specify the source directory path to be loaded'
complete -c sload -s t -d 'Specify the mount point path in the partition to load'
complete -c sload -s d -d 'Specify the level of debugging options'

