# smb2-quota
# Autogenerated from man page /usr/share/man/man1/smb2-quota.1.gz
complete -c smb2-quota -l help/-h
complete -c smb2-quota -l tabular/-t -d 'Amount Used | Quota Limit | Warning Level | Percent Used | Status | SID'
complete -c smb2-quota -l csv/-c -d 'SID,Amount Used,Quota Limit,Warning Level'
complete -c smb2-quota -l list/-l

