# smbtar
# Autogenerated from man page /usr/share/man/man1/smbtar.1.gz
complete -c smbtar -s s -d 'The SMB/CIFS server that the share resides upon'
complete -c smbtar -s x -d 'The share name on the server to connect to.  The default is "backup"'
complete -c smbtar -s X -d 'Exclude mode.  Exclude filenames.  from tar create or restore'
complete -c smbtar -s d -d 'Change to initial directory  before restoring / backing up files'
complete -c smbtar -s v -d 'Verbose mode'
complete -c smbtar -s p -d 'The password to use to access a share.  Default: none'
complete -c smbtar -s u -d 'The user id to connect as.  Default: UNIX login name'
complete -c smbtar -s a -d 'Reset DOS archive bit mode to indicate file has been archived'
complete -c smbtar -s t -d 'Tape device.  May be regular file or tape device'
complete -c smbtar -s b -d 'Blocking factor.  Defaults to 20.  See tar(1) for a fuller explanation'
complete -c smbtar -s N -d 'Backup only files newer than filename'
complete -c smbtar -s i -d 'Incremental mode; tar files are only backed up if they have the archive bit s…'
complete -c smbtar -s r -d 'Restore.  Files are restored to the share from the tar file'
complete -c smbtar -s l -d 'Log (debug) level.  Corresponds to the -d flag of smbclient(1)'

