# stoken-gui
# Autogenerated from man page /usr/share/man/man1/stoken-gui.1.gz
complete -c stoken-gui -l small -d 'Show a minimal window that only displays a tokencode and a progress bar'
complete -c stoken-gui -l rcfile -d 'Use an alternate . stokenrc file'
complete -c stoken-gui -l password -s p -d 'Use a password supplied from the command line, instead of prompting the user'
complete -c stoken-gui -l pin -s n -d 'Use a PIN supplied from the command line, instead of prompting the user'
complete -c stoken-gui -l force -s f -d 'Override token expiration date check'
complete -c stoken-gui -l file -d 'Use a token from file instead of the . stokenrc file'
complete -c stoken-gui -l token -d 'Use a token from the command line instead of the . stokenrc file'
complete -c stoken-gui -l random -d 'Generate a random token on the fly.   Used for testing or demonstrations only'
complete -c stoken-gui -l help -s h -d 'Display basic usage information'

