# syslinux
# Autogenerated from man page /usr/share/man/man1/syslinux.1.gz
complete -c syslinux -s i -l install -d 'Install \\s-1SYSLINUX\\s+1 on a new medium, overwriting any previously installe…'
complete -c syslinux -s U -l update -d 'Install \\s-1SYSLINUX\\s+1 on a new medium if and only if a version of \\s-1SYSL…'
complete -c syslinux -s s -l stupid -d 'Install a "safe, slow and stupid" version of \\s-1SYSLINUX\\s+1'
complete -c syslinux -s f -l force -d 'Force install even if it appears unsafe'
complete -c syslinux -s r -l raid -d 'RAID mode'
complete -c syslinux -s d -l directory -d 'Install the \\s-1SYSLINUX\\s+1 control files in a subdirectory with the specifi…'
complete -c syslinux -s t -l offset -d 'Indicates that the filesystem is at an offset from the base of the device or …'
complete -c syslinux -l once -d 'Declare a boot command to be tried on the first boot only'
complete -c syslinux -s O -l clear-once -d 'Clear the boot-once command'
complete -c syslinux -s H -l heads -d 'Override the detected number of heads for the geometry'
complete -c syslinux -s S -l sectors -d 'Override the detected number of sectors for the geometry'
complete -c syslinux -o style -d 'followed by any kernel parameters'
complete -c syslinux -s z -l zipdrive -d 'Assume zipdrive geometry (--heads 64 --sectors 32)'
complete -c syslinux -l ---------------------------------------------------- -d '<DLE> = <Ctrl-P> = ASCII 16     No      No      No <DC1> = <Ctrl-Q> = ASCII 1…'

