# time
# Autogenerated from man page /usr/share/man/man1/time.1.gz
complete -c time -s p -d 'When in the POSIX locale, use the precise traditional format'
complete -c time -s f -d 'option or the TIME environment variable'
complete -c time -l format -d 'Specify output format, possibly overriding the format specified in the enviro…'
complete -c time -l portability -d 'Use the portable output format'
complete -c time -s o -l output -d 'Do not send the results to stderr , but overwrite the specified file'
complete -c time -s a -l append -d '(Used together with -o. ) Do not overwrite but append'
complete -c time -s v -l verbose -d 'Give very verbose output about all the program knows about'
complete -c time -s q -l quiet -d 'Don\'t report abnormal program termination (where command is terminated by a s…'
complete -c time -l help -d 'Print a usage message on standard output and exit successfully'
complete -c time -s V -l version -d 'Print version information on standard output, then exit successfully'

