# tlp-stat
# Autogenerated from man page /usr/share/man/man8/tlp-stat.8.gz
complete -c tlp-stat -s b -l battery -d 'Show battery data'
complete -c tlp-stat -s c -l config -d 'Show configuration'
complete -c tlp-stat -s d -l disk -d 'Show disk data'
complete -c tlp-stat -s e -l pcie -d 'Show PCI(e) device data'
complete -c tlp-stat -s g -l graphics -d 'Show graphics card data'
complete -c tlp-stat -s p -l processor -d 'Show processor data'
complete -c tlp-stat -s r -l rfkill -d 'Show radio device data'
complete -c tlp-stat -s s -l system -d 'Show system information'
complete -c tlp-stat -s t -l temp -d 'Show temperatures and fan speed'
complete -c tlp-stat -s u -l usb -d 'Show USB device data'
complete -c tlp-stat -s w -l warn -d 'Show warnings'
complete -c tlp-stat -s P -l pev -d 'Monitor power supply udev events'
complete -c tlp-stat -l psup -d 'Show power supply diagnostic (view kernel data)'
complete -c tlp-stat -s T -l trace -d 'Show trace output'
complete -c tlp-stat -s v -l verbose -d 'Be more verbose'

