# udiskie
# Autogenerated from man page /usr/share/man/man8/udiskie.8.gz
complete -c udiskie -s h -l help
complete -c udiskie -s V -l version
complete -c udiskie -s v -l verbose
complete -c udiskie -s q -l quiet
complete -c udiskie -s c -l config
complete -c udiskie -s C -l no-config
complete -c udiskie -s p -l password-prompt
complete -c udiskie -l entry -l hide-text -l text
complete -c udiskie -s P -l no-password-prompt
complete -c udiskie -s a -l automount
complete -c udiskie -s A -l no-automount
complete -c udiskie -s n -l notify
complete -c udiskie -s N -l no-notify
complete -c udiskie -s t -l tray
complete -c udiskie -s s -l smart-tray
complete -c udiskie -s T -l no-tray
complete -c udiskie -s f -l file-manager
complete -c udiskie -s F -l no-file-manager
complete -c udiskie -l terminal
complete -c udiskie -l no-terminal
complete -c udiskie -l appindicator
complete -c udiskie -l no-appindicator
complete -c udiskie -l password-cache
complete -c udiskie -l no-password-cache
complete -c udiskie -l notify-command
complete -c udiskie -l info
complete -c udiskie -l no-notify-command
complete -c udiskie -l all
complete -c udiskie -s r -l recursive
complete -c udiskie -s R -l no-recursive
complete -c udiskie -s o -l options
complete -c udiskie -s d -l detach
complete -c udiskie -s D -l no-detach
complete -c udiskie -s e -l eject
complete -c udiskie -s E -l no-eject
complete -c udiskie -l force
complete -c udiskie -l no-force
complete -c udiskie -s l -l lock
complete -c udiskie -s L -l no-lock

