# uuidcdef
# Autogenerated from man page /usr/share/man/man1/uuidcdef.1.gz
complete -c uuidcdef -s c -l cdef -d 'Print the UUID as an initializer for a C structure, compatible with the type …'
complete -c uuidcdef -s r -l random -d 'Demand that the random-based algorithm be used to generate the UUID'
complete -c uuidcdef -s t -l time -d 'Demand that the time-based algorithm be used to generate the UUID. \\"'
complete -c uuidcdef -s u -l uuid -d 'Print the UUID like: "26175a27-c35d-4615-8dfb-1509eab28ef8"'

