# vdoimport
# Autogenerated from man page /usr/share/man/man8/vdoimport.8.gz
complete -c vdoimport -s f -l force -d 'Bypass some sanity checks'
complete -c vdoimport -s h -l help -d 'Display the help text'
complete -c vdoimport -s n -l name -d 'Specifies the name of converted VDO LV'
complete -c vdoimport -s v -l verbose -d 'Be more verbose'
complete -c vdoimport -s y -l yes -d 'Answer "yes" at any prompts'
complete -c vdoimport -l dry-run -d 'Print commands without running them.  DIAGNOSTICS'

