# xorriso-dd-target
# Autogenerated from man page /usr/share/man/man1/xorriso-dd-target.1.gz
complete -c xorriso-dd-target -o plug_test -d 'Find the target device by asking the user to press the Enter key when the des…'
complete -c xorriso-dd-target -o list_all -d 'Print list of all found devices with advice, vendor and model.  One per line'
complete -c xorriso-dd-target -o list_long -d 'After each result line, which shows reasons, add an additional listing of the…'
complete -c xorriso-dd-target -o with_vendor_model -d 'Print vendor and model with each submitted device name'
complete -c xorriso-dd-target -o max_size -d 'Set the upper byte size limit for advisable devices'
complete -c xorriso-dd-target -o min_size -d 'Set the lower byte size limit for advisable devices'
complete -c xorriso-dd-target -o look_for_iso -d 'Demand presence of an ISO 9660 filesystem'
complete -c xorriso-dd-target -o with_sudo -d 'Run \'lsblk -o FSTYPE\' by sudo'
complete -c xorriso-dd-target -o trust_lsblk_udev -d 'Suppress the reason no_fs_while_not_su- if lsblk is linked with libudev. so'
complete -c xorriso-dd-target -o image_file -d 'Set the path of the image file which shall be written to a device'
complete -c xorriso-dd-target -o DO_WRITE -d 'Write the given -image_file to the one advisable device that is found'
complete -c xorriso-dd-target -o no_pacifier -d 'Do not use dd options to print progress messages and to perform synchronized …'
complete -c xorriso-dd-target -o dummy -d 'Report the -DO_WRITE actions but do not perform them'
complete -c xorriso-dd-target -o dummy_force -d 'If a single device name is given, do a run of -dummy -DO_WRITE even against t…'
complete -c xorriso-dd-target -o version -d 'Print the program name, version text, and timestamp to stdout and then end th…'
complete -c xorriso-dd-target -o help -d 'Print the help text to stdout and then end the program'

