# xorriso-tcltk
# Autogenerated from man page /usr/share/man/man1/xorriso-tcltk.1.gz
complete -c xorriso-tcltk -l help -d 'Print a help text with the complete list of start options and exit'
complete -c xorriso-tcltk -l no_extract -d 'Do not allow extraction of files from ISO filesystem to hard disk'
complete -c xorriso-tcltk -l geometry -d 'Set the position of the main window on the screen'
complete -c xorriso-tcltk -l click_to_focus -d 'Chooses that input fields and list boxes get the keyboard focus only when bei…'
complete -c xorriso-tcltk -o 0X -o 0Y
complete -c xorriso-tcltk -l auto_focus -d 'Chooses that the keyboard focus is where the mouse pointer is'

