# y4mcolorbars
# Autogenerated from man page /usr/share/man/man1/y4mcolorbars.1.gz
complete -c y4mcolorbars -s n -d 'Output a total of \'num\' output frames.  [default: 1]'
complete -c y4mcolorbars -s F -d 'Set framerate encoded in output stream, as an exact integer ratio'
complete -c y4mcolorbars -s W -d 'Set frame width.  [default: 720]'
complete -c y4mcolorbars -s H -d 'Set frame height.  [default: 480]'
complete -c y4mcolorbars -s A -d 'Set pixel aspect ratio encoded in output stream, as an exact integer ratio'
complete -c y4mcolorbars -s I -d 'Set interlacing mode, used to interpret the PPM image(s), and also encoded in…'
complete -c y4mcolorbars -s Q -d 'Data to place in the "-I/+Q" patches in the bottom row of the pattern:  0 -  …'
complete -c y4mcolorbars -s S -d 'Set chroma subsampling mode'

