# yad-tools
# Autogenerated from man page /usr/share/man/man1/yad-tools.1.gz
complete -c yad-tools -s f -l pfd -d 'This mode is intended to transform font names from pango to xft specification…'
complete -c yad-tools -s i -l icon -d 'This mode is intended to get full path to icon file from icon name'
complete -c yad-tools -l show-langs -d 'Show list of available languages for spell checking'
complete -c yad-tools -l show-themes -d 'Show list of available GtkSourceView themes'
complete -c yad-tools -s x -l xft -d 'Print font name in xft format.  This is default'
complete -c yad-tools -s p -l pango -d 'Print font name in pango format. SS Icon mode options'
complete -c yad-tools -s s -l size -d 'Use specified icon size.  Default is 24'
complete -c yad-tools -s t -l type -d 'Obtain icon size from one of predefined GTK+ types'
complete -c yad-tools -l theme -d 'Use specified icon theme instead of default'

