# yuvfps
# Autogenerated from man page /usr/share/man/man1/yuvfps.1.gz
complete -c yuvfps -s r -d 'Specifies the resulting stream frame rate'
complete -c yuvfps -s s -d 'Ignores the frame rate in the input stream and assumes this frame rate for th…'
complete -c yuvfps -s i -d 'Specifies the interlacing mode of the resulting stream'
complete -c yuvfps -s I -d 'Ignores the interlacing mode information in the input stream and assumes this…'
complete -c yuvfps -s c -d 'Changes the stream header frame rate and interlacing mode in the output strea…'
complete -c yuvfps -s n -d 'By default yuvfps tries to find a normalized framerate'
complete -c yuvfps -s w -d 'Produce each output frame/field as a weighted average of the two temporally c…'
complete -c yuvfps -s v -d 'Set verbosity level.   0 = warnings and error messages only'

