# yuvkineco
# Autogenerated from man page /usr/share/man/man1/yuvkineco.1.gz
complete -c yuvkineco -s F -d 'Set output fps code (default: same as input)'
complete -c yuvkineco -s C -d 'Specify 2-3 pull down cycle list file name to write'
complete -c yuvkineco -s O -d 'Specify cycle list name to read with old yuv stream to retry'
complete -c yuvkineco -s N -d 'Specify cycle list name to read with new yuv stream to repair'
complete -c yuvkineco -s n -d 'Specify noise level of input (default: 10)'
complete -c yuvkineco -s c -d 'Specify threshold to decide pictures in 2 frames are same (default: 4)'
complete -c yuvkineco -s i -d 'yuvkineco deinterlaces each frame after 2-3 pulldown reverting process, speci…'
complete -c yuvkineco -s u -d 'Set interlace information in header of output to unknown (default: non-interl…'

