# yuvplay
# Autogenerated from man page /usr/share/man/man1/yuvplay.1.gz
complete -c yuvplay -s s -d 'The size of the SDL window'
complete -c yuvplay -s t -d 'Set the window title'
complete -c yuvplay -s f -d 'Override the framerate specified in the input stream header'
complete -c yuvplay -s c -d 'By default, yuvplay will try to play at the framerate of the input movie'
complete -c yuvplay -s v -d 'Set the verbosity of user feedback'

