# yuvycsnoise
# Autogenerated from man page /usr/share/man/man1/yuvycsnoise.1.gz
complete -c yuvycsnoise -s t -d 'test.  Instead of noise reduction, noises will be marked as black pixel'
complete -c yuvycsnoise -s m -d '(default: tbic). br Select method'
complete -c yuvycsnoise -s S -d '(default: 4)'
complete -c yuvycsnoise -s T -d '(default: 32,255)'
complete -c yuvycsnoise -s B -d '(default: 32,255)'
complete -c yuvycsnoise -s I -d '(default: 16,255)'
complete -c yuvycsnoise -s C -d '(default: 12,255)'

