# zbarcam
# Autogenerated from man page /usr/share/man/man1/zbarcam.1.gz
complete -c zbarcam -s h -l help -d 'Print a short help message describing command line options to standard output…'
complete -c zbarcam -l version -d 'Print program version information to standard output and exit'
complete -c zbarcam -s v -l verbose -d 'Increase debug output level.  Multiple -v options create more spew'
complete -c zbarcam -s q -l quiet -d 'Quiet operation; disable the audible beep otherwise emitted when a symbol is …'
complete -c zbarcam -l nodisplay -d 'Disable output video window'
complete -c zbarcam -l xml -d 'Stream results using an XML output format'
complete -c zbarcam -l raw -d 'Use raw symbol data output format'
complete -c zbarcam -l prescale -d 'Request video input scaling from the camera driver'
complete -c zbarcam -o Sconfig -l set

