# zbarimg
# Autogenerated from man page /usr/share/man/man1/zbarimg.1.gz
complete -c zbarimg -s h -l help -d 'Print a short help message describing command line options to standard output…'
complete -c zbarimg -l version -d 'Print program version information to standard output and exit'
complete -c zbarimg -s v -l verbose -d 'Increase debug output level.  Multiple -v options create more spew'
complete -c zbarimg -s q -l quiet -d 'Quiet operation; only output decoded symbol data'
complete -c zbarimg -s d -l display -s D -l nodisplay -d 'Enable/disable display of subsequent image files, until next --display or --n…'
complete -c zbarimg -l xml -l noxml -d 'Enable/disable result output using an XML format'
complete -c zbarimg -l raw -d 'Enable raw symbol data output'
complete -c zbarimg -o Sconfig -l set

