# zretune
# Autogenerated from man page /usr/share/man/man1/zretune.1.gz
complete -c zretune -l help -d 'Display a short help text'
complete -c zretune -l cent -d 'The number of cents by which the pitch is changed'
complete -c zretune -l wav -d 'Produce a WAV file, or for more than 2 channels, a WAVEX file'
complete -c zretune -l amb -d 'Produce a WAVEX file with the Ambisonic GUID.  Such files should have the  '
complete -c zretune -l caf -d 'Produce a Core Audio file'
complete -c zretune -l aiff -d 'Produce an AIFF file'
complete -c zretune -l flac -d 'Produce a FLAC file. SS Output sample format'
complete -c zretune -l 16bit -d 'Output sample format is signed 16-bit'
complete -c zretune -l 24bit -d 'Output sample format is 24-bit.  This is the default'
complete -c zretune -l float -d 'Output sample format is 32-bit floating point. SS Dithering'
complete -c zretune -l rec -d 'Add white dithering noise with a rectangular distribution'
complete -c zretune -l tri -d 'Add filtered noise with a triangular distribution'
complete -c zretune -l lips -d 'This uses the optimal error feedback filter described by  Stanley Lipschitz'
complete -c zretune -l pad -d 'Insert zero valued input samples at the start and end so that the output incl…'

